<a href="https://colab.research.google.com/github/IanCastillo0621/tsp-bio-inspired-algorithms/blob/main/Algoritmo_Exacto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Data from GitHub

In [1]:
!git clone https://github.com/IanCastillo0621/tsp-bio-inspired-algorithms.git

Cloning into 'tsp-bio-inspired-algorithms'...
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 22 (delta 2), reused 11 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (22/22), 8.96 MiB | 16.62 MiB/s, done.
Resolving deltas: 100% (2/2), done.

In [5]:
!pip install gamspy

Collecting gamspy
  Downloading gamspy-1.19.2-py3-none-any.whl.metadata (3.9 kB)
Collecting gamsapi<53.0.0,>=52.2.0 (from gamspy)
  Downloading gamsapi-52.5.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.9 kB)
Collecting gamspy_base<53.0.0,>=52.2.0 (from gamspy)
  Downloading gamspy_base-52.5.0-py3-none-manylinux_2_28_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: pandas<2.4,>=2.2.2 in /usr/local/lib/python3.12/dist-packages (from gamspy) (2.2.2)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.12/dist-packages (from gamspy) (2.12.3)
Requirement already satisfied: requests>=2.28.0 in /usr/local/lib/python3.12/dist-packages (from gamspy) (2.32.4)
Requirement already satisfied: typer>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from gamspy) (0.21.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas<2.4,>=2.2.2->gamspy) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<2.4,>=2.2.2->gamspy) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<2.4,>=2.2.2->gamspy) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<2.4,>=2.2.2->gamspy) (2025.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->gamspy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->gamspy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->gamspy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->gamspy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.0->gamspy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.0->gamspy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.0->gamspy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.0->gamspy) (2026.1.4)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.16.0->gamspy) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.16.0->gamspy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.16.0->gamspy) (13.9.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<2.4,>=2.2.2->gamspy) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->typer>=0.16.0->gamspy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->typer>=0.16.0->gamspy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer>=0.16.0->gamspy) (0.1.2)
Downloading gamspy-1.19.2-py3-none-any.whl (234 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 234.4/234.4 kB 3.3 MB/s eta 0:00:00
Downloading gamsapi-52.5.0-cp312-cp312-manylinux_2_28_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 17.5 MB/s eta 0:00:00
Downloading gamspy_base-52.5.0-py3-none-manylinux_2_28_x86_64.whl (30.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.5/30.5 MB 12.3 MB/s eta 0:00:00
Installing collected packages: gamspy_base, gamsapi, gamspy
Successfully installed gamsapi-52.5.0 gamspy-1.19.2 gamspy_base-52.5.0

In [4]:
import pandas as pd
import numpy as np
from collections import Counter

In [9]:
from gamspy import Container, Set, Parameter, Variable, Equation, Model, Sum, Alias, Options, Ord, Card
import gamspy as gp

# Generate Distance Matrix (matriz_distancias.csv)

The indices were chosen to serve as unique identifiers for each address and are referred to throughout the code as the address unique identifier index.

In [ ]:
df = pd.read_csv('/content/tsp-bio-inspired-algorithms/Data_for_algorithms/Addresses_Jalisco_Mexico.csv')
df

,colonia,Calle,Num Cas,CP,Estado,Full Address,Latitude,Longitude
0,UNIDAD HABITACIONAL FOVISSSTE ESTADIO,LISBOA,28,44307,Guadalajara,UNIDAD HABITACIONAL FOVISSSTE ESTADIO LISBOA 2...,20.710556,-103.324800
1,INDEPENDENCIA,ROGELIO BACON,2280,44290,Guadalajara,INDEPENDENCIA ROGELIO BACON 2280 44290 Guadala...,20.704919,-103.333184
2,BOSQUES DE LA CANTERA,PRIV OPALO,17,44306,Guadalajara,BOSQUES DE LA CANTERA PRIV OPALO 17 44306 Guad...,20.715553,-103.315642
3,JARDINES DE LOS POETAS,JOSE FERNANDEZ,3365,44820,Guadalajara,JARDINES DE LOS POETAS JOSE FERNANDEZ 3365 448...,20.648905,-103.293064
4,LOMAS DEL GALLO,FERNANDO SOLIS,1338,44760,Guadalajara,LOMAS DEL GALLO FERNANDO SOLIS 1338 44760 Guad...,20.679106,-103.270528
...,...,...,...,...,...,...,...,...
424,MESA COLORADA PTE,DELLI,1825,45189,Jalisco,MESA COLORADA PTE DELLI 1825 45189 Jalisco,20.770500,-103.347956
425,VILLA FONTANA DIAMANTE,AV LAS TORRES,1896,45200,Jalisco,VILLA FONTANA DIAMANTE AV LAS TORRES 1896 4520...,20.776952,-103.471263
426,REAL DE TESISTAN,PASEO DE LA ARB,176,45200,Jalisco,REAL DE TESISTAN PASEO DE LA ARB 176 45200 Jal...,20.782630,-103.472207
427,EL CENTINELA 2,HIDALGO,310,45187,Jalisco,EL CENTINELA 2 HIDALGO 310 45187 Jalisco,20.758818,-103.379668
428,LA VENTA DEL ASTILLE,JILGEROS,33,45221,Jalisco,LA VENTA DEL ASTILLE JILGEROS 33 45221 Jalisco,20.732197,-103.539289

In [ ]:
# Create distance matrix (matriz_distancias.csv)
n = len(df)
matriz_dist = np.zeros((n, n))

for i in range(n):
    for j in range(n):
        # Eucledian distance Lat-Lon (Aproximate)
        x1, y1 = df.loc[i, ['Latitude', 'Longitude']]
        x2, y2 = df.loc[j, ['Latitude', 'Longitude']]
        matriz_dist[i, j] = np.sqrt((x1 - x2)**2 + (y1 - y2)**2)

# Convert to a DataFrame using the original dataset indices as both row and column labels.
df_matriz_dist = pd.DataFrame(matriz_dist, index=df.index, columns=df.index)

print(df_matriz_dist)

          0         1         2         3         4         5         6    \
0    0.000000  0.010103  0.010432  0.069341  0.062726  0.027534  0.071092
1    0.010103  0.000000  0.020513  0.068901  0.067766  0.019582  0.074029
2    0.010432  0.020513  0.000000  0.070369  0.057998  0.036466  0.068528
3    0.069341  0.068901  0.070369  0.000000  0.037683  0.056842  0.024111
4    0.062726  0.067766  0.057998  0.037683  0.000000  0.066255  0.017227
..        ...       ...       ...       ...       ...       ...       ...
424  0.064261  0.067224  0.063745  0.133412  0.119783  0.085661  0.131935
425  0.160810  0.155738  0.167295  0.219433  0.223312  0.162831  0.229297
426  0.164084  0.159268  0.170329  0.223551  0.226698  0.166850  0.233002
427  0.073074  0.071175  0.077274  0.139934  0.135151  0.085004  0.144149
428  0.215578  0.207902  0.224265  0.259932  0.273955  0.208107  0.275530

          7         8         9    ...       419       420       421  \
0    0.058367  0.023118  0.042338  ...  0.135907  0.022340  0.037867
1    0.049645  0.030740  0.037785  ...  0.131070  0.020309  0.036830
2    0.067355  0.018964  0.048095  ...  0.142260  0.028999  0.042405
3    0.060359  0.089332  0.036628  ...  0.195699  0.089174  0.105684
4    0.084391  0.074751  0.054749  ...  0.198501  0.085062  0.100039
..        ...       ...       ...  ...       ...       ...       ...
424  0.111393  0.045314  0.105004  ...  0.099424  0.048485  0.034681
425  0.167215  0.155635  0.182905  ...  0.025096  0.138663  0.125378
426  0.171917  0.158213  0.187083  ...  0.028203  0.141856  0.128219
427  0.103245  0.063152  0.106237  ...  0.068505  0.051217  0.035223
428  0.200510  0.217471  0.224417  ...  0.099109  0.195672  0.186619

          422       423       424       425       426       427       428
0    0.032424  0.084437  0.064261  0.160810  0.164084  0.073074  0.215578
1    0.036292  0.074955  0.067224  0.155738  0.159268  0.071175  0.207902
2    0.032438  0.094604  0.063745  0.167295  0.170329  0.077274  0.224265
3    0.101560  0.120147  0.133412  0.219433  0.223551  0.139934  0.259932
4    0.089891  0.136208  0.119783  0.223312  0.226698  0.135151  0.273955
..        ...       ...       ...       ...       ...       ...       ...
424  0.031865  0.100435  0.000000  0.123476  0.124842  0.033796  0.195129
425  0.140321  0.109439  0.123476  0.000000  0.005756  0.093372  0.081428
426  0.142780  0.114602  0.124842  0.005756  0.000000  0.095554  0.083925
427  0.047493  0.074931  0.033796  0.093372  0.095554  0.000000  0.161825
428  0.203893  0.139802  0.195129  0.081428  0.083925  0.161825  0.000000

[429 rows x 429 columns]

# Defining Functions (Counter/Reconstruct_Path)

In [ ]:
# Function that counts the number of appearances of elements within a list.
def count(list):
  # Count instances
  conteo = Counter(list)

  # Print unique values and number of appearances.
  for valor, cantidad in conteo.items():
      if cantidad > 1:
          print(f"Valor {valor} se repite {cantidad} veces")

  # Print number of unique values
  print(f"Cantidad de valores únicos: {len(conteo)}")
  return

In [ ]:
# Reconstructs a TSP tour by iteratively following (i → j) edges in a DataFrame starting from the first node.

def reconstruct_tsp_path_safe(camino_df):
  camino_df.reset_index(inplace=True, drop = True)

  count = 0

  path = [camino_df["i"][0]]

  while count != camino_df.shape[0]:
    path.append(camino_df[camino_df["i"] == path[-1]]["j"].values[0])
    count += 1

  return path

# Define Function (Random submatrix generator).

In [ ]:

def generar_submatrices_distancias(df_dist, n_subconjuntos=10, tamaño_sub=40, seed=None):
    if seed is not None:
        np.random.seed(seed)

    # Choose a defined amount of random address unique identifiers indexes.
    ubicaciones = df_dist.index.tolist()
    # Store random address unique identifiers indexes that where chosen.
    subconjuntos = []
    # Store Distance matrices.
    matrices = []

    for i in range(n_subconjuntos):
        seleccion = np.random.choice(ubicaciones, tamaño_sub, replace=False)
        submat = df_dist.loc[seleccion, seleccion].copy()

        # Due to precision, addresses close to eachother showed a distance of 0. We changed those values to 0.1 km.
        submat = submat.mask((submat == 0) & (np.eye(tamaño_sub) == 0), 0.1)

        # Change diagonal to 9999 km to reperesent actions the tourist can't do, such as stay in the same address.
        np.fill_diagonal(submat.values, 9999)

        subconjuntos.append(seleccion)
        matrices.append(submat)

        print(f"✅ Subconjunto {i+1}: {len(seleccion)} ubicaciones seleccionadas")

    return matrices, subconjuntos

# Solving instances of 40 addresses

## Generate distance sub matrices (matrices_40.xlsx).

In [ ]:
# Generate 10 instances of sub matrices consisting of 40 randomly chosen addresses. (matrices_40.xlsx)
matrices_40, subconjuntos = generar_submatrices_distancias(df_matriz_dist)

✅ Subconjunto 1: 40 ubicaciones seleccionadas
✅ Subconjunto 2: 40 ubicaciones seleccionadas
✅ Subconjunto 3: 40 ubicaciones seleccionadas
✅ Subconjunto 4: 40 ubicaciones seleccionadas
✅ Subconjunto 5: 40 ubicaciones seleccionadas
✅ Subconjunto 6: 40 ubicaciones seleccionadas
✅ Subconjunto 7: 40 ubicaciones seleccionadas
✅ Subconjunto 8: 40 ubicaciones seleccionadas
✅ Subconjunto 9: 40 ubicaciones seleccionadas
✅ Subconjunto 10: 40 ubicaciones seleccionadas

In [ ]:
for i in matrices_40:
  display(i)

,143,186,4,37,197,267,24,217,215,259,...,387,178,32,213,159,273,375,304,211,348
143,9999.000000,0.150940,0.044168,0.054234,0.151789,0.392502,0.016902,0.119113,0.100696,0.134617,...,0.152908,0.129240,0.057463,0.106890,0.123275,0.218469,0.107404,0.102064,0.151445,0.199640
186,0.150940,9999.000000,0.191741,0.107635,0.023971,0.292533,0.143554,0.035640,0.057062,0.016510,...,0.008116,0.081714,0.186236,0.157396,0.043810,0.197776,0.044580,0.067055,0.008136,0.234944
4,0.044168,0.191741,9999.000000,0.098318,0.194549,0.435474,0.058737,0.161575,0.144082,0.175247,...,0.194434,0.173146,0.069878,0.140571,0.166819,0.255511,0.147360,0.146149,0.191390,0.226529
37,0.054234,0.107635,0.098318,9999.000000,0.103108,0.339102,0.040665,0.072621,0.051718,0.092646,...,0.107633,0.075094,0.078627,0.076479,0.072683,0.174416,0.069905,0.049223,0.110254,0.172204
197,0.151789,0.023971,0.194549,0.103108,9999.000000,0.272909,0.142031,0.033089,0.051653,0.030414,...,0.016271,0.061750,0.180251,0.142128,0.031125,0.174324,0.053449,0.056361,0.032107,0.214520
267,0.392502,0.292533,0.435474,0.339102,0.272909,9999.000000,0.376831,0.299366,0.306242,0.303264,...,0.284854,0.264638,0.386779,0.308887,0.285969,0.206681,0.323856,0.297338,0.299375,0.282542
24,0.016902,0.143554,0.058737,0.040665,0.142031,0.376831,9999.000000,0.110111,0.090404,0.127603,...,0.144714,0.114655,0.050736,0.090414,0.112396,0.201567,0.101560,0.089744,0.144902,0.184046
217,0.119113,0.035640,0.161575,0.072621,0.033089,0.299366,0.110111,9999.000000,0.021434,0.023265,...,0.035013,0.056534,0.151022,0.123749,0.016283,0.178474,0.024941,0.032567,0.039829,0.206348
215,0.100696,0.057062,0.144082,0.051718,0.051653,0.306242,0.090404,0.021434,9999.000000,0.043704,...,0.056211,0.049095,0.129801,0.104562,0.022822,0.170263,0.031311,0.015473,0.060906,0.190921
259,0.134617,0.016510,0.175247,0.092646,0.030414,0.303264,0.127603,0.023265,0.043704,9999.000000,...,0.020813,0.076787,0.171247,0.147013,0.036131,0.196860,0.028091,0.055831,0.017608,0.228630
171,0.079034,0.144406,0.114819,0.050892,0.132705,0.326737,0.062383,0.109162,0.088328,0.132004,...,0.142053,0.081711,0.060666,0.028280,0.102221,0.140754,0.114807,0.077484,0.148988,0.123889
312,0.138467,0.013247,0.179772,0.094428,0.022783,0.295649,0.130675,0.022464,0.043854,0.007631,...,0.014759,0.072079,0.173012,0.145169,0.032325,0.190977,0.033652,0.054352,0.017841,0.224754
412,0.081985,0.150758,0.116036,0.056989,0.138764,0.328223,0.065621,0.115574,0.094796,0.138456,...,0.148315,0.086693,0.058583,0.024972,0.108405,0.139579,0.121340,0.083780,0.155403,0.119281
404,0.127043,0.041171,0.170536,0.076550,0.027372,0.283458,0.116236,0.017076,0.026473,0.034754,...,0.037074,0.042039,0.153036,0.116684,0.003868,0.162745,0.041882,0.028991,0.047681,0.194474
325,0.091722,0.178975,0.116766,0.081239,0.167009,0.343871,0.077645,0.143695,0.122763,0.166463,...,0.176599,0.113552,0.049054,0.035619,0.136697,0.146594,0.148404,0.112046,0.183513,0.109907
113,0.053320,0.129719,0.093900,0.024745,0.122502,0.341943,0.036487,0.094165,0.072754,0.115446,...,0.128898,0.083459,0.057871,0.057610,0.091413,0.165388,0.094112,0.066366,0.133000,0.153531
379,0.039928,0.111153,0.081300,0.031025,0.113285,0.364710,0.036276,0.080279,0.063506,0.094774,...,0.113393,0.100217,0.086327,0.105446,0.086325,0.205293,0.067476,0.068203,0.111526,0.201563
13,0.018402,0.152019,0.039897,0.065442,0.155718,0.404457,0.034186,0.122641,0.106202,0.135513,...,0.154916,0.140026,0.074025,0.124595,0.129024,0.234799,0.107556,0.110063,0.151536,0.217909
112,0.050911,0.100183,0.092031,0.030829,0.102738,0.357133,0.046313,0.069672,0.053732,0.083793,...,0.102501,0.093287,0.095450,0.107244,0.076464,0.202465,0.056499,0.059887,0.100537,0.203032
251,0.139979,0.025761,0.182786,0.091478,0.011814,0.280890,0.130248,0.021523,0.039909,0.024979,...,0.020492,0.055965,0.168921,0.133444,0.020396,0.173153,0.043518,0.045541,0.033182,0.209218
268,0.084744,0.116403,0.126260,0.038402,0.103961,0.309550,0.068234,0.081607,0.061477,0.104740,...,0.113693,0.054530,0.084223,0.043817,0.073674,0.136470,0.090115,0.049350,0.121359,0.136393
279,0.160350,0.154822,0.198501,0.116116,0.133328,0.247865,0.143455,0.129431,0.117527,0.150373,...,0.148630,0.073613,0.140867,0.061617,0.114358,0.058490,0.148595,0.102089,0.162247,0.082384
176,0.068456,0.156435,0.100039,0.054711,0.146648,0.344720,0.052955,0.120827,0.099498,0.143013,...,0.154795,0.098777,0.042348,0.040548,0.115692,0.155960,0.123247,0.090496,0.160375,0.131208
269,0.132169,0.020151,0.172275,0.091766,0.035625,0.308465,0.125720,0.025155,0.044353,0.005211,...,0.025443,0.080254,0.170218,0.148476,0.039367,0.200940,0.024922,0.057396,0.019278,0.231376
44,0.022830,0.169602,0.039505,0.066297,0.168275,0.398175,0.026255,0.136350,0.116638,0.153551,...,0.170897,0.138592,0.037449,0.101143,0.138531,0.216011,0.127109,0.115520,0.170747,0.189076
99,0.031998,0.141893,0.071214,0.034742,0.137836,0.364567,0.015323,0.107202,0.086443,0.126527,...,0.142196,0.104607,0.045444,0.075091,0.107289,0.186682,0.102135,0.083255,0.144086,0.168979
344,0.146514,0.093396,0.190055,0.092796,0.071045,0.246322,0.131335,0.073055,0.068139,0.091199,...,0.086736,0.019534,0.150869,0.087712,0.056841,0.105739,0.095943,0.055030,0.101130,0.144710
252,0.110724,0.151571,0.146046,0.076219,0.135533,0.300752,0.094000,0.118553,0.100035,0.141786,...,0.147630,0.076354,0.086795,0.008787,0.107772,0.109531,0.130003,0.086097,0.157424,0.096089
20,0.010055,0.160203,0.034120,0.064232,0.161542,0.402177,0.025618,0.128774,0.110582,0.143820,...,0.162355,0.139177,0.057275,0.113693,0.133207,0.226483,0.116383,0.112112,0.160492,0.204957
145,0.014624,0.140558,0.051400,0.051893,0.143219,0.390837,0.024873,0.110207,0.093167,0.124096,...,0.143087,0.126385,0.071545,0.114013,0.115980,0.222545,0.096383,0.096575,0.140504,0.208509
387,0.152908,0.008116,0.194434,0.107633,0.016271,0.284854,0.144714,0.035013,0.056211,0.020813,...,9999.000000,0.076052,0.185987,0.153758,0.040169,0.190532,0.048330,0.064586,0.016120,0.229283
178,0.129240,0.081714,0.173146,0.075094,0.061750,0.264638,0.114655,0.056534,0.049095,0.076787,...,0.076052,9999.000000,0.138621,0.083887,0.040921,0.122276,0.078037,0.035543,0.088909,0.153266
32,0.057463,0.186236,0.069878,0.078627,0.180251,0.386779,0.050736,0.151022,0.129801,0.171247,...,0.185987,0.138621,9999.000000,0.079406,0.149209,0.194369,0.147464,0.124229,0.188850,0.157442
213,0.106890,0.157396,0.140571,0.076479,0.142128,0.308887,0.090414,0.123749,0.104562,0.147013,...,0.153758,0.083887,0.079406,9999.000000,0.113702,0.115653,0.133861,0.091184,0.163004,0.096121
159,0.123275,0.043810,0.166819,0.072683,0.031125,0.285969,0.112396,0.016283,0.022822,0.036131,...,0.040169,0.040921,0.149209,0.113702,9999.000000,0.162401,0.040474,0.025258,0.049989,0.192602
273,0.218469,0.197776,0.255511,0.174416,0.174324,0.206681,0.201567,0.178474,0.170263,0.196860,...,0.190532,0.122276,0.194369,0.115653,0.162401,9999.000000,0.200231,0.155282,0.205749,0.079583
375,0.107404,0.044580,0.147360,0.069905,0.053449,0.323856,0.101560,0.024941,0.031311,0.028091,...,0.048330,0.078037,0.147464,0.133861,0.040474,0.200231,9999.000000,0.046753,0.044127,0.222069
304,0.102064,0.067055,0.146149,0.049223,0.056361,0.297338,0.089744,0.032567,0.015473,0.055831,...,0.064586,0.035543,0.124229,0.091184,0.025258,0.155282,0.046753,9999.000000,0.072097,0.175745
211,0.151445,0.008136,0.191390,0.110254,0.032107,0.299375,0.144902,0.039829,0.060906,0.017608,...,0.016120,0.088909,0.188850,0.163004,0.049989,0.205749,0.044127,0.072097,9999.000000,0.241990
348,0.199640,0.234944,0.226529,0.172204,0.214520,0.282542,0.184046,0.206348,0.190921,0.228630,...,0.229283,0.153266,0.157442,0.096121,0.192602,0.079583,0.222069,0.175745,0.241990,9999.000000

,17,369,207,335,151,146,11,81,127,154,...,112,364,217,188,36,263,332,99,338,119
17,9999.000000,0.136014,0.100650,0.115875,0.159631,0.059361,0.013499,0.036783,0.046068,0.136273,...,0.038937,0.028810,0.103782,0.054089,0.066391,0.376468,0.210130,0.018827,0.119811,0.067293
369,0.136014,9999.000000,0.135661,0.046196,0.024452,0.191462,0.128980,0.172796,0.181514,0.005100,...,0.102191,0.112831,0.032558,0.129800,0.078211,0.276606,0.325109,0.138341,0.031528,0.071329
207,0.100650,0.135661,9999.000000,0.090864,0.149466,0.149617,0.108813,0.119697,0.131209,0.132326,...,0.110055,0.109721,0.117696,0.046818,0.120265,0.297034,0.200900,0.083983,0.142802,0.110443
335,0.115875,0.046196,0.090864,9999.000000,0.058789,0.175025,0.113182,0.151223,0.161569,0.042225,...,0.092174,0.100597,0.042254,0.093681,0.078520,0.267082,0.285961,0.112193,0.063541,0.067244
151,0.159631,0.024452,0.149466,0.058789,9999.000000,0.215660,0.153032,0.196399,0.205354,0.023372,...,0.126499,0.137068,0.056828,0.149448,0.102652,0.257045,0.343812,0.160970,0.053151,0.095697
146,0.059361,0.191462,0.149617,0.175025,0.215660,9999.000000,0.062870,0.029974,0.018787,0.192358,...,0.089385,0.078637,0.158905,0.104116,0.115522,0.435025,0.193895,0.068626,0.170918,0.120318
11,0.013499,0.128980,0.108813,0.113182,0.153032,0.062870,9999.000000,0.045598,0.052908,0.129685,...,0.028201,0.017288,0.096451,0.063302,0.055797,0.377017,0.223197,0.031206,0.110495,0.058468
81,0.036783,0.172796,0.119697,0.151223,0.196399,0.029974,0.045598,9999.000000,0.011635,0.173047,...,0.073782,0.062884,0.140531,0.074563,0.101394,0.407310,0.184349,0.040577,0.155892,0.103545
127,0.046068,0.181514,0.131209,0.161569,0.205354,0.018787,0.052908,0.011635,9999.000000,0.181983,...,0.080929,0.069939,0.149075,0.086196,0.108239,0.418751,0.185053,0.051919,0.163308,0.111372
154,0.136273,0.005100,0.132326,0.042225,0.023372,0.192358,0.129685,0.173047,0.181983,9999.000000,...,0.103305,0.113807,0.033726,0.128019,0.080104,0.272526,0.323123,0.137904,0.035826,0.072616
116,0.070156,0.079680,0.127231,0.083513,0.103997,0.116725,0.058797,0.104237,0.110493,0.081967,...,0.031239,0.041622,0.049234,0.094649,0.006976,0.348735,0.278581,0.081154,0.054704,0.018258
312,0.124047,0.020065,0.138310,0.054899,0.042633,0.177158,0.115646,0.160570,0.168548,0.024276,...,0.087913,0.098836,0.022464,0.125495,0.062041,0.296663,0.320531,0.128749,0.011553,0.057178
398,0.079491,0.117289,0.025251,0.075292,0.133764,0.132839,0.086143,0.103540,0.115173,0.114532,...,0.085142,0.085434,0.095931,0.029219,0.095116,0.305609,0.210838,0.064732,0.120815,0.085501
19,0.048064,0.177336,0.143523,0.162537,0.201617,0.014962,0.049540,0.027621,0.020565,0.178371,...,0.075149,0.064567,0.144803,0.097081,0.100891,0.424531,0.204493,0.060279,0.156252,0.106062
390,0.097918,0.110025,0.025955,0.064938,0.123511,0.152855,0.103162,0.123809,0.135425,0.106575,...,0.097875,0.100011,0.093812,0.049828,0.102829,0.284926,0.225103,0.084380,0.118890,0.091989
235,0.094497,0.051721,0.130285,0.065968,0.075732,0.144796,0.084687,0.130213,0.137380,0.054548,...,0.056499,0.067476,0.024941,0.106824,0.029293,0.325105,0.298202,0.102135,0.026124,0.027817
29,0.017536,0.153506,0.109543,0.132910,0.177159,0.043400,0.026892,0.019315,0.028692,0.153799,...,0.054866,0.044100,0.121221,0.062909,0.082519,0.391627,0.198227,0.025984,0.136718,0.084303
286,0.171679,0.149882,0.075501,0.107126,0.151893,0.224287,0.177395,0.194539,0.206133,0.145046,...,0.170828,0.173850,0.148147,0.120244,0.171284,0.226096,0.252057,0.156899,0.170652,0.159624
7,0.030990,0.109739,0.108584,0.097618,0.133966,0.081724,0.020057,0.065627,0.072857,0.110700,...,0.008157,0.003118,0.077184,0.066950,0.035803,0.363719,0.240450,0.043879,0.090468,0.038706
149,0.140600,0.007037,0.135360,0.044836,0.019043,0.196673,0.134009,0.177372,0.186312,0.004329,...,0.107596,0.118112,0.037981,0.131938,0.084247,0.269571,0.326927,0.142169,0.038558,0.076879
239,0.095780,0.137839,0.006470,0.093704,0.152465,0.143741,0.104409,0.113791,0.125265,0.134681,...,0.107031,0.106132,0.118553,0.041724,0.118584,0.303492,0.196066,0.078736,0.143592,0.109142
1,0.022083,0.144920,0.085381,0.118161,0.167470,0.065261,0.035323,0.036241,0.047810,0.144440,...,0.056730,0.048204,0.113846,0.039033,0.082626,0.371148,0.191169,0.006670,0.132768,0.080927
322,0.121746,0.091678,0.055586,0.045993,0.099935,0.179517,0.124195,0.151593,0.163038,0.087338,...,0.112090,0.117051,0.085074,0.080123,0.108833,0.255718,0.256482,0.111142,0.108487,0.097025
175,0.139802,0.033179,0.160186,0.075731,0.046516,0.189776,0.130154,0.175671,0.182812,0.038277,...,0.101964,0.112936,0.043377,0.145982,0.074596,0.303432,0.340369,0.146390,0.020302,0.072611
13,0.032705,0.155125,0.133090,0.142309,0.179468,0.037405,0.029456,0.034403,0.034990,0.156293,...,0.052989,0.042707,0.122641,0.086332,0.078337,0.406457,0.218636,0.049505,0.133677,0.083798
42,0.017922,0.118133,0.096526,0.099577,0.141822,0.075584,0.014460,0.054672,0.063605,0.118455,...,0.023255,0.015760,0.085866,0.052543,0.049657,0.362669,0.224605,0.027484,0.102124,0.049599
273,0.202093,0.177741,0.103564,0.136821,0.177177,0.253175,0.208328,0.223261,0.234768,0.172773,...,0.202465,0.205293,0.178474,0.149660,0.202950,0.210059,0.262736,0.186682,0.200270,0.191262
330,0.084700,0.057572,0.085479,0.032395,0.078473,0.143414,0.081105,0.120791,0.130711,0.056123,...,0.059887,0.068203,0.032567,0.072328,0.049345,0.299072,0.267740,0.083255,0.057509,0.037519
251,0.124177,0.012176,0.125328,0.038042,0.035577,0.180105,0.117455,0.160959,0.169816,0.012262,...,0.091045,0.101545,0.021523,0.117844,0.068083,0.282052,0.313219,0.126218,0.028836,0.060383
360,0.167659,0.144144,0.072793,0.101381,0.146308,0.220875,0.173092,0.191218,0.202831,0.139313,...,0.165973,0.169196,0.142450,0.116763,0.165988,0.226863,0.253184,0.153191,0.164911,0.154300
112,0.038937,0.102191,0.110055,0.092174,0.126499,0.089385,0.028201,0.073782,0.080929,0.103305,...,9999.000000,0.010990,0.069672,0.070502,0.027653,0.358901,0.247820,0.050700,0.082379,0.030934
364,0.028810,0.112831,0.109721,0.100597,0.137068,0.078637,0.017288,0.062884,0.069939,0.113807,...,0.010990,9999.000000,0.080279,0.067358,0.038511,0.366561,0.238661,0.042654,0.093369,0.041748
217,0.103782,0.032558,0.117696,0.042254,0.056828,0.158905,0.096451,0.140531,0.149075,0.033726,...,0.069672,0.080279,9999.000000,0.103044,0.046694,0.300677,0.298078,0.107202,0.025118,0.038898
188,0.054089,0.129800,0.046818,0.093681,0.149448,0.104116,0.063302,0.074563,0.086196,0.128019,...,0.070502,0.067358,0.103044,9999.000000,0.088148,0.334669,0.195420,0.037183,0.126229,0.081298
36,0.066391,0.078211,0.120265,0.078520,0.102652,0.115522,0.055797,0.101394,0.108239,0.080104,...,0.027653,0.038511,0.046694,0.088148,9999.000000,0.344600,0.273600,0.076226,0.055404,0.011857
263,0.376468,0.276606,0.297034,0.267082,0.257045,0.435025,0.377017,0.407310,0.418751,0.272526,...,0.358901,0.366561,0.300677,0.334669,0.344600,9999.000000,0.472549,0.366841,0.308124,0.333862
332,0.210130,0.325109,0.200900,0.285961,0.343812,0.193895,0.223197,0.184349,0.185053,0.323123,...,0.247820,0.238661,0.298078,0.195420,0.273600,0.472549,9999.000000,0.197434,0.320238,0.270650
99,0.018827,0.138341,0.083983,0.112193,0.160970,0.068626,0.031206,0.040577,0.051919,0.137904,...,0.050700,0.042654,0.107202,0.037183,0.076226,0.366841,0.197434,9999.000000,0.126106,0.074318
338,0.119811,0.031528,0.142802,0.063541,0.053151,0.170918,0.110495,0.155892,0.163308,0.035826,...,0.082379,0.093369,0.025118,0.126229,0.055404,0.308124,0.320238,0.126106,9999.000000,0.052530
119,0.067293,0.071329,0.110443,0.067244,0.095697,0.120318,0.058468,0.103545,0.111372,0.072616,...,0.030934,0.041748,0.038898,0.081298,0.011857,0.333862,0.270650,0.074318,0.052530,9999.000000

,224,131,70,179,105,420,61,273,212,13,...,240,425,15,252,389,71,397,182,63,326
224,9999.000000,0.059430,0.089317,0.063031,0.088770,0.054469,0.133145,0.121494,0.118209,0.113390,...,0.053797,0.087047,0.105441,0.025107,0.085732,0.116010,0.053355,0.049684,0.123312,0.127574
131,0.059430,9999.000000,0.060064,0.086553,0.072001,0.053135,0.089295,0.177370,0.175258,0.066457,...,0.110866,0.141104,0.076019,0.081819,0.028276,0.065355,0.052484,0.088888,0.064243,0.100959
70,0.089317,0.060064,9999.000000,0.066452,0.018507,0.038516,0.047043,0.208371,0.203792,0.035079,...,0.141382,0.175667,0.016927,0.099272,0.050657,0.043162,0.039331,0.134847,0.089482,0.158955
179,0.063031,0.086553,0.066452,9999.000000,0.052990,0.035779,0.112051,0.158264,0.151813,0.101212,...,0.097876,0.131664,0.075393,0.054158,0.098675,0.108438,0.035961,0.111243,0.142775,0.180738
105,0.088770,0.072001,0.018507,0.052990,9999.000000,0.034354,0.059384,0.203468,0.198168,0.052152,...,0.137900,0.172554,0.022414,0.094014,0.067523,0.060856,0.035451,0.136988,0.107735,0.172675
420,0.054469,0.053135,0.038516,0.035779,0.034354,9999.000000,0.085403,0.170449,0.165604,0.070179,...,0.104090,0.138663,0.052813,0.061017,0.062896,0.076086,0.001142,0.103165,0.106996,0.151943
61,0.133145,0.089295,0.047043,0.112051,0.059384,0.085403,9999.000000,0.253912,0.249744,0.023091,...,0.186423,0.220180,0.037206,0.145594,0.065695,0.027947,0.086157,0.174862,0.082881,0.173762
273,0.121494,0.177370,0.208371,0.158264,0.203468,0.170449,0.253912,9999.000000,0.009629,0.234799,...,0.067705,0.036963,0.223261,0.109531,0.205293,0.237483,0.169503,0.094832,0.237119,0.197776
212,0.118209,0.175258,0.203792,0.151813,0.198168,0.165604,0.249744,0.009629,9999.000000,0.231114,...,0.064602,0.037497,0.218353,0.104587,0.202928,0.234149,0.164691,0.095391,0.236040,0.200710
13,0.113390,0.066457,0.035079,0.101212,0.052152,0.070179,0.023091,0.234799,0.231114,9999.000000,...,0.167105,0.200293,0.034403,0.128045,0.042707,0.009600,0.070726,0.153120,0.065713,0.152019
410,0.077781,0.049025,0.108834,0.127232,0.120937,0.098374,0.131788,0.171175,0.171757,0.108833,...,0.113152,0.134481,0.124317,0.102742,0.066126,0.104763,0.097499,0.076410,0.073817,0.053702
346,0.106617,0.074681,0.132414,0.156292,0.146217,0.126336,0.148364,0.190521,0.192243,0.126276,...,0.137498,0.154755,0.146757,0.131371,0.084897,0.120470,0.125523,0.097719,0.076672,0.026542
198,0.118862,0.085503,0.142061,0.168170,0.156459,0.137718,0.155233,0.200270,0.202338,0.133677,...,0.148821,0.164911,0.155892,0.143592,0.093369,0.127288,0.136933,0.108487,0.079650,0.018787
147,0.127667,0.082785,0.043198,0.109114,0.057050,0.081113,0.006699,0.248700,0.244683,0.016440,...,0.181119,0.214712,0.035538,0.140793,0.058998,0.021472,0.081814,0.168773,0.077185,0.167230
183,0.051207,0.062796,0.117551,0.112273,0.124059,0.093367,0.151969,0.129398,0.129954,0.129231,...,0.072850,0.092669,0.134428,0.072890,0.089459,0.127966,0.092264,0.034597,0.111003,0.080468
244,0.052726,0.048569,0.105908,0.109101,0.114186,0.085786,0.137813,0.144317,0.144400,0.114882,...,0.084870,0.107415,0.122590,0.076907,0.074196,0.113080,0.084743,0.049628,0.094915,0.074849
196,0.036639,0.042462,0.052778,0.045111,0.052840,0.019538,0.097648,0.156268,0.152155,0.079305,...,0.088882,0.122978,0.068802,0.048820,0.060522,0.083325,0.018406,0.084149,0.103461,0.136244
41,0.116532,0.058455,0.091221,0.140455,0.109033,0.104818,0.089870,0.228310,0.227502,0.071021,...,0.164609,0.191368,0.100504,0.139939,0.042627,0.062806,0.104544,0.134499,0.010878,0.088149
222,0.041996,0.100874,0.127490,0.082822,0.123337,0.089788,0.173054,0.080912,0.076809,0.154311,...,0.015079,0.049518,0.142567,0.029657,0.127666,0.157482,0.088812,0.045696,0.163983,0.151454
62,0.085936,0.061843,0.007154,0.059568,0.012215,0.033398,0.053155,0.203804,0.199002,0.042208,...,0.137180,0.171635,0.019588,0.094414,0.055447,0.050312,0.034315,0.132589,0.095560,0.161891
135,0.128232,0.082450,0.044644,0.110761,0.058912,0.082310,0.007956,0.249393,0.245457,0.015994,...,0.181771,0.215260,0.037600,0.141721,0.058163,0.020009,0.082987,0.168879,0.075198,0.165823
73,0.102593,0.052004,0.036549,0.098771,0.055038,0.065012,0.038498,0.224019,0.220783,0.015520,...,0.156367,0.188878,0.042516,0.119289,0.027205,0.013647,0.065331,0.139899,0.054611,0.136884
31,0.114621,0.088559,0.028733,0.078024,0.026892,0.060679,0.040386,0.230356,0.225055,0.044071,...,0.164631,0.199258,0.012829,0.120881,0.075617,0.053652,0.061729,0.161850,0.108603,0.186077
146,0.134623,0.098485,0.045309,0.103896,0.051380,0.082736,0.020459,0.253175,0.248316,0.037405,...,0.186492,0.220875,0.029974,0.143741,0.078637,0.045125,0.083673,0.179517,0.101739,0.189152
309,0.072137,0.130816,0.156162,0.105504,0.150577,0.117935,0.202267,0.053057,0.047673,0.184014,...,0.021984,0.030591,0.170681,0.056921,0.157775,0.187414,0.117025,0.063020,0.193483,0.172763
163,0.061291,0.048872,0.107998,0.115921,0.117543,0.090782,0.137223,0.152073,0.152451,0.114156,...,0.093678,0.115275,0.124407,0.085725,0.072389,0.111608,0.089783,0.057242,0.089105,0.066436
407,0.300865,0.338171,0.388275,0.354612,0.389609,0.355334,0.426935,0.206681,0.215806,0.404457,...,0.256783,0.223895,0.405007,0.300752,0.364710,0.403406,0.354219,0.253427,0.378000,0.292533
172,0.115313,0.087796,0.146082,0.167640,0.159597,0.138698,0.162245,0.190977,0.193381,0.140208,...,0.141688,0.156081,0.160570,0.139586,0.098836,0.134334,0.137847,0.100608,0.089180,0.013247
132,0.089461,0.056531,0.005544,0.070451,0.024010,0.040661,0.044894,0.209396,0.205040,0.030761,...,0.142128,0.176212,0.019499,0.100736,0.045501,0.038370,0.041365,0.133930,0.083944,0.154529
236,0.030760,0.063952,0.069574,0.032598,0.064036,0.031114,0.116268,0.139579,0.134568,0.099802,...,0.073984,0.108656,0.083786,0.030048,0.083557,0.104713,0.030255,0.079979,0.126285,0.150758
240,0.053797,0.110866,0.141382,0.097876,0.137900,0.104090,0.186423,0.067705,0.064602,0.167105,...,9999.000000,0.034673,0.156747,0.044628,0.138378,0.169805,0.103085,0.042052,0.172662,0.151407
425,0.087047,0.141104,0.175667,0.131664,0.172554,0.138663,0.220180,0.036963,0.037497,0.200293,...,0.034673,9999.000000,0.191218,0.079175,0.169196,0.202444,0.137646,0.058072,0.200230,0.163717
15,0.105441,0.076019,0.016927,0.075393,0.022414,0.052813,0.037206,0.223261,0.218353,0.034403,...,0.156747,0.191218,9999.000000,0.113791,0.062884,0.043921,0.053767,0.151593,0.097125,0.173249
252,0.025107,0.081819,0.099272,0.054158,0.094014,0.061017,0.145594,0.109531,0.104587,0.128045,...,0.044628,0.079175,0.113791,9999.000000,0.106132,0.132126,0.060104,0.060561,0.146060,0.151571
389,0.085732,0.028276,0.050657,0.098675,0.067523,0.062896,0.065695,0.205293,0.202928,0.042707,...,0.138378,0.169196,0.062884,0.106132,9999.000000,0.039245,0.062733,0.117051,0.044102,0.111153
71,0.116010,0.065355,0.043162,0.108438,0.060856,0.076086,0.027947,0.237483,0.234149,0.009600,...,0.169805,0.202444,0.043921,0.132126,0.039245,9999.000000,0.076525,0.153507,0.056863,0.145816
397,0.053355,0.052484,0.039331,0.035961,0.035451,0.001142,0.086157,0.169503,0.164691,0.070726,...,0.103085,0.137646,0.053767,0.060104,0.062733,0.076525,9999.000000,0.102027,0.106835,0.151090
182,0.049684,0.088888,0.134847,0.111243,0.136988,0.103165,0.174862,0.094832,0.095391,0.153120,...,0.042052,0.058072,0.151593,0.060561,0.117051,0.153507,0.102027,9999.000000,0.143823,0.109770
63,0.123312,0.064243,0.089482,0.142775,0.107735,0.106996,0.082881,0.237119,0.236040,0.065713,...,0.172662,0.200230,0.097125,0.146060,0.044102,0.056863,0.106835,0.143823,9999.000000,0.098306
326,0.127574,0.100959,0.158955,0.180738,0.172675,0.151943,0.173762,0.197776,0.200710,0.152019,...,0.151407,0.163717,0.173249,0.151571,0.111153,0.145816,0.151090,0.109770,0.098306,9999.000000

,367,285,24,59,134,421,344,335,51,49,...,96,171,119,33,337,313,140,420,248,40
367,9999.000000,0.215571,0.174785,0.161293,0.207192,0.125832,0.102663,0.132113,0.215643,0.181380,...,0.218625,0.112543,0.176378,0.155002,0.173705,0.119334,0.219842,0.141323,0.188570,0.205492
285,0.215571,9999.000000,0.133831,0.141063,0.110287,0.157215,0.115868,0.084818,0.122793,0.134756,...,0.128095,0.148300,0.061470,0.182046,0.053275,0.101203,0.141983,0.149580,0.028051,0.164551
24,0.174785,0.133831,9999.000000,0.015399,0.042263,0.052955,0.131335,0.120371,0.044555,0.006612,...,0.045942,0.062383,0.074184,0.054318,0.142031,0.087549,0.045068,0.036526,0.126414,0.039665
59,0.161293,0.141063,0.015399,9999.000000,0.057189,0.037808,0.125181,0.117762,0.059951,0.021307,...,0.061227,0.048788,0.079953,0.042149,0.143695,0.082496,0.059279,0.021295,0.130792,0.047035
134,0.207192,0.110287,0.042263,0.057189,9999.000000,0.092926,0.144820,0.125307,0.013718,0.038194,...,0.019184,0.098241,0.062093,0.095671,0.133801,0.101984,0.031965,0.077204,0.111594,0.056643
421,0.125832,0.157215,0.052955,0.037808,0.092926,9999.000000,0.109513,0.111766,0.097307,0.059097,...,0.098896,0.018351,0.096851,0.037792,0.146648,0.073861,0.096899,0.016522,0.140805,0.079662
344,0.102663,0.115868,0.131335,0.125181,0.144820,0.109513,9999.000000,0.031086,0.157243,0.137014,...,0.161968,0.091531,0.092526,0.147125,0.071045,0.044072,0.169454,0.115489,0.088007,0.170741
335,0.132113,0.084818,0.120371,0.117762,0.125307,0.111766,0.031086,9999.000000,0.138550,0.125147,...,0.143675,0.095715,0.067244,0.147375,0.043354,0.037912,0.153069,0.113298,0.057050,0.159883
51,0.215643,0.122793,0.044555,0.059951,0.013718,0.097307,0.157243,0.138550,9999.000000,0.039000,...,0.005497,0.104820,0.075809,0.094645,0.147502,0.113950,0.019297,0.080999,0.125080,0.048164
49,0.181380,0.134756,0.006612,0.021307,0.038194,0.059097,0.137014,0.125147,0.039000,9999.000000,...,0.039977,0.068947,0.076185,0.057498,0.145317,0.093090,0.038493,0.042597,0.128674,0.034778
191,0.143339,0.075840,0.089744,0.089035,0.092987,0.090496,0.055030,0.032395,0.106176,0.094075,...,0.111287,0.077484,0.037519,0.122935,0.056361,0.025420,0.120738,0.088307,0.053092,0.128842
28,0.179528,0.083766,0.050066,0.058243,0.038590,0.082365,0.107595,0.086784,0.052044,0.051283,...,0.057326,0.080252,0.025675,0.100185,0.097311,0.066365,0.068119,0.070677,0.078043,0.083267
268,0.114333,0.122656,0.068234,0.059389,0.093705,0.044530,0.067113,0.067296,0.103430,0.074561,...,0.107093,0.028815,0.068294,0.081045,0.103961,0.029461,0.111069,0.048414,0.102142,0.106165
34,0.184659,0.083856,0.050377,0.059758,0.034427,0.085743,0.112627,0.091327,0.048048,0.050913,...,0.053419,0.084430,0.028245,0.101882,0.100225,0.071594,0.064786,0.073431,0.079890,0.081708
274,0.142902,0.072992,0.102982,0.102095,0.105002,0.101699,0.047856,0.020716,0.118366,0.107298,...,0.123561,0.087601,0.046578,0.135152,0.045112,0.031176,0.133398,0.100557,0.047377,0.142059
174,0.100795,0.166119,0.077348,0.062586,0.115525,0.025324,0.098827,0.108008,0.121116,0.083695,...,0.123088,0.018984,0.108794,0.056901,0.147296,0.071804,0.121859,0.041552,0.146303,0.104836
31,0.199709,0.173843,0.043573,0.046629,0.068093,0.074395,0.171808,0.163274,0.060693,0.040311,...,0.057750,0.090467,0.116372,0.049212,0.185488,0.128919,0.045795,0.060679,0.168903,0.013280
359,0.017548,0.214189,0.184559,0.171728,0.214743,0.137618,0.099002,0.129611,0.223957,0.191171,...,0.227252,0.123032,0.179396,0.168670,0.169524,0.121930,0.229425,0.152490,0.186630,0.216984
77,0.124198,0.153691,0.052914,0.038091,0.091997,0.004194,0.105468,0.107572,0.096942,0.059222,...,0.098754,0.014679,0.093572,0.041722,0.142558,0.069668,0.097367,0.017200,0.136973,0.081410
124,0.145854,0.154245,0.035394,0.020065,0.077199,0.020055,0.122203,0.119865,0.079861,0.040936,...,0.080887,0.035592,0.092798,0.028643,0.150635,0.082519,0.077712,0.006722,0.141050,0.059644
82,0.147563,0.112749,0.037345,0.034226,0.059700,0.045645,0.094065,0.083879,0.069146,0.042951,...,0.072840,0.042656,0.051620,0.070516,0.109963,0.050206,0.077430,0.036907,0.099067,0.076953
416,0.160588,0.062282,0.135303,0.135744,0.130890,0.136144,0.057970,0.030134,0.144595,0.139052,...,0.150017,0.121540,0.068847,0.169706,0.013298,0.063752,0.161317,0.135096,0.034875,0.173528
47,0.140946,0.133118,0.034077,0.022908,0.069197,0.026313,0.103115,0.098215,0.075576,0.040686,...,0.078074,0.029252,0.071973,0.051135,0.128126,0.061525,0.078979,0.016765,0.118871,0.069925
371,0.037231,0.186147,0.167707,0.156193,0.194284,0.125378,0.070537,0.101381,0.204458,0.174257,...,0.208173,0.108808,0.154300,0.159824,0.140801,0.097144,0.211768,0.138663,0.158430,0.202748
239,0.080814,0.161559,0.094000,0.080528,0.128108,0.046528,0.079330,0.093704,0.135625,0.100587,...,0.138328,0.031744,0.109142,0.080884,0.135533,0.061499,0.139067,0.061017,0.138944,0.125524
79,0.170126,0.162494,0.029643,0.022616,0.069221,0.044568,0.145012,0.139562,0.067578,0.031438,...,0.066999,0.060753,0.101845,0.027100,0.166304,0.103443,0.060118,0.031165,0.153170,0.036050
212,0.028198,0.223596,0.197582,0.184810,0.227404,0.150729,0.107849,0.138797,0.236758,0.204193,...,0.240105,0.136130,0.190809,0.181606,0.177529,0.133387,0.242412,0.165604,0.195829,0.230100
123,0.160585,0.142080,0.016527,0.001233,0.058393,0.036830,0.125280,0.118161,0.061065,0.022339,...,0.062291,0.048122,0.080927,0.040986,0.144387,0.082729,0.060168,0.020309,0.131659,0.047318
164,0.143339,0.075840,0.089744,0.089035,0.092987,0.090496,0.055030,0.032395,0.106176,0.094075,...,0.111287,0.077484,0.037519,0.122935,0.056361,0.025420,0.120738,0.088307,0.053092,0.128842
284,0.113657,0.190251,0.083717,0.068392,0.125411,0.034681,0.127135,0.136324,0.128092,0.089097,...,0.128882,0.042598,0.130754,0.043426,0.174853,0.099604,0.124464,0.048485,0.172123,0.101010
96,0.218625,0.128095,0.045942,0.061227,0.019184,0.098896,0.161968,0.143675,0.005497,0.039977,...,9999.000000,0.107239,0.081256,0.094094,0.152983,0.118506,0.014356,0.082460,0.130572,0.044888
171,0.112543,0.148300,0.062383,0.048788,0.098241,0.018351,0.091531,0.095715,0.104820,0.068947,...,0.107239,9999.000000,0.090128,0.056113,0.132705,0.058125,0.107440,0.029867,0.129561,0.094251
119,0.176378,0.061470,0.074184,0.079953,0.062093,0.096851,0.092526,0.067244,0.075809,0.076185,...,0.081256,0.090128,9999.000000,0.120594,0.071985,0.057466,0.092994,0.088257,0.052543,0.108860
33,0.155002,0.182046,0.054318,0.042149,0.095671,0.037792,0.147125,0.147375,0.094645,0.057498,...,0.094094,0.056113,0.120594,9999.000000,0.179190,0.109640,0.086763,0.034629,0.169582,0.059441
337,0.173705,0.053275,0.142031,0.143695,0.133801,0.146648,0.071045,0.043354,0.147502,0.145317,...,0.152983,0.132705,0.071985,0.179190,9999.000000,0.075514,0.164970,0.144574,0.028238,0.179355
313,0.119334,0.101203,0.087549,0.082496,0.101984,0.073861,0.044072,0.037912,0.113950,0.093090,...,0.118506,0.058125,0.057466,0.109640,0.075514,9999.000000,0.125521,0.075872,0.077540,0.127119
140,0.219842,0.141983,0.045068,0.059279,0.031965,0.096899,0.169454,0.153069,0.019297,0.038493,...,0.014356,0.107440,0.092994,0.086763,0.164970,0.125521,9999.000000,0.080404,0.143420,0.032557
420,0.141323,0.149580,0.036526,0.021295,0.077204,0.016522,0.115489,0.113298,0.080999,0.042597,...,0.082460,0.029867,0.088257,0.034629,0.144574,0.075872,0.080404,9999.000000,0.135635,0.064519
248,0.188570,0.028051,0.126414,0.130792,0.111594,0.140805,0.088007,0.057050,0.125080,0.128674,...,0.130572,0.129561,0.052543,0.169582,0.028238,0.077540,0.143420,0.135635,9999.000000,0.161310
40,0.205492,0.164551,0.039665,0.047035,0.056643,0.079662,0.170741,0.159883,0.048164,0.034778,...,0.044888,0.094251,0.108860,0.059441,0.179355,0.127119,0.032557,0.064519,0.161310,9999.000000

,114,375,130,391,263,257,347,184,335,318,...,207,161,378,254,302,417,201,422,413,239
114,9999.000000,0.122615,0.080407,0.160893,0.425616,0.086697,0.151023,0.172966,0.160955,0.159121,...,0.151023,0.094454,0.120765,0.233450,0.117079,0.176665,0.070467,0.097572,0.253323,0.145774
375,0.122615,9999.000000,0.047150,0.043518,0.325105,0.113425,0.130285,0.093161,0.065968,0.078037,...,0.130285,0.128431,0.052878,0.184522,0.092768,0.130215,0.125008,0.136009,0.200231,0.130003
130,0.080407,0.047150,9999.000000,0.080819,0.349892,0.071836,0.108040,0.100471,0.082897,0.085099,...,0.108040,0.087047,0.046059,0.178928,0.066628,0.120389,0.079499,0.094384,0.197235,0.105563
391,0.160893,0.043518,0.080819,9999.000000,0.282052,0.131075,0.125328,0.066956,0.038042,0.055965,...,0.125328,0.144547,0.056880,0.160195,0.097524,0.113685,0.148159,0.151924,0.173153,0.127216
263,0.425616,0.325105,0.349892,0.282052,9999.000000,0.356059,0.297034,0.252728,0.267082,0.266561,...,0.297034,0.360117,0.305444,0.226155,0.314413,0.262670,0.379519,0.363869,0.210059,0.303492
257,0.086697,0.113425,0.071836,0.131075,0.356059,9999.000000,0.065909,0.109134,0.110987,0.100231,...,0.065909,0.015235,0.074555,0.149358,0.043075,0.095911,0.023460,0.022704,0.169445,0.060138
347,0.151023,0.130285,0.108040,0.125328,0.297034,0.065909,9999.000000,0.071961,0.090864,0.073134,...,0.100000,0.065102,0.077475,0.083467,0.041416,0.034761,0.087904,0.067606,0.103564,0.006470
184,0.172966,0.093161,0.100471,0.066956,0.252728,0.109134,0.071961,9999.000000,0.029316,0.015809,...,0.071961,0.117488,0.054449,0.093590,0.066095,0.049525,0.131844,0.123308,0.107770,0.076293
335,0.160955,0.065968,0.082897,0.038042,0.267082,0.110987,0.090864,0.029316,9999.000000,0.018398,...,0.090864,0.122278,0.040871,0.122906,0.070954,0.075888,0.131602,0.129072,0.136821,0.093704
318,0.159121,0.078037,0.085099,0.055965,0.266561,0.100231,0.073134,0.015809,0.018398,9999.000000,...,0.073134,0.110100,0.039282,0.107172,0.058075,0.057721,0.122149,0.116465,0.122276,0.076354
339,0.130337,0.101113,0.079072,0.100362,0.303480,0.052620,0.029687,0.059296,0.069710,0.054333,...,0.029687,0.058760,0.048653,0.104099,0.013664,0.046344,0.076066,0.064199,0.123631,0.028891
281,0.102863,0.123247,0.084809,0.136033,0.347307,0.016762,0.052731,0.105477,0.111766,0.098777,...,0.052731,0.012811,0.079213,0.135860,0.040893,0.085146,0.035482,0.017831,0.155960,0.046528
333,0.118770,0.126204,0.092296,0.133552,0.332553,0.032073,0.036503,0.095416,0.105614,0.090836,...,0.036503,0.028634,0.077888,0.119296,0.036029,0.069923,0.052140,0.031350,0.139389,0.030166
186,0.167189,0.044580,0.090341,0.025761,0.293369,0.149630,0.150037,0.092511,0.063781,0.081714,...,0.150037,0.163851,0.077767,0.185385,0.119754,0.139430,0.164521,0.171376,0.197776,0.151571
240,0.185681,0.142712,0.132023,0.125647,0.259612,0.102883,0.038203,0.060449,0.087710,0.069722,...,0.038203,0.103215,0.091957,0.048076,0.069676,0.012499,0.125510,0.105803,0.067705,0.044628
172,0.155863,0.033652,0.077934,0.018108,0.296663,0.136386,0.138310,0.084161,0.054899,0.072079,...,0.138310,0.150625,0.064849,0.177674,0.106976,0.129508,0.151341,0.158156,0.190977,0.139586
154,0.173115,0.054548,0.093080,0.012262,0.272526,0.142039,0.132326,0.069313,0.042225,0.060622,...,0.132326,0.155212,0.067530,0.160981,0.107016,0.117808,0.159655,0.162512,0.172773,0.134681
65,0.075817,0.050810,0.032694,0.093505,0.372408,0.098948,0.140664,0.128392,0.106656,0.112623,...,0.140664,0.113671,0.075373,0.210804,0.099249,0.152510,0.100881,0.120518,0.228771,0.138045
131,0.085523,0.062534,0.024078,0.085682,0.340127,0.050994,0.084593,0.087640,0.076572,0.073598,...,0.084593,0.066118,0.035748,0.158497,0.043260,0.099769,0.063571,0.073665,0.177370,0.081819
373,0.153373,0.126966,0.106951,0.120271,0.291432,0.069369,0.006613,0.065581,0.085231,0.067310,...,0.006613,0.069737,0.074089,0.080270,0.040731,0.028823,0.091881,0.072702,0.100291,0.012467
219,0.236419,0.190621,0.183744,0.167057,0.229039,0.151598,0.085741,0.100302,0.129611,0.113596,...,0.085741,0.149336,0.142109,0.007479,0.121523,0.063355,0.173089,0.150427,0.019754,0.091474
294,0.173115,0.054548,0.093080,0.012262,0.272526,0.142039,0.132326,0.069313,0.042225,0.060622,...,0.132326,0.155212,0.067530,0.160981,0.107016,0.117808,0.159655,0.162512,0.172773,0.134681
396,0.168470,0.124205,0.112738,0.109901,0.269690,0.088066,0.029053,0.048107,0.072577,0.054196,...,0.029053,0.090540,0.072876,0.066696,0.051599,0.008201,0.111273,0.094186,0.085853,0.035124
1,0.066377,0.108742,0.063274,0.132788,0.371148,0.020347,0.085381,0.120900,0.118161,0.110063,...,0.085381,0.030761,0.078677,0.168593,0.056757,0.113687,0.016287,0.036292,0.188629,0.079848
383,0.253664,0.201688,0.198188,0.174945,0.211615,0.169533,0.103627,0.109382,0.138488,0.123783,...,0.103627,0.167772,0.155154,0.020226,0.137795,0.078448,0.191324,0.169051,0.002455,0.109535
86,0.075204,0.079198,0.035929,0.103008,0.351458,0.035909,0.082194,0.098850,0.091410,0.086051,...,0.082194,0.051118,0.050766,0.161115,0.043366,0.103021,0.046158,0.058471,0.180597,0.078255
244,0.133797,0.057845,0.058658,0.051456,0.292365,0.083445,0.075814,0.041916,0.028656,0.026441,...,0.075814,0.095612,0.013083,0.127667,0.046303,0.072375,0.103351,0.102703,0.144317,0.076907
35,0.021330,0.139583,0.094945,0.175709,0.433337,0.084451,0.150327,0.180888,0.171926,0.168013,...,0.150327,0.088907,0.131117,0.233711,0.120574,0.178801,0.064215,0.090441,0.253775,0.144588
195,0.160955,0.065968,0.082897,0.038042,0.267082,0.110987,0.090864,0.029316,0.100000,0.018398,...,0.090864,0.122278,0.040871,0.122906,0.070954,0.075888,0.131602,0.129072,0.136821,0.093704
324,0.172966,0.093161,0.100471,0.066956,0.252728,0.109134,0.071961,0.100000,0.029316,0.015809,...,0.071961,0.117488,0.054449,0.093590,0.066095,0.049525,0.131844,0.123308,0.107770,0.076293
207,0.151023,0.130285,0.108040,0.125328,0.297034,0.065909,0.100000,0.071961,0.090864,0.073134,...,9999.000000,0.065102,0.077475,0.083467,0.041416,0.034761,0.087904,0.067606,0.103564,0.006470
161,0.094454,0.128431,0.087047,0.144547,0.360117,0.015235,0.065102,0.117488,0.122278,0.110100,...,0.065102,9999.000000,0.087717,0.147827,0.052027,0.097895,0.024698,0.007589,0.167904,0.058795
378,0.120765,0.052878,0.046059,0.056880,0.305444,0.074555,0.077475,0.054449,0.040871,0.039282,...,0.077475,0.087717,9999.000000,0.136646,0.042242,0.079620,0.093105,0.095064,0.153996,0.077475
254,0.233450,0.184522,0.178928,0.160195,0.226155,0.149358,0.083467,0.093590,0.122906,0.107172,...,0.083467,0.147827,0.136646,9999.000000,0.117750,0.058732,0.171247,0.149287,0.020106,0.089426
302,0.117079,0.092768,0.066628,0.097524,0.314413,0.043075,0.041416,0.066095,0.070954,0.058075,...,0.041416,0.052027,0.042242,0.117750,9999.000000,0.059797,0.066070,0.058447,0.137247,0.039146
417,0.176665,0.130215,0.120389,0.113685,0.262670,0.095911,0.034761,0.049525,0.075888,0.057721,...,0.034761,0.097895,0.079620,0.058732,0.059797,9999.000000,0.119026,0.101269,0.077747,0.041117
201,0.070467,0.125008,0.079499,0.148159,0.379519,0.023460,0.087904,0.131844,0.131602,0.122149,...,0.087904,0.024698,0.093105,0.171247,0.066070,0.119026,9999.000000,0.027105,0.191352,0.081831
422,0.097572,0.136009,0.094384,0.151924,0.363869,0.022704,0.067606,0.123308,0.129072,0.116465,...,0.067606,0.007589,0.095064,0.149287,0.058447,0.101269,0.027105,9999.000000,0.169292,0.061176
413,0.253323,0.200231,0.197235,0.173153,0.210059,0.169445,0.103564,0.107770,0.136821,0.122276,...,0.103564,0.167904,0.153996,0.020106,0.137247,0.077747,0.191352,0.169292,9999.000000,0.109531
239,0.145774,0.130003,0.105563,0.127216,0.303492,0.060138,0.006470,0.076293,0.093704,0.076354,...,0.006470,0.058795,0.077475,0.089426,0.039146,0.041117,0.081831,0.061176,0.109531,9999.000000

,410,260,163,231,28,377,99,278,391,167,...,350,132,384,359,133,358,386,362,275,131
410,9999.000000,0.092944,0.019514,0.166947,0.050624,0.021020,0.089749,0.134041,0.036705,0.106025,...,0.090180,0.104975,0.028319,0.161167,0.050764,0.201255,0.102871,0.142777,0.120706,0.049025
260,0.092944,9999.000000,0.074051,0.087203,0.107520,0.110667,0.093203,0.085378,0.111475,0.082014,...,0.069583,0.116223,0.064935,0.078365,0.135278,0.108312,0.020440,0.062678,0.041017,0.084936
163,0.019514,0.074051,9999.000000,0.147672,0.058803,0.036925,0.086505,0.123014,0.043920,0.098072,...,0.081388,0.104927,0.009122,0.141746,0.068555,0.182287,0.085312,0.123391,0.101235,0.048872
231,0.166947,0.087203,0.147672,9999.000000,0.192827,0.179208,0.179160,0.154303,0.170697,0.163401,...,0.154091,0.201758,0.139674,0.010870,0.215350,0.076077,0.096279,0.024983,0.047840,0.171104
28,0.050624,0.107520,0.058803,0.192827,9999.000000,0.064687,0.053085,0.111199,0.085598,0.078034,...,0.067330,0.060258,0.061862,0.184939,0.039997,0.209385,0.107900,0.167844,0.145004,0.023336
377,0.021020,0.110667,0.036925,0.179208,0.064687,9999.000000,0.109102,0.155031,0.022308,0.126643,...,0.111001,0.122646,0.045993,0.174360,0.050457,0.218641,0.122196,0.155829,0.134607,0.068136
99,0.089749,0.093203,0.086505,0.179160,0.053085,0.109102,9999.000000,0.061130,0.126218,0.027690,...,0.026113,0.023150,0.083584,0.169501,0.092922,0.176685,0.083520,0.155333,0.134210,0.040967
278,0.134041,0.085378,0.123014,0.154303,0.111199,0.155031,0.061130,9999.000000,0.166876,0.033641,...,0.045094,0.072389,0.116277,0.143524,0.150951,0.128998,0.066009,0.134776,0.119321,0.092503
391,0.036705,0.111475,0.043920,0.170697,0.085598,0.022308,0.126218,0.166876,9999.000000,0.140924,...,0.124533,0.141652,0.051456,0.167057,0.072264,0.217113,0.125974,0.148635,0.128933,0.085682
167,0.106025,0.082014,0.098072,0.163401,0.078034,0.126643,0.027690,0.033641,0.140924,9999.000000,...,0.016933,0.042971,0.092833,0.153155,0.117969,0.152509,0.067470,0.140922,0.121659,0.060868
124,0.104060,0.085231,0.097033,0.167615,0.074002,0.124480,0.022662,0.038469,0.139409,0.005418,...,0.017446,0.037639,0.092223,0.157448,0.113993,0.157814,0.071467,0.144890,0.125277,0.057827
103,0.071075,0.101818,0.073155,0.189002,0.026904,0.088298,0.027088,0.087490,0.107629,0.053852,...,0.046615,0.034381,0.073004,0.180133,0.066165,0.195848,0.097170,0.164327,0.142010,0.024451
168,0.057369,0.121528,0.061411,0.170861,0.106722,0.043022,0.146185,0.183839,0.021131,0.159457,...,0.142798,0.162295,0.067566,0.168524,0.091720,0.223485,0.137964,0.150536,0.132786,0.106039
51,0.102399,0.145750,0.110393,0.232953,0.052044,0.114214,0.059138,0.116573,0.136050,0.085267,...,0.084772,0.044537,0.112425,0.223957,0.073273,0.235739,0.139872,0.208343,0.186084,0.065602
375,0.029585,0.122016,0.049098,0.196216,0.051873,0.022061,0.102135,0.154231,0.043518,0.123354,...,0.109190,0.112056,0.057845,0.190621,0.028764,0.230251,0.130657,0.172192,0.150229,0.062534
225,0.150782,0.072612,0.131513,0.016165,0.177200,0.163122,0.165368,0.144307,0.154931,0.150934,...,0.140740,0.188177,0.123536,0.013631,0.199249,0.081994,0.083473,0.010055,0.032281,0.155707
401,0.045957,0.119505,0.053393,0.175515,0.093996,0.029600,0.135622,0.176389,0.009576,0.150499,...,0.134109,0.150753,0.060738,0.172364,0.077767,0.224195,0.134551,0.154066,0.135021,0.094981
87,0.067501,0.068733,0.060312,0.155906,0.047509,0.088189,0.029047,0.067971,0.102539,0.038534,...,0.023022,0.051365,0.056082,0.146851,0.085247,0.163449,0.063683,0.131400,0.109382,0.025535
32,0.133168,0.109186,0.126882,0.185920,0.098274,0.153254,0.045444,0.035145,0.168921,0.029988,...,0.046775,0.045453,0.122155,0.175317,0.137785,0.164140,0.092419,0.164858,0.147187,0.085526
361,0.026773,0.117888,0.046070,0.193692,0.045589,0.024399,0.095678,0.148020,0.046606,0.117000,...,0.102954,0.105707,0.054485,0.187815,0.026411,0.225955,0.125830,0.169459,0.147279,0.056154
174,0.108518,0.048386,0.094223,0.123556,0.099190,0.129297,0.062174,0.037081,0.137771,0.040579,...,0.036364,0.082212,0.086315,0.113133,0.136132,0.114640,0.029738,0.101926,0.084325,0.076725
284,0.134059,0.074670,0.121137,0.139231,0.117046,0.155047,0.070421,0.015780,0.164981,0.042984,...,0.049720,0.084742,0.113649,0.128412,0.156056,0.113686,0.054501,0.120352,0.105972,0.096534
400,0.092944,0.100000,0.074051,0.087203,0.107520,0.110667,0.093203,0.085378,0.111475,0.082014,...,0.069583,0.116223,0.064935,0.078365,0.135278,0.108312,0.020440,0.062678,0.041017,0.084936
17,0.087548,0.107988,0.088468,0.194849,0.042829,0.104993,0.018827,0.078947,0.124177,0.046058,...,0.044266,0.017685,0.087462,0.185484,0.080730,0.195227,0.100269,0.170607,0.148886,0.039663
303,0.019514,0.074051,0.100000,0.147672,0.058803,0.036925,0.086505,0.123014,0.043920,0.098072,...,0.081388,0.104927,0.009122,0.141746,0.068555,0.182287,0.085312,0.123391,0.101235,0.048872
235,0.029585,0.122016,0.049098,0.196216,0.051873,0.022061,0.102135,0.154231,0.043518,0.123354,...,0.109190,0.112056,0.057845,0.190621,0.028764,0.230251,0.130657,0.172192,0.150229,0.062534
134,0.088757,0.136379,0.097221,0.223456,0.038590,0.100528,0.055071,0.115169,0.122337,0.082470,...,0.079321,0.045781,0.099624,0.214743,0.060791,0.229974,0.132027,0.198675,0.176183,0.053928
165,0.091517,0.042026,0.072678,0.076191,0.123941,0.103019,0.125519,0.127151,0.095367,0.120070,...,0.105463,0.148503,0.065448,0.071782,0.141162,0.125954,0.062311,0.053302,0.034399,0.104937
178,0.049494,0.056958,0.031619,0.118552,0.088275,0.060765,0.104607,0.126597,0.055965,0.108644,...,0.091889,0.125819,0.026441,0.113596,0.099889,0.161151,0.073916,0.095065,0.074058,0.073598
285,0.058836,0.151019,0.077000,0.218602,0.083766,0.040562,0.135534,0.188236,0.049730,0.157324,...,0.143208,0.143824,0.086122,0.214189,0.049535,0.259133,0.161698,0.195659,0.174796,0.096467
350,0.090180,0.069583,0.081388,0.154091,0.067330,0.111001,0.026113,0.045094,0.124533,0.016933,...,9999.000000,0.047767,0.075963,0.144227,0.106546,0.151004,0.057966,0.130686,0.110250,0.047491
132,0.104975,0.116223,0.104927,0.201758,0.060258,0.122646,0.023150,0.072389,0.141652,0.042971,...,0.047767,9999.000000,0.103239,0.191960,0.097145,0.195451,0.105729,0.178131,0.157202,0.056531
384,0.028319,0.064935,0.009122,0.139674,0.061862,0.045993,0.083584,0.116277,0.051456,0.092833,...,0.075963,0.103239,9999.000000,0.133482,0.075865,0.173188,0.076354,0.115215,0.092872,0.048569
359,0.161167,0.078365,0.141746,0.010870,0.184939,0.174360,0.169501,0.143524,0.167057,0.153155,...,0.144227,0.191960,0.133482,9999.000000,0.208782,0.069486,0.086296,0.018534,0.040682,0.162885
133,0.050764,0.135278,0.068555,0.215350,0.039997,0.050457,0.092922,0.150951,0.072264,0.117969,...,0.106546,0.097145,0.075865,0.208782,9999.000000,0.241702,0.140051,0.190707,0.168101,0.059718
358,0.201255,0.108312,0.182287,0.076077,0.209385,0.218641,0.176685,0.128998,0.217113,0.152509,...,0.151004,0.195451,0.173188,0.069486,0.241702,9999.000000,0.101833,0.080940,0.091999,0.186055
386,0.102871,0.020440,0.085312,0.096279,0.107900,0.122196,0.083520,0.066009,0.125974,0.067470,...,0.057966,0.105729,0.076354,0.086296,0.140051,0.101833,9999.000000,0.073454,0.054772,0.084583
362,0.142777,0.062678,0.123391,0.024983,0.167844,0.155829,0.155333,0.134776,0.148635,0.140922,...,0.130686,0.178131,0.115215,0.018534,0.190707,0.080940,0.073454,9999.000000,0.022864,0.146163
275,0.120706,0.041017,0.101235,0.047840,0.145004,0.134607,0.134210,0.119321,0.128933,0.121659,...,0.110250,0.157202,0.092872,0.040682,0.168101,0.091999,0.054772,0.022864,9999.000000,0.123428
131,0.049025,0.084936,0.048872,0.171104,0.023336,0.068136,0.040967,0.092503,0.085682,0.060868,...,0.047491,0.056531,0.048569,0.162885,0.059718,0.186055,0.084583,0.146163,0.123428,9999.000000

,309,91,112,412,246,413,283,61,291,28,...,116,167,81,384,186,30,372,89,96,375
309,9999.000000,0.132404,0.156457,0.086896,0.051776,0.053057,0.104605,0.202267,0.161215,0.153447,...,0.168404,0.118639,0.170681,0.106834,0.172763,0.193598,0.033157,0.150427,0.193467,0.164679
91,0.132404,9999.000000,0.093614,0.049841,0.083464,0.185432,0.100812,0.085150,0.196766,0.095992,...,0.124037,0.022877,0.047975,0.115700,0.181539,0.119862,0.160859,0.116180,0.091695,0.143883
112,0.156457,0.093614,9999.000000,0.086841,0.110011,0.202465,0.058329,0.075762,0.126499,0.005548,...,0.031239,0.076550,0.073782,0.066923,0.100183,0.037246,0.170150,0.030934,0.051802,0.056499
412,0.086896,0.049841,0.086841,9999.000000,0.035446,0.139579,0.064178,0.116268,0.158723,0.086251,...,0.110554,0.032053,0.083786,0.077536,0.150758,0.122340,0.112721,0.096599,0.111034,0.121340
246,0.051776,0.083464,0.110011,0.035446,9999.000000,0.104186,0.067869,0.150539,0.150236,0.107900,...,0.127398,0.067470,0.119080,0.076354,0.150644,0.147140,0.077565,0.110667,0.142699,0.130657
413,0.053057,0.185432,0.202465,0.139579,0.104186,9999.000000,0.146334,0.253912,0.177177,0.198779,...,0.209518,0.171486,0.223261,0.144317,0.197776,0.238868,0.033027,0.191262,0.243349,0.200231
283,0.104605,0.100812,0.058329,0.064178,0.067869,0.146334,9999.000000,0.125619,0.096310,0.053844,...,0.063932,0.077957,0.108521,0.014941,0.086713,0.093132,0.113513,0.045843,0.106677,0.062847
61,0.202267,0.085150,0.075762,0.116268,0.150539,0.253912,0.125619,9999.000000,0.202056,0.081273,...,0.100573,0.086901,0.037206,0.137813,0.173762,0.070772,0.224414,0.106366,0.027567,0.129188
291,0.161215,0.196766,0.126499,0.158723,0.150236,0.177177,0.096310,0.202056,9999.000000,0.121083,...,0.103997,0.174011,0.196399,0.081761,0.036513,0.141769,0.148600,0.095697,0.176527,0.075732
28,0.153447,0.095992,0.005548,0.086251,0.107900,0.198779,0.053844,0.081273,0.121083,9999.000000,...,0.028080,0.078034,0.078356,0.061862,0.095190,0.040225,0.166321,0.025675,0.057326,0.051873
54,0.198629,0.071644,0.092398,0.111767,0.147152,0.251334,0.134466,0.026258,0.218294,0.097603,...,0.120435,0.080067,0.028293,0.148007,0.192445,0.094629,0.223648,0.123276,0.051470,0.148242
371,0.030591,0.156931,0.165973,0.108656,0.073570,0.036963,0.109439,0.220180,0.146308,0.162164,...,0.172556,0.140667,0.191218,0.107415,0.163717,0.202163,0.004251,0.154300,0.208173,0.163692
253,0.032525,0.164688,0.185609,0.119387,0.084144,0.020922,0.130951,0.234422,0.172130,0.182202,...,0.194742,0.151162,0.203162,0.130553,0.189366,0.222418,0.023640,0.176521,0.224787,0.187665
36,0.161519,0.118947,0.027653,0.103958,0.120434,0.202950,0.057128,0.100209,0.102652,0.023623,...,0.006976,0.099994,0.101394,0.059456,0.073683,0.042204,0.169980,0.011857,0.074008,0.029293
68,0.120377,0.088260,0.037260,0.062127,0.076974,0.165324,0.022364,0.103518,0.110013,0.033465,...,0.050524,0.066225,0.088607,0.034558,0.093404,0.073647,0.132920,0.034785,0.084329,0.059423
285,0.191202,0.177642,0.087746,0.154832,0.161698,0.221594,0.094091,0.155553,0.067851,0.083766,...,0.056990,0.157324,0.161210,0.086122,0.031480,0.086669,0.189473,0.061470,0.128095,0.034021
342,0.020856,0.137841,0.148556,0.089336,0.054391,0.054043,0.093280,0.201045,0.141433,0.144979,...,0.157040,0.121327,0.171862,0.093012,0.154886,0.185147,0.023521,0.138817,0.189546,0.150404
84,0.212172,0.091345,0.087588,0.125706,0.160396,0.264134,0.137427,0.011945,0.213751,0.093110,...,0.111792,0.095462,0.043793,0.149710,0.185089,0.080529,0.235002,0.118091,0.038167,0.140511
191,0.117950,0.118367,0.059887,0.083780,0.085961,0.155282,0.019658,0.133139,0.078473,0.054556,...,0.055323,0.095691,0.120791,0.011171,0.067055,0.089935,0.122262,0.037519,0.111287,0.046753
190,0.117950,0.118367,0.059887,0.083780,0.085961,0.155282,0.019658,0.133139,0.078473,0.054556,...,0.055323,0.095691,0.120791,0.011171,0.067055,0.089935,0.122262,0.037519,0.111287,0.046753
219,0.034557,0.166409,0.188317,0.121452,0.086296,0.019754,0.133799,0.236684,0.174994,0.184939,...,0.197611,0.153155,0.205238,0.133482,0.192332,0.225160,0.026438,0.179396,0.227252,0.190621
388,0.164636,0.165046,0.083069,0.135996,0.138476,0.193676,0.072550,0.157018,0.048437,0.078043,...,0.056938,0.143354,0.156074,0.062123,0.017174,0.093780,0.161693,0.052543,0.130572,0.028108
176,0.103101,0.033855,0.081893,0.016744,0.052020,0.155960,0.071566,0.101602,0.167742,0.082365,...,0.108716,0.015538,0.067872,0.085983,0.156435,0.115207,0.129433,0.096851,0.098896,0.123247
115,66.029064,65.928691,65.872996,65.953668,65.982412,66.070634,65.925467,65.843708,65.911004,65.875742,...,65.861639,65.928822,65.880752,65.926360,65.880972,65.835753,66.037621,65.879866,65.843103,65.870799
205,0.032310,0.147651,0.184849,0.107959,0.075789,0.049430,0.135531,0.224114,0.192519,0.182266,...,0.198903,0.137882,0.190300,0.138669,0.205013,0.222094,0.050966,0.181147,0.218154,0.196477
9,0.167590,0.071009,0.037615,0.085209,0.116717,0.217782,0.084745,0.040964,0.163606,0.042778,...,0.066823,0.062042,0.037997,0.096852,0.137779,0.050106,0.187156,0.068453,0.025994,0.093839
276,0.138273,0.165147,0.098736,0.127455,0.121170,0.161995,0.064665,0.174459,0.031654,0.093205,...,0.080520,0.142375,0.166284,0.050192,0.035785,0.119110,0.130958,0.068847,0.150017,0.055167
421,0.103101,0.033855,0.081893,0.016744,0.052020,0.155960,0.071566,0.101602,0.167742,0.082365,...,0.108716,0.015538,0.067872,0.085983,0.156435,0.115207,0.129433,0.096851,0.098896,0.123247
387,0.166705,0.180958,0.102501,0.148315,0.146444,0.190532,0.084138,0.176993,0.029351,0.097333,...,0.077140,0.158758,0.174830,0.071462,0.008116,0.113941,0.159697,0.071669,0.150688,0.048330
138,0.187541,0.063636,0.080574,0.100656,0.135890,0.240049,0.121656,0.023886,0.206016,0.085668,...,0.109354,0.069407,0.016941,0.135213,0.180750,0.085875,0.211933,0.111329,0.043880,0.136766
116,0.168404,0.124037,0.031239,0.110554,0.127398,0.209518,0.063932,0.100573,0.103997,0.028080,...,9999.000000,0.105610,0.104237,0.065695,0.073347,0.038592,0.176527,0.018258,0.073764,0.028844
167,0.118639,0.022877,0.076550,0.032053,0.067470,0.171486,0.077957,0.086901,0.174011,0.078034,...,0.105610,9999.000000,0.052466,0.092833,0.159628,0.107019,0.144747,0.095979,0.086305,0.123354
81,0.170681,0.047975,0.073782,0.083786,0.119080,0.223261,0.108521,0.037206,0.196399,0.078356,...,0.104237,0.052466,9999.000000,0.122590,0.173249,0.086457,0.195383,0.103545,0.048799,0.130213
384,0.106834,0.115700,0.066923,0.077536,0.076354,0.144317,0.014941,0.137813,0.081761,0.061862,...,0.065695,0.092833,0.122590,9999.000000,0.074849,0.099005,0.111291,0.047603,0.117350,0.057845
186,0.172763,0.181539,0.100183,0.150758,0.150644,0.197776,0.086713,0.173762,0.036513,0.095190,...,0.073347,0.159628,0.173249,0.074849,9999.000000,0.109171,0.166689,0.069715,0.147109,0.044580
30,0.193598,0.119862,0.037246,0.122340,0.147140,0.238868,0.093132,0.070772,0.141769,0.040225,...,0.038592,0.107019,0.086457,0.099005,0.109171,9999.000000,0.206298,0.053170,0.043392,0.066037
372,0.033157,0.160859,0.170150,0.112721,0.077565,0.033027,0.113513,0.224414,0.148600,0.166321,...,0.176527,0.144747,0.195383,0.111291,0.166689,0.206298,9999.000000,0.158274,0.212422,0.167368
89,0.150427,0.116180,0.030934,0.096599,0.110667,0.191262,0.045843,0.106366,0.095697,0.025675,...,0.018258,0.095979,0.103545,0.047603,0.069715,0.053170,0.158274,9999.000000,0.081256,0.027817
96,0.193467,0.091695,0.051802,0.111034,0.142699,0.243349,0.106677,0.027567,0.176527,0.057326,...,0.073764,0.086305,0.048799,0.117350,0.147109,0.043392,0.212422,0.081256,9999.000000,0.102560
375,0.164679,0.143883,0.056499,0.121340,0.130657,0.200231,0.062847,0.129188,0.075732,0.051873,...,0.028844,0.123354,0.130213,0.057845,0.044580,0.066037,0.167368,0.027817,0.102560,9999.000000

,29,126,100,245,239,131,10,61,304,164,...,201,254,307,160,227,425,415,48,62,370
29,9999.000000,0.031069,0.027920,0.061970,0.104093,0.057067,0.016251,0.041503,0.102030,0.102030,...,0.030141,0.192557,0.046761,0.142416,0.184867,0.179175,0.128772,0.036425,0.015794,0.074586
126,0.031069,9999.000000,0.053346,0.046074,0.081065,0.028351,0.041469,0.069217,0.072152,0.072152,...,0.036203,0.166618,0.038840,0.121420,0.161181,0.151723,0.101088,0.034285,0.033538,0.069797
100,0.027920,0.053346,9999.000000,0.089824,0.131305,0.073008,0.037109,0.016314,0.117023,0.117023,...,0.057006,0.219023,0.074616,0.143542,0.212115,0.204799,0.154181,0.064112,0.041940,0.101457
245,0.061970,0.046074,0.089824,9999.000000,0.044293,0.060804,0.059352,0.103058,0.088121,0.088121,...,0.037556,0.133695,0.017736,0.153845,0.123973,0.122969,0.075119,0.028256,0.050660,0.030130
239,0.104093,0.081065,0.131305,0.044293,9999.000000,0.081819,0.103377,0.145594,0.086097,0.086097,...,0.081831,0.089426,0.062012,0.159155,0.080814,0.079175,0.035124,0.072494,0.094414,0.058100
131,0.057067,0.028351,0.073008,0.060804,0.081819,9999.000000,0.069429,0.089295,0.045052,0.045052,...,0.063571,0.158497,0.060868,0.095337,0.156837,0.141104,0.091829,0.059739,0.061843,0.089454
10,0.016251,0.041469,0.037109,0.059352,0.103377,0.069429,9999.000000,0.046204,0.113616,0.113616,...,0.022334,0.192757,0.042099,0.157930,0.183298,0.180909,0.131298,0.031212,0.009461,0.065336
61,0.041503,0.069217,0.016314,0.103058,0.145594,0.089295,0.046204,9999.000000,0.133139,0.133139,...,0.068010,0.233950,0.086901,0.156375,0.226355,0.220180,0.169623,0.076077,0.053155,0.111519
304,0.102030,0.072152,0.117023,0.088121,0.086097,0.045052,0.113616,0.133139,9999.000000,0.100000,...,0.104258,0.138768,0.095691,0.073268,0.143339,0.118418,0.077455,0.098271,0.105409,0.118115
164,0.102030,0.072152,0.117023,0.088121,0.086097,0.045052,0.113616,0.133139,0.100000,9999.000000,...,0.104258,0.138768,0.095691,0.073268,0.143339,0.118418,0.077455,0.098271,0.105409,0.118115
389,0.044100,0.030880,0.050076,0.076233,0.106132,0.028276,0.059859,0.065695,0.068203,0.068203,...,0.063701,0.186237,0.069623,0.098345,0.183636,0.169196,0.119546,0.064005,0.055447,0.100651
265,0.089816,0.061116,0.114402,0.045072,0.033000,0.052952,0.094195,0.130073,0.053645,0.053645,...,0.076186,0.106598,0.059692,0.126347,0.103905,0.090746,0.040209,0.067363,0.084735,0.071721
297,0.179175,0.151723,0.204799,0.122969,0.079175,0.141104,0.180909,0.220180,0.118418,0.118418,...,0.160145,0.021674,0.140667,0.182818,0.037231,0.100000,0.050637,0.150766,0.171635,0.135266
250,0.110260,0.081917,0.135166,0.060279,0.029416,0.072392,0.113781,0.150769,0.062454,0.062454,...,0.094670,0.086227,0.076746,0.135409,0.085088,0.069943,0.019560,0.085523,0.104337,0.082501
355,0.102000,0.074116,0.113512,0.097351,0.100035,0.045778,0.115094,0.129199,0.015473,0.015473,...,0.108611,0.153998,0.102650,0.059205,0.158804,0.133481,0.092899,0.103704,0.107620,0.127474
92,0.042564,0.050020,0.067638,0.038808,0.081946,0.076598,0.030705,0.076598,0.115464,0.115464,...,0.014356,0.170550,0.022342,0.171297,0.158874,0.161101,0.113904,0.017230,0.026772,0.035230
292,0.198393,0.171786,0.224536,0.140374,0.096093,0.162358,0.199161,0.239664,0.140291,0.140291,...,0.177874,0.009177,0.158102,0.203941,0.031197,0.021890,0.071015,0.168516,0.190027,0.149585
411,0.065833,0.058816,0.093275,0.019741,0.054599,0.078222,0.058264,0.104333,0.107827,0.107827,...,0.036405,0.141535,0.020480,0.172545,0.129090,0.133378,0.088621,0.029507,0.051461,0.011253
84,0.051628,0.080474,0.028165,0.112160,0.155337,0.101173,0.053706,0.011945,0.145082,0.145082,...,0.075991,0.244119,0.095462,0.167124,0.235929,0.230778,0.180317,0.084551,0.061623,0.118288
422,0.056736,0.052037,0.084047,0.020662,0.061176,0.073665,0.048929,0.094998,0.106450,0.106450,...,0.027105,0.149287,0.013233,0.168750,0.137468,0.140321,0.094186,0.020665,0.042178,0.018367
41,0.083524,0.073008,0.078295,0.116642,0.139939,0.058455,0.099772,0.089870,0.075166,0.075166,...,0.106174,0.210626,0.111835,0.067232,0.211797,0.191368,0.145280,0.106614,0.096822,0.142668
277,0.136900,0.109288,0.162370,0.082564,0.041117,0.099769,0.139235,0.177793,0.083507,0.083507,...,0.119026,0.058732,0.100012,0.153880,0.059925,0.042438,0.008201,0.109686,0.129878,0.099214
42,0.035374,0.015152,0.050113,0.060623,0.092509,0.023032,0.049495,0.066424,0.067830,0.067830,...,0.049495,0.175288,0.053972,0.109168,0.171379,0.159202,0.108876,0.048859,0.043404,0.084949
113,0.048354,0.021486,0.073593,0.028865,0.059599,0.032253,0.053644,0.088943,0.066366,0.066366,...,0.038921,0.145563,0.029909,0.126800,0.139733,0.131252,0.080680,0.032034,0.044285,0.057225
60,0.015712,0.041906,0.035765,0.060690,0.104676,0.069735,0.001447,0.044759,0.114055,0.114055,...,0.023748,0.194043,0.043477,0.157739,0.184647,0.182125,0.132460,0.032581,0.010549,0.066778
31,0.032130,0.061085,0.038865,0.076589,0.120881,0.088559,0.020086,0.040386,0.133161,0.133161,...,0.039124,0.210255,0.058874,0.173875,0.199709,0.199258,0.150167,0.048503,0.029351,0.076578
204,0.144039,0.113046,0.164335,0.106680,0.079330,0.091969,0.151745,0.180639,0.055030,0.055030,...,0.136152,0.092153,0.121003,0.112486,0.102663,0.070537,0.049953,0.127836,0.142478,0.131914
295,0.141422,0.113683,0.151343,0.133176,0.126656,0.085362,0.154683,0.166566,0.045080,0.045080,...,0.147789,0.159632,0.140499,0.046631,0.169506,0.137995,0.109314,0.142441,0.147203,0.163116
342,0.159953,0.132817,0.185754,0.103640,0.060011,0.123365,0.161548,0.201045,0.104169,0.104169,...,0.140781,0.035342,0.121327,0.171858,0.040835,0.019369,0.031875,0.131403,0.152281,0.116733
305,0.150904,0.120974,0.174086,0.103646,0.067183,0.104937,0.155945,0.190135,0.076115,0.076115,...,0.137634,0.065089,0.120070,0.139205,0.075304,0.043656,0.032468,0.128604,0.146486,0.124409
201,0.030141,0.036203,0.057006,0.037556,0.081831,0.063571,0.022334,0.068010,0.104258,0.104258,...,9999.000000,0.171247,0.019965,0.157623,0.161247,0.160145,0.111273,0.009379,0.015082,0.044537
254,0.192557,0.166618,0.219023,0.133695,0.089426,0.158497,0.192757,0.233950,0.138768,0.138768,...,0.171247,9999.000000,0.151384,0.204292,0.022245,0.021674,0.066696,0.161918,0.183714,0.141766
307,0.046761,0.038840,0.074616,0.017736,0.062012,0.060868,0.042099,0.086901,0.095691,0.095691,...,0.019965,0.151384,9999.000000,0.156138,0.141289,0.140667,0.092435,0.010917,0.033859,0.031095
160,0.142416,0.121420,0.143542,0.153845,0.159155,0.095337,0.157930,0.156375,0.073268,0.073268,...,0.157623,0.204292,0.156138,9999.000000,0.212425,0.182818,0.148836,0.154808,0.152532,0.183617
227,0.184867,0.161181,0.212115,0.123973,0.080814,0.156837,0.183298,0.226355,0.143339,0.143339,...,0.161247,0.022245,0.141289,0.212425,9999.000000,0.037231,0.066710,0.152109,0.174616,0.127829
425,0.179175,0.151723,0.204799,0.122969,0.079175,0.141104,0.180909,0.220180,0.118418,0.118418,...,0.160145,0.021674,0.140667,0.182818,0.037231,9999.000000,0.050637,0.150766,0.171635,0.135266
415,0.128772,0.101088,0.154181,0.075119,0.035124,0.091829,0.131298,0.169623,0.077455,0.077455,...,0.111273,0.066696,0.092435,0.148836,0.066710,0.050637,9999.000000,0.101956,0.121920,0.093035
48,0.036425,0.034285,0.064112,0.028256,0.072494,0.059739,0.031212,0.076077,0.098271,0.098271,...,0.009379,0.161918,0.010917,0.154808,0.152109,0.150766,0.101956,9999.000000,0.022969,0.038956
62,0.015794,0.033538,0.041940,0.050660,0.094414,0.061843,0.009461,0.053155,0.105409,0.105409,...,0.015082,0.183714,0.033859,0.152532,0.174616,0.171635,0.121920,0.022969,9999.000000,0.059534
370,0.074586,0.069797,0.101457,0.030130,0.058100,0.089454,0.065336,0.111519,0.118115,0.118115,...,0.044537,0.141766,0.031095,0.183617,0.127829,0.135266,0.093035,0.038956,0.059534,9999.000000

,411,298,266,178,145,48,290,190,112,122,...,19,349,347,111,42,295,224,375,389,185
411,9999.000000,0.136100,0.074247,0.114949,0.085732,0.029507,0.162873,0.107827,0.096076,0.099727,...,0.095232,0.158238,0.061069,0.068096,0.073960,0.152893,0.059756,0.139968,0.089695,0.017898
298,0.136100,9999.000000,0.086297,0.106088,0.198676,0.156909,0.152265,0.136863,0.180504,0.228935,...,0.222051,0.024134,0.078612,0.198250,0.171415,0.159308,0.097794,0.182935,0.182660,0.121283
266,0.074247,0.086297,9999.000000,0.046732,0.114204,0.082604,0.101150,0.060009,0.094319,0.148973,...,0.141044,0.110384,0.026895,0.120580,0.085743,0.097921,0.015520,0.106013,0.096406,0.069175
178,0.114949,0.106088,0.046732,9999.000000,0.126385,0.114367,0.055020,0.035543,0.093287,0.168013,...,0.158897,0.127633,0.073134,0.144772,0.096324,0.055378,0.056874,0.078037,0.100217,0.113552
145,0.085732,0.198676,0.114204,0.126385,9999.000000,0.056393,0.148868,0.096575,0.040632,0.044252,...,0.034652,0.222732,0.121689,0.037392,0.030201,0.131288,0.101051,0.096383,0.029934,0.102506
48,0.029507,0.156909,0.082604,0.114367,0.056393,9999.000000,0.155353,0.098271,0.072034,0.073023,...,0.067421,0.180105,0.078546,0.041601,0.048859,0.142441,0.067097,0.122034,0.064005,0.046889
290,0.162873,0.152265,0.101150,0.055020,0.148868,0.155353,9999.000000,0.057157,0.108862,0.193101,...,0.183507,0.170683,0.127886,0.176662,0.122417,0.019686,0.109114,0.063314,0.119048,0.164595
190,0.107827,0.136863,0.060009,0.035543,0.096575,0.098271,0.057157,9999.000000,0.059887,0.140054,...,0.130597,0.159612,0.085479,0.120791,0.067830,0.045080,0.061368,0.046753,0.068203,0.112046
112,0.096076,0.180504,0.094319,0.093287,0.040632,0.072034,0.108862,0.059887,9999.000000,0.084739,...,0.075149,0.204517,0.110055,0.073782,0.023255,0.090877,0.085083,0.056499,0.010990,0.108987
122,0.099727,0.228935,0.148973,0.168013,0.044252,0.073023,0.193101,0.140054,0.084739,9999.000000,...,0.009601,0.252459,0.150327,0.031688,0.072350,0.175525,0.134288,0.139583,0.074168,0.117591
100,0.093275,0.214588,0.131656,0.146435,0.020462,0.064112,0.169124,0.117023,0.060477,0.024428,...,0.014987,0.238486,0.136552,0.030745,0.050113,0.151343,0.117765,0.115166,0.050076,0.110935
86,0.064123,0.157183,0.071775,0.086051,0.042772,0.042862,0.117559,0.061056,0.032379,0.082061,...,0.073099,0.181310,0.082194,0.059871,0.014360,0.102675,0.059427,0.079198,0.028401,0.076611
340,0.057588,0.113852,0.028777,0.058075,0.085507,0.057556,0.105615,0.052702,0.068851,0.120574,...,0.112479,0.137984,0.041416,0.092978,0.057563,0.097019,0.016364,0.092768,0.069370,0.059541
299,0.133011,0.146962,0.079610,0.040921,0.115980,0.123175,0.033302,0.025258,0.076464,0.160146,...,0.150567,0.168206,0.106242,0.143365,0.089137,0.019909,0.083939,0.040474,0.086325,0.136697
39,16.504171,16.629366,16.576895,16.607627,16.485887,16.495364,16.634087,16.582006,16.525305,16.442000,...,16.451506,16.645396,16.564587,16.462919,16.514186,16.615540,16.561495,16.575003,16.515374,16.514409
407,0.355288,0.228949,0.285370,0.264638,0.390837,0.367959,0.261385,0.297338,0.357133,0.431186,...,0.422412,0.215249,0.294290,0.405007,0.360662,0.280679,0.300865,0.323856,0.364710,0.343871
293,0.055307,0.099035,0.019390,0.061423,0.099642,0.063611,0.113449,0.064881,0.085529,0.131812,...,0.124274,0.123094,0.024617,0.102565,0.073007,0.107292,0.004576,0.107687,0.085591,0.052136
159,0.133011,0.146962,0.079610,0.040921,0.115980,0.123175,0.033302,0.025258,0.076464,0.160146,...,0.150567,0.168206,0.106242,0.143365,0.089137,0.019909,0.083939,0.040474,0.086325,0.136697
263,0.358001,0.232183,0.287830,0.266561,0.392830,0.370431,0.262498,0.299072,0.358901,0.433337,...,0.424531,0.218706,0.297034,0.407310,0.362669,0.281848,0.303334,0.325105,0.366561,0.346707
235,0.139968,0.182935,0.106013,0.078037,0.096383,0.122034,0.063314,0.046753,0.056499,0.139583,...,0.130130,0.205217,0.130285,0.130213,0.077059,0.043637,0.104897,0.100000,0.067476,0.148404
133,0.136801,0.200963,0.118639,0.099889,0.076908,0.114161,0.092056,0.065048,0.042338,0.117529,...,0.108437,0.224120,0.139864,0.113384,0.065569,0.072371,0.113855,0.028764,0.051921,0.148216
10,0.058264,0.187836,0.110594,0.136180,0.038312,0.031212,0.170064,0.113616,0.070424,0.041885,...,0.036974,0.211161,0.109293,0.010420,0.049495,0.154683,0.095370,0.126282,0.059859,0.076161
376,0.029029,0.114491,0.045275,0.086693,0.089553,0.042449,0.136579,0.083780,0.086841,0.114745,...,0.108332,0.137802,0.036123,0.083786,0.068534,0.128271,0.030760,0.121340,0.083557,0.028293
128,0.082763,0.216023,0.140018,0.164740,0.051167,0.059206,0.195674,0.140253,0.090566,0.022219,...,0.025038,0.239066,0.137751,0.019989,0.073285,0.179269,0.124753,0.146986,0.079577,0.100289
147,0.101147,0.224303,0.141634,0.156296,0.030010,0.072392,0.177918,0.126503,0.069069,0.018170,...,0.010917,0.248161,0.146125,0.035538,0.059982,0.159884,0.127667,0.122665,0.058998,0.118946
254,0.141535,0.006032,0.089835,0.107172,0.202854,0.161918,0.151882,0.138768,0.183790,0.233711,...,0.226718,0.020934,0.083467,0.203163,0.175288,0.159632,0.101839,0.184522,0.186237,0.126905
129,0.124468,0.180853,0.099348,0.079790,0.077405,0.104758,0.077486,0.044797,0.037485,0.120801,...,0.111310,0.203937,0.121567,0.111241,0.058537,0.058121,0.095620,0.019033,0.048453,0.134247
198,0.160730,0.185647,0.116778,0.079794,0.122470,0.145206,0.046439,0.057509,0.082379,0.165702,...,0.156252,0.206493,0.142802,0.155892,0.102124,0.029267,0.118862,0.026124,0.093369,0.167380
1,0.044575,0.163904,0.084405,0.110063,0.041390,0.016110,0.146646,0.089600,0.056730,0.065242,...,0.058149,0.187577,0.085381,0.036241,0.033476,0.132437,0.069379,0.108742,0.048204,0.061119
115,65.947616,66.051404,65.966648,65.948807,65.864438,65.918477,65.917310,65.915360,65.872996,65.850156,...,65.853145,66.074732,65.982552,65.880752,65.886404,65.903187,65.958061,65.870799,65.872832,65.965322
19,0.095232,0.222051,0.141044,0.158897,0.034652,0.067421,0.183507,0.130597,0.075149,0.009601,...,9999.000000,0.245720,0.143523,0.027621,0.062987,0.165925,0.126574,0.130130,0.064567,0.113127
349,0.158238,0.024134,0.110384,0.127633,0.222732,0.180105,0.170683,0.159612,0.204517,0.252459,...,0.245720,9999.000000,0.102197,0.221581,0.195546,0.179319,0.121910,0.205217,0.206770,0.142715
347,0.061069,0.078612,0.026895,0.073134,0.121689,0.078546,0.127886,0.085479,0.110055,0.150327,...,0.143523,0.102197,9999.000000,0.119697,0.096526,0.124760,0.026009,0.130285,0.109721,0.050511
111,0.068096,0.198250,0.120580,0.144772,0.037392,0.041601,0.176662,0.120791,0.073782,0.031688,...,0.027621,0.221581,0.119697,9999.000000,0.054672,0.160684,0.105441,0.130213,0.062884,0.085980
42,0.073960,0.171415,0.085743,0.096324,0.030201,0.048859,0.122417,0.067830,0.023255,0.072350,...,0.062987,0.195546,0.096526,0.054672,9999.000000,0.106065,0.073714,0.077059,0.015760,0.087986
295,0.152893,0.159308,0.097921,0.055378,0.131288,0.142441,0.019686,0.045080,0.090877,0.175525,...,0.165925,0.179319,0.124760,0.160684,0.106065,9999.000000,0.103275,0.043637,0.101358,0.156560
224,0.059756,0.097794,0.015520,0.056874,0.101051,0.067097,0.109114,0.061368,0.085083,0.134288,...,0.126574,0.121910,0.026009,0.105441,0.073714,0.103275,9999.000000,0.104897,0.085732,0.056697
375,0.139968,0.182935,0.106013,0.078037,0.096383,0.122034,0.063314,0.046753,0.056499,0.139583,...,0.130130,0.205217,0.130285,0.130213,0.077059,0.043637,0.104897,9999.000000,0.067476,0.148404
389,0.089695,0.182660,0.096406,0.100217,0.029934,0.064005,0.119048,0.068203,0.010990,0.074168,...,0.064567,0.206770,0.109721,0.062884,0.015760,0.101358,0.085732,0.067476,9999.000000,0.103709
185,0.017898,0.121283,0.069175,0.113552,0.102506,0.046889,0.164595,0.112046,0.108987,0.117591,...,0.113127,0.142715,0.050511,0.085980,0.087986,0.156560,0.056697,0.148404,0.103709,9999.000000

,76,45,420,225,331,401,122,345,127,318,...,34,92,105,309,162,409,65,106,204,177
76,9999.000000,0.119071,0.025569,0.171419,0.111364,0.165159,0.066837,0.156343,0.045482,0.127757,...,0.085363,0.005986,0.012932,0.138734,0.070723,0.156202,0.109276,0.056692,0.141050,0.026967
45,0.119071,9999.000000,0.107550,0.202934,0.069636,0.085881,0.109925,0.213086,0.111978,0.104939,...,0.034203,0.124913,0.114278,0.182739,0.099750,0.059013,0.015315,0.062996,0.124204,0.121965
420,0.025569,0.107550,9999.000000,0.149590,0.088307,0.142998,0.083631,0.138716,0.064345,0.102455,...,0.073431,0.028141,0.034354,0.117935,0.045158,0.137028,0.100504,0.045394,0.115489,0.014612
225,0.171419,0.202934,0.149590,9999.000000,0.134587,0.159947,0.232684,0.042235,0.213934,0.102432,...,0.182450,0.170528,0.182935,0.033861,0.115604,0.181971,0.207383,0.171456,0.086952,0.144497
331,0.111364,0.069636,0.088307,0.134587,9999.000000,0.055095,0.140054,0.149725,0.130711,0.035543,...,0.059237,0.115464,0.114386,0.117950,0.052702,0.057396,0.077100,0.067490,0.055030,0.098303
401,0.165159,0.085881,0.142998,0.159947,0.055095,9999.000000,0.184119,0.185811,0.178709,0.063245,...,0.096764,0.169597,0.166845,0.153656,0.106918,0.030957,0.099831,0.115581,0.073595,0.153370
122,0.066837,0.109925,0.083631,0.232684,0.140054,0.184119,9999.000000,0.221816,0.021757,0.168013,...,0.087496,0.070620,0.053906,0.201502,0.120574,0.164476,0.095116,0.072892,0.185300,0.092043
345,0.156343,0.213086,0.138716,0.042235,0.149725,0.185811,0.221816,9999.000000,0.201340,0.123548,...,0.187288,0.154065,0.168911,0.032310,0.116039,0.203266,0.214571,0.170309,0.112823,0.129948
127,0.045482,0.111978,0.064345,0.213934,0.130711,0.178709,0.021757,0.201340,9999.000000,0.155653,...,0.084389,0.048993,0.032610,0.182124,0.104498,0.162189,0.098300,0.063605,0.171910,0.071392
318,0.127757,0.104939,0.102455,0.102432,0.035543,0.063245,0.168013,0.123548,0.155653,9999.000000,...,0.093263,0.130578,0.133833,0.091243,0.058075,0.080254,0.112623,0.095505,0.019534,0.108339
94,0.030595,0.103397,0.046153,0.195627,0.114247,0.164032,0.037668,0.184153,0.018666,0.137800,...,0.072773,0.035406,0.018203,0.164086,0.085876,0.149596,0.091061,0.048486,0.153712,0.054497
134,0.078325,0.053292,0.077204,0.208412,0.092987,0.130127,0.056746,0.207816,0.059798,0.125809,...,0.034427,0.084262,0.069754,0.181575,0.093236,0.108389,0.038841,0.037547,0.144820,0.091227
25,0.048745,0.121577,0.070037,0.219315,0.139891,0.188325,0.023793,0.205071,0.009775,0.164109,...,0.094164,0.051259,0.036480,0.187050,0.111805,0.171959,0.107767,0.073039,0.180024,0.075496
414,0.124055,0.076909,0.100557,0.131715,0.013238,0.044533,0.153089,0.150463,0.143940,0.029518,...,0.070840,0.128008,0.127402,0.118264,0.062436,0.053072,0.086105,0.080658,0.047856,0.109924
172,0.159248,0.069748,0.138698,0.172501,0.054352,0.018115,0.172221,0.195619,0.168548,0.072079,...,0.084837,0.164081,0.159597,0.163311,0.106976,0.012842,0.084279,0.106668,0.085549,0.150240
145,0.059101,0.070177,0.061328,0.200962,0.096575,0.139944,0.044252,0.196702,0.041866,0.126385,...,0.043625,0.064963,0.049931,0.172280,0.085507,0.121296,0.056871,0.031255,0.144525,0.074556
41,0.114615,0.009019,0.104818,0.207043,0.075166,0.094612,0.101812,0.215545,0.104820,0.110685,...,0.031741,0.120530,0.109033,0.185707,0.100915,0.068022,0.006696,0.059597,0.130107,0.119374
85,0.065120,0.099798,0.079224,0.227145,0.130875,0.174217,0.010166,0.217918,0.023203,0.159557,...,0.077517,0.069546,0.052360,0.196526,0.113783,0.154348,0.085033,0.064124,0.177144,0.088897
338,0.157030,0.060404,0.137718,0.181373,0.057509,0.029659,0.165702,0.202922,0.163308,0.079794,...,0.078986,0.162100,0.156459,0.170638,0.109167,0.001425,0.075339,0.102813,0.094561,0.149939
366,0.047447,0.149218,0.042700,0.134985,0.118065,0.172756,0.114091,0.113170,0.092494,0.120884,...,0.115399,0.043503,0.060315,0.101156,0.065925,0.172239,0.142954,0.087953,0.128265,0.028168
381,0.068107,0.137150,0.048494,0.103501,0.091324,0.143797,0.131905,0.090242,0.111926,0.087133,...,0.106077,0.067029,0.080039,0.070627,0.039750,0.148242,0.134567,0.083809,0.092459,0.041141
79,0.011051,0.112709,0.031165,0.179942,0.111454,0.164101,0.056125,0.166277,0.035088,0.130654,...,0.079702,0.016114,0.003241,0.147665,0.075124,0.153150,0.102020,0.051834,0.145012,0.036352
352,0.186219,0.223563,0.165604,0.021038,0.155479,0.180582,0.249152,0.040208,0.229791,0.123469,...,0.202342,0.184826,0.198168,0.047673,0.134238,0.202948,0.227682,0.190177,0.107849,0.159265
46,0.121758,0.024232,0.115123,0.223869,0.092433,0.109298,0.098823,0.231337,0.105392,0.127955,...,0.044854,0.127742,0.114605,0.201901,0.115951,0.081025,0.016767,0.069864,0.147377,0.129728
71,0.071393,0.070850,0.076086,0.215873,0.107433,0.147165,0.039078,0.211927,0.044456,0.138767,...,0.050626,0.077040,0.060856,0.187414,0.100310,0.126028,0.056116,0.045104,0.157313,0.088925
288,0.220987,0.202323,0.195672,0.087810,0.136769,0.128449,0.269488,0.129949,0.255268,0.103065,...,0.195834,0.222299,0.229599,0.111347,0.151382,0.158532,0.212464,0.197903,0.084515,0.196774
72,0.071578,0.058555,0.053135,0.155707,0.045052,0.094981,0.095370,0.159191,0.085714,0.073598,...,0.028172,0.076598,0.072001,0.130816,0.043260,0.084706,0.056241,0.022518,0.091969,0.066533
165,0.141073,0.145573,0.115964,0.060128,0.076115,0.101029,0.193010,0.085870,0.177256,0.042462,...,0.129172,0.142200,0.150153,0.054644,0.072761,0.121888,0.151700,0.124238,0.027435,0.116571
6,0.077507,0.108353,0.093080,0.241393,0.144002,0.185741,0.011267,0.231646,0.032884,0.173345,...,0.089031,0.081492,0.064590,0.210637,0.128119,0.164599,0.093205,0.077840,0.191104,0.102190
258,0.077134,0.115625,0.052242,0.101090,0.063364,0.115228,0.132620,0.099792,0.115173,0.059611,...,0.087723,0.078263,0.086580,0.072721,0.016296,0.120647,0.115487,0.071378,0.067611,0.052929
34,0.085363,0.034203,0.073431,0.182450,0.059237,0.096764,0.087496,0.187288,0.084389,0.093263,...,9999.000000,0.091127,0.081543,0.158587,0.071429,0.077844,0.028504,0.028878,0.112627,0.087910
92,0.005986,0.124913,0.028141,0.170528,0.115464,0.169597,0.070620,0.154065,0.048993,0.130578,...,0.091127,9999.000000,0.017247,0.137528,0.073020,0.161295,0.115220,0.062381,0.143288,0.026315
105,0.012932,0.114278,0.034354,0.182935,0.114386,0.166845,0.053906,0.168911,0.032610,0.133833,...,0.081543,0.017247,9999.000000,0.150577,0.078364,0.155538,0.103296,0.053991,0.148237,0.039075
309,0.138734,0.182739,0.117935,0.033861,0.117950,0.153656,0.201502,0.032310,0.182124,0.091243,...,0.158587,0.137528,0.150577,9999.000000,0.088455,0.170992,0.185162,0.144099,0.081047,0.111767
162,0.070723,0.099750,0.045158,0.115604,0.052702,0.106918,0.120574,0.116039,0.104498,0.058075,...,0.071429,0.073020,0.078364,0.088455,9999.000000,0.108860,0.099249,0.055941,0.070332,0.050287
409,0.156202,0.059013,0.137028,0.181971,0.057396,0.030957,0.164476,0.203266,0.162189,0.080254,...,0.077844,0.161295,0.155538,0.170992,0.108860,9999.000000,0.073965,0.101842,0.095212,0.149320
65,0.109276,0.015315,0.100504,0.207383,0.077100,0.099831,0.095116,0.214571,0.098300,0.112623,...,0.028504,0.115220,0.103296,0.185162,0.099249,0.073965,9999.000000,0.055120,0.132128,0.115104
106,0.056692,0.062996,0.045394,0.171456,0.067490,0.115581,0.072892,0.170309,0.063605,0.095505,...,0.028878,0.062381,0.053991,0.144099,0.055941,0.101842,0.055120,9999.000000,0.113401,0.060002
204,0.141050,0.124204,0.115489,0.086952,0.055030,0.073595,0.185300,0.112823,0.171910,0.019534,...,0.112627,0.143288,0.148237,0.081047,0.070332,0.095212,0.132128,0.113401,9999.000000,0.119479
177,0.026967,0.121965,0.014612,0.144497,0.098303,0.153370,0.092043,0.129948,0.071392,0.108339,...,0.087910,0.026315,0.039075,0.111767,0.050287,0.149320,0.115104,0.060002,0.119479,9999.000000

In [ ]:
!pip install xlsxwriter

Collecting xlsxwriter
  Downloading xlsxwriter-3.2.9-py3-none-any.whl.metadata (2.7 kB)
Downloading xlsxwriter-3.2.9-py3-none-any.whl (175 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 1.8 MB/s eta 0:00:00
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.2.9

In [ ]:
# Save sub matrices to a excel file for later use.
archivo_salida = "matrices_40.xlsx"

with pd.ExcelWriter(archivo_salida, engine="xlsxwriter") as writer:
    for idx, matriz in enumerate(matrices_40):
        hoja_nombre = f"Instancia_{idx+1}"
        matriz.to_excel(writer, sheet_name=hoja_nombre, index=True)

## Read pre-generated submatrices.

In [8]:
archivo = "/content/tsp-bio-inspired-algorithms/Data_for_algorithms/matrices_40.xlsx"

# Read file.
hojas_dict = pd.read_excel(archivo, sheet_name=None, index_col=0)

# Convert lists into dataframes.
matrices_40 = [hojas_dict[f"Instancia_{i+1}"] for i in range(10)]

# Validation.
print(len(matrices_40))  # print number of instances 10.
print(matrices_40[0].head()) # print first instance.
print(matrices_40[0].shape) # print first instance shape.

10
             332          163          115          388          402  \
332  9999.000000     0.269340    66.004588     0.317838     0.257123
163     0.269340  9999.000000    65.918566     0.053220     0.029585
115    66.004588    65.918566  9999.000000    65.880899    65.897945
388     0.317838     0.053220    65.880899  9999.000000     0.061222
402     0.257123     0.029585    65.897945     0.061222  9999.000000

           361        41         383        89         418  ...        26   \
332   0.291817   0.280746   0.261074   0.270650   0.146346  ...   0.214347
163   0.046070   0.079073   0.153423   0.041487   0.123014  ...   0.094960
115  65.872791  65.843577  66.071954  65.879866  65.956187  ...  65.874983
388   0.033375   0.072928   0.195391   0.052543   0.172043  ...   0.122073
402   0.036477   0.054506   0.174931   0.019133   0.112184  ...   0.067193

           43         277        334        239        351        225  \
332   0.213167   0.231830   0.199969   0.196066   0.337408   0.252114
163   0.070429   0.081178   0.085312   0.085725   0.071857   0.131513
115  65.901805  65.996210  65.982412  65.978857  65.872865  66.049866
388   0.108022   0.130594   0.138476   0.138944   0.019576   0.174883
402   0.047341   0.098296   0.091566   0.090129   0.080649   0.152544

           92         271        15
332   0.160885   0.160022   0.184349
163   0.118168   0.109604   0.124407
115  65.920244  65.947616  65.880752
388   0.160614   0.158033   0.156074
402   0.099455   0.097973   0.098802

[5 rows x 40 columns]
(40, 40)

In [ ]:
for i in matrices_40:
  display(i)

,332,163,115,388,402,361,41,383,89,418,...,26,43,277,334,239,351,225,92,271,15
332,9999.000000,0.269340,66.004588,0.317838,0.257123,0.291817,0.280746,0.261074,0.270650,0.146346,...,0.214347,0.213167,0.231830,0.199969,0.196066,0.337408,0.252114,0.160885,0.160022,0.184349
163,0.269340,9999.000000,65.918566,0.053220,0.029585,0.046070,0.079073,0.153423,0.041487,0.123014,...,0.094960,0.070429,0.081178,0.085312,0.085725,0.071857,0.131513,0.118168,0.109604,0.124407
115,66.004588,65.918566,9999.000000,65.880899,65.897945,65.872791,65.843577,66.071954,65.879866,65.956187,...,65.874983,65.901805,65.996210,65.982412,65.978857,65.872865,66.049866,65.920244,65.947616,65.880752
388,0.317838,0.053220,65.880899,9999.000000,0.061222,0.033375,0.072928,0.195391,0.052543,0.172043,...,0.122073,0.108022,0.130594,0.138476,0.138944,0.019576,0.174883,0.160614,0.158033,0.156074
402,0.257123,0.029585,65.897945,0.061222,9999.000000,0.036477,0.054506,0.174931,0.019133,0.112184,...,0.067193,0.047341,0.098296,0.091566,0.090129,0.080649,0.152544,0.099455,0.097973,0.098802
361,0.291817,0.046070,65.872791,0.033375,0.036477,9999.000000,0.042078,0.199344,0.021360,0.148020,...,0.089575,0.079105,0.126757,0.125830,0.124994,0.050224,0.177529,0.132140,0.133748,0.123945
41,0.280746,0.079073,65.843577,0.072928,0.054506,0.042078,9999.000000,0.229417,0.037678,0.145388,...,0.067053,0.072554,0.152640,0.142353,0.139939,0.085659,0.207043,0.120530,0.131566,0.100504
383,0.261074,0.153423,66.071954,0.195391,0.174931,0.199344,0.229417,9999.000000,0.192442,0.162446,...,0.213041,0.182209,0.078448,0.104232,0.109535,0.207593,0.022479,0.190369,0.161147,0.223310
89,0.270650,0.041487,65.879866,0.052543,0.019133,0.021360,0.037678,0.192442,9999.000000,0.127498,...,0.069570,0.057766,0.116671,0.110667,0.109142,0.070728,0.170166,0.110791,0.113210,0.103545
418,0.146346,0.123014,65.956187,0.172043,0.112184,0.148020,0.145388,0.162446,0.127498,9999.000000,...,0.087536,0.072987,0.101699,0.066009,0.060614,0.191611,0.144307,0.035958,0.014288,0.075449
112,0.247820,0.064128,65.872996,0.083069,0.034554,0.050314,0.035583,0.203318,0.030934,0.109987,...,0.039285,0.037032,0.125070,0.110011,0.107031,0.100537,0.180844,0.086952,0.096076,0.073782
48,0.176573,0.101016,65.918477,0.143589,0.082384,0.115602,0.106614,0.182009,0.094303,0.040993,...,0.046559,0.036613,0.109686,0.077885,0.072494,0.162946,0.161348,0.017230,0.029507,0.041601
151,0.343812,0.075940,65.911004,0.048437,0.097641,0.080037,0.121109,0.179268,0.095697,0.197923,...,0.163908,0.144248,0.130842,0.150236,0.152465,0.043106,0.161831,0.193933,0.184917,0.196399
108,0.223993,0.073155,65.885640,0.103005,0.045791,0.071674,0.058191,0.196393,0.050691,0.087490,...,0.021822,0.016454,0.118166,0.097170,0.093322,0.121416,0.174143,0.063128,0.073936,0.053408
12,0.194148,0.135904,65.861809,0.162159,0.108457,0.129118,0.100016,0.242160,0.109998,0.094598,...,0.041271,0.068080,0.167450,0.137956,0.132749,0.179211,0.221031,0.058683,0.087649,0.019586
226,0.149440,0.120327,65.963942,0.170598,0.111769,0.148013,0.148097,0.152939,0.127954,0.009616,...,0.092968,0.075564,0.093552,0.057917,0.052688,0.190111,0.134968,0.044216,0.017308,0.083497
336,0.197469,0.072971,65.931279,0.120475,0.060615,0.096727,0.099372,0.156529,0.076674,0.051658,...,0.057677,0.029673,0.080869,0.053373,0.048820,0.140050,0.134973,0.047608,0.037563,0.068802
20,0.201926,0.115988,65.869418,0.143075,0.088557,0.110284,0.083998,0.226720,0.090689,0.087593,...,0.021424,0.048922,0.150695,0.122981,0.118024,0.160492,0.205199,0.052475,0.078200,0.017586
251,0.313219,0.043920,65.902711,0.022068,0.062347,0.046606,0.088629,0.174945,0.060383,0.166876,...,0.128335,0.109355,0.113685,0.125974,0.127216,0.033182,0.154931,0.160064,0.153360,0.160959
371,0.253184,0.115275,66.033773,0.158430,0.136922,0.161243,0.191368,0.038187,0.154300,0.137288,...,0.178023,0.146890,0.042438,0.073570,0.079175,0.171541,0.016473,0.161101,0.133378,0.191218
51,0.235266,0.110393,65.844926,0.125080,0.080841,0.091755,0.057140,0.240395,0.075809,0.116573,...,0.030131,0.058544,0.162242,0.139872,0.135625,0.140442,0.218185,0.083413,0.105314,0.050956
146,0.193895,0.147317,65.854272,0.172159,0.119581,0.138948,0.107929,0.253242,0.120318,0.103090,...,0.052438,0.079847,0.178929,0.149009,0.143741,0.188842,0.232240,0.067536,0.097155,0.029974
195,0.285961,0.028214,65.935855,0.057050,0.057709,0.065335,0.103727,0.138488,0.067244,0.140912,...,0.122815,0.096888,0.075888,0.091611,0.093704,0.071191,0.117838,0.141332,0.128538,0.151223
101,0.230769,0.135062,65.831055,0.149004,0.105558,0.115828,0.078751,0.260716,0.100548,0.125928,...,0.047676,0.078715,0.183191,0.158303,0.153660,0.163685,0.238750,0.090475,0.116593,0.052087
366,0.150310,0.119394,65.963110,0.169609,0.110738,0.146974,0.147031,0.153056,0.126903,0.009397,...,0.091979,0.074499,0.093216,0.057556,0.052291,0.189126,0.134985,0.043503,0.016305,0.082728
213,0.187675,0.091150,65.977418,0.144248,0.093035,0.128611,0.141034,0.115518,0.111805,0.052073,...,0.103502,0.075621,0.049639,0.013952,0.008787,0.163004,0.095488,0.075041,0.046821,0.108371
63,0.279470,0.089105,65.835588,0.083415,0.063367,0.052942,0.010878,0.238165,0.047619,0.147294,...,0.065123,0.075321,0.160864,0.148783,0.146060,0.095456,0.215737,0.120399,0.133790,0.097125
147,0.215239,0.130596,65.846524,0.150453,0.101670,0.117082,0.083846,0.249006,0.099695,0.109961,...,0.037597,0.068556,0.172292,0.145650,0.140793,0.166409,0.227299,0.074287,0.101147,0.035538
171,0.190972,0.078700,65.949283,0.129561,0.072524,0.108994,0.115816,0.140865,0.090128,0.045199,...,0.075256,0.047649,0.067706,0.036744,0.031744,0.148988,0.119791,0.054166,0.033277,0.082601
58,0.272389,0.055550,65.866800,0.059426,0.031163,0.026052,0.023741,0.205847,0.014064,0.131843,...,0.064709,0.059594,0.129458,0.121207,0.119238,0.075818,0.183507,0.111588,0.117640,0.099313
26,0.214347,0.094960,65.874983,0.122073,0.067193,0.089575,0.067053,0.213041,0.069570,0.087536,...,9999.000000,0.031219,0.135591,0.110978,0.106496,0.139789,0.191079,0.056457,0.075681,0.034622
43,0.213167,0.070429,65.901805,0.108022,0.047341,0.079105,0.072554,0.182209,0.057766,0.072987,...,0.031219,9999.000000,0.104478,0.081475,0.077416,0.127164,0.160137,0.053042,0.059044,0.054362
277,0.231830,0.081178,65.996210,0.130594,0.098296,0.126757,0.152640,0.078448,0.116671,0.101699,...,0.135591,0.104478,9999.000000,0.035692,0.041117,0.146565,0.056060,0.121275,0.095361,0.149460
334,0.199969,0.085312,65.982412,0.138476,0.091566,0.125830,0.142353,0.104232,0.110667,0.066009,...,0.110978,0.081475,0.035692,9999.000000,0.005625,0.156698,0.083473,0.087537,0.060210,0.119080
239,0.196066,0.085725,65.978857,0.138944,0.090129,0.124994,0.139939,0.109535,0.109142,0.060614,...,0.106496,0.077416,0.041117,0.005625,9999.000000,0.157424,0.088926,0.081946,0.054599,0.113791
351,0.337408,0.071857,65.872865,0.019576,0.080649,0.050224,0.085659,0.207593,0.070728,0.191611,...,0.139789,0.127164,0.146565,0.156698,0.157424,9999.000000,0.187870,0.179918,0.177608,0.174095
225,0.252114,0.131513,66.049866,0.174883,0.152544,0.177529,0.207043,0.022479,0.170166,0.144307,...,0.191079,0.160137,0.056060,0.083473,0.088926,0.187870,9999.000000,0.170528,0.141851,0.202384
92,0.160885,0.118168,65.920244,0.160614,0.099455,0.132140,0.120530,0.190369,0.110791,0.035958,...,0.056457,0.053042,0.121275,0.087537,0.081946,0.179918,0.170528,9999.000000,0.030089,0.039495
271,0.160022,0.109604,65.947616,0.158033,0.097973,0.133748,0.131566,0.161147,0.113210,0.014288,...,0.075681,0.059044,0.095361,0.060210,0.054599,0.177608,0.141851,0.030089,9999.000000,0.068096
15,0.184349,0.124407,65.880752,0.156074,0.098802,0.123945,0.100504,0.223310,0.103545,0.075449,...,0.034622,0.054362,0.149460,0.119080,0.113791,0.174095,0.202384,0.039495,0.068096,9999.000000

,88,33,327,379,418,137,369,392,249,361,...,56,152,210,72,310,24,122,345,346,403
88,9999.000000,0.027717,0.152298,0.065644,0.037905,0.114868,0.152506,0.066516,0.062115,0.114835,...,0.041758,0.162546,0.018279,0.058707,0.139178,0.035719,0.078892,0.142939,0.132615,0.364884
33,0.027717,9999.000000,0.179668,0.089065,0.027868,0.136043,0.180170,0.080884,0.083509,0.141888,...,0.057401,0.175406,0.044301,0.085955,0.166632,0.054318,0.079307,0.149250,0.160213,0.383984
327,0.152298,0.179668,9999.000000,0.119048,0.175820,0.126434,0.015952,0.130697,0.109427,0.066281,...,0.150837,0.149864,0.135528,0.100705,0.013476,0.145680,0.193101,0.174385,0.043548,0.262498
379,0.065644,0.089065,0.119048,9999.000000,0.103262,0.050096,0.112831,0.106132,0.086632,0.061302,...,0.037408,0.190328,0.061896,0.028276,0.105886,0.036276,0.074168,0.185119,0.084897,0.366561
418,0.037905,0.027868,0.175820,0.103262,9999.000000,0.152740,0.178784,0.060614,0.070357,0.148020,...,0.078059,0.151293,0.045094,0.092503,0.163502,0.072945,0.106475,0.122452,0.163011,0.363434
137,0.114868,0.136043,0.126434,0.050096,0.152740,9999.000000,0.114709,0.153580,0.131994,0.060353,...,0.079368,0.230296,0.111976,0.071835,0.115649,0.081729,0.094700,0.230718,0.083527,0.387200
369,0.152506,0.180170,0.015952,0.112831,0.178784,0.114709,9999.000000,0.137839,0.115307,0.055744,...,0.146671,0.164217,0.136642,0.097730,0.018052,0.142171,0.186929,0.186735,0.031228,0.276606
392,0.066516,0.080884,0.130697,0.106132,0.060614,0.153580,0.137839,9999.000000,0.024383,0.124994,...,0.101712,0.096093,0.052980,0.081819,0.120421,0.094000,0.144588,0.079868,0.131371,0.303492
249,0.062115,0.083509,0.109427,0.086632,0.070357,0.131994,0.115307,0.024383,9999.000000,0.100664,...,0.089319,0.106084,0.044723,0.060329,0.098349,0.081464,0.135032,0.098866,0.107238,0.302779
361,0.114835,0.141888,0.066281,0.061302,0.148020,0.060353,0.055744,0.124994,0.100664,9999.000000,...,0.097985,0.183055,0.102954,0.056154,0.055301,0.095163,0.133835,0.192766,0.024977,0.327061
161,0.011568,0.025559,0.155303,0.075981,0.027322,0.125618,0.156647,0.058795,0.058336,0.122120,...,0.053313,0.154769,0.020031,0.066118,0.142452,0.047261,0.088907,0.133116,0.138538,0.360117
130,0.078145,0.103951,0.098672,0.020937,0.114120,0.048886,0.091984,0.105563,0.083335,0.040833,...,0.057153,0.182131,0.069818,0.024078,0.085672,0.054573,0.094945,0.181898,0.064008,0.349892
401,0.149900,0.177574,0.017038,0.110020,0.176389,0.112200,0.002812,0.135963,0.113283,0.053066,...,0.143875,0.163922,0.134109,0.094981,0.016912,0.139391,0.184119,0.185811,0.028679,0.278607
13,0.068107,0.079701,0.161734,0.042707,0.103055,0.066536,0.155125,0.128045,0.114219,0.101800,...,0.026801,0.220299,0.075614,0.066457,0.148591,0.034186,0.032035,0.207566,0.126276,0.406457
354,0.130687,0.158370,0.027289,0.092307,0.157632,0.100060,0.021902,0.119477,0.096148,0.039708,...,0.125266,0.156676,0.115007,0.075950,0.015597,0.120569,0.166468,0.174486,0.020610,0.287508
428,0.202974,0.224148,0.111418,0.203280,0.206597,0.228124,0.127260,0.146044,0.141119,0.169566,...,0.222561,0.085544,0.185046,0.176440,0.117151,0.215239,0.269488,0.129949,0.152010,0.163887
30,0.102616,0.123328,0.128218,0.038808,0.140519,0.012882,0.117680,0.144023,0.123228,0.062086,...,0.066519,0.223770,0.100568,0.062919,0.116643,0.069039,0.083305,0.222094,0.086533,0.386802
257,0.009817,0.036986,0.142729,0.061433,0.042350,0.111367,0.143228,0.060138,0.053352,0.107085,...,0.043324,0.155666,0.008752,0.050994,0.129660,0.036228,0.084451,0.138269,0.124049,0.356059
331,0.095393,0.122935,0.057157,0.068203,0.121395,0.093461,0.057572,0.086097,0.061977,0.043315,...,0.095530,0.140291,0.079137,0.045052,0.043868,0.089744,0.140054,0.149725,0.045277,0.299072
17,0.041238,0.061419,0.140026,0.028810,0.078947,0.074756,0.136014,0.095780,0.081527,0.088125,...,0.010843,0.187600,0.044266,0.039663,0.126570,0.007473,0.056965,0.175540,0.110311,0.376468
134,0.077619,0.095671,0.140831,0.025803,0.115169,0.042374,0.132906,0.128108,0.110352,0.078235,...,0.038274,0.215212,0.079321,0.053928,0.128066,0.042263,0.056746,0.207816,0.103089,0.391884
155,0.139929,0.167594,0.019686,0.101358,0.166398,0.106749,0.012577,0.126656,0.103732,0.046652,...,0.134609,0.158657,0.124095,0.085362,0.011720,0.129957,0.175525,0.178686,0.024160,0.281848
216,0.143115,0.170585,0.047684,0.092252,0.174280,0.084308,0.032862,0.143493,0.119343,0.030952,...,0.128799,0.186653,0.129708,0.084706,0.041971,0.125720,0.164476,0.203266,0.012130,0.309467
302,0.052704,0.077525,0.105615,0.069370,0.070222,0.115059,0.109203,0.039146,0.017264,0.087353,...,0.074101,0.122528,0.034426,0.043260,0.093429,0.066321,0.120574,0.116039,0.096952,0.314413
25,0.063942,0.058332,0.195447,0.079708,0.086115,0.110461,0.191127,0.130420,0.124373,0.141008,...,0.044612,0.226483,0.079772,0.094978,0.181993,0.050182,0.023793,0.205071,0.164386,0.426218
143,0.049706,0.062607,0.156507,0.039928,0.084960,0.076822,0.151600,0.110724,0.098320,0.101223,...,0.009057,0.204150,0.057916,0.057076,0.143109,0.016902,0.038796,0.189914,0.124567,0.394629
109,0.078928,0.106626,0.074708,0.051935,0.107415,0.083964,0.073624,0.079918,0.055646,0.045121,...,0.077572,0.146429,0.063638,0.027165,0.061291,0.071740,0.122436,0.150409,0.055715,0.314626
194,0.071912,0.086507,0.128635,0.109581,0.066009,0.156418,0.136341,0.005625,0.025392,0.125830,...,0.106485,0.090641,0.057966,0.084583,0.118740,0.098730,0.149755,0.075789,0.131145,0.297921
76,0.018075,0.017379,0.168496,0.072179,0.040506,0.118696,0.167824,0.082557,0.080004,0.126838,...,0.040075,0.178581,0.036308,0.071578,0.155231,0.036992,0.066837,0.156343,0.146251,0.382681
125,0.091939,0.114076,0.119687,0.026745,0.129731,0.023377,0.110257,0.130959,0.110004,0.054619,...,0.058622,0.210641,0.088603,0.049682,0.107573,0.059920,0.082737,0.208869,0.079569,0.376156
56,0.041758,0.057401,0.150837,0.037408,0.078059,0.079368,0.146671,0.101712,0.089319,0.097985,...,9999.000000,0.195107,0.048978,0.050503,0.137384,0.007860,0.046967,0.180990,0.120595,0.386389
152,0.162546,0.175406,0.149864,0.190328,0.151293,0.230296,0.164217,0.096093,0.106084,0.183055,...,0.195107,9999.000000,0.147884,0.162358,0.147577,0.187250,0.239822,0.045768,0.176083,0.217122
210,0.018279,0.044301,0.135528,0.061896,0.045094,0.111976,0.136642,0.052980,0.044723,0.102954,...,0.048978,0.147884,9999.000000,0.047491,0.122595,0.041428,0.091957,0.132012,0.118690,0.347357
72,0.058707,0.085955,0.100705,0.028276,0.092503,0.071835,0.097730,0.081819,0.060329,0.056154,...,0.050503,0.162358,0.047491,9999.000000,0.087229,0.044990,0.095370,0.159191,0.074681,0.340127
310,0.139178,0.166632,0.013476,0.105886,0.163502,0.115649,0.018052,0.120421,0.098349,0.055301,...,0.137384,0.147577,0.122595,0.087229,9999.000000,0.132207,0.179850,0.168901,0.034913,0.271947
24,0.035719,0.054318,0.145680,0.036276,0.072945,0.081729,0.142171,0.094000,0.081464,0.095163,...,0.007860,0.187250,0.041428,0.044990,0.132207,9999.000000,0.054483,0.173402,0.117012,0.379018
122,0.078892,0.079307,0.193101,0.074168,0.106475,0.094700,0.186929,0.144588,0.135032,0.133835,...,0.046967,0.239822,0.091957,0.095370,0.179850,0.054483,9999.000000,0.221816,0.158283,0.433337
345,0.142939,0.149250,0.174385,0.185119,0.122452,0.230718,0.186735,0.079868,0.098866,0.192766,...,0.180990,0.045768,0.132012,0.159191,0.168901,0.173402,0.221816,9999.000000,0.191628,0.259421
346,0.132615,0.160213,0.043548,0.084897,0.163011,0.083527,0.031228,0.131371,0.107238,0.024977,...,0.120595,0.176083,0.118690,0.074681,0.034913,0.117012,0.158283,0.191628,9999.000000,0.305973
403,0.364884,0.383984,0.262498,0.366561,0.363434,0.387200,0.276606,0.303492,0.302779,0.327061,...,0.386389,0.217122,0.347357,0.340127,0.271947,0.379018,0.433337,0.259421,0.305973,9999.000000

,191,178,375,376,380,47,337,286,144,162,...,117,368,391,264,0,154,366,151,157,150
191,9999.000000,0.035543,0.046753,0.083780,0.095997,0.072003,0.056361,0.123902,0.060786,0.052702,...,0.018004,0.114953,0.045541,0.028991,0.099494,0.056123,0.118065,0.078473,0.118418,0.057157
178,0.035543,9999.000000,0.078037,0.086693,0.069722,0.088661,0.061750,0.091662,0.096304,0.058075,...,0.048459,0.117633,0.055965,0.042039,0.118988,0.060622,0.120884,0.076361,0.085985,0.055020
375,0.046753,0.078037,9999.000000,0.121340,0.142712,0.099109,0.053449,0.169299,0.039140,0.092768,...,0.050367,0.150253,0.043518,0.041882,0.118621,0.054548,0.153062,0.075732,0.163692,0.063314
376,0.083780,0.086693,0.121340,9999.000000,0.073984,0.033658,0.138764,0.111549,0.107466,0.031257,...,0.071892,0.031567,0.128775,0.111848,0.053396,0.138238,0.034779,0.158723,0.108656,0.136579
380,0.095997,0.069722,0.142712,0.073984,9999.000000,0.099990,0.130638,0.037795,0.148982,0.069676,...,0.098250,0.092275,0.125647,0.111469,0.126298,0.129368,0.094901,0.141550,0.034673,0.122184
47,0.072003,0.088661,0.099109,0.033658,0.099990,9999.000000,0.128126,0.137609,0.077910,0.034030,...,0.055491,0.053805,0.116892,0.100855,0.030554,0.127987,0.056147,0.150474,0.133878,0.129003
337,0.056361,0.061750,0.053449,0.138764,0.130638,0.128126,9999.000000,0.146536,0.090886,0.107526,...,0.072810,0.170267,0.011814,0.027372,0.154444,0.001648,0.173441,0.023789,0.140801,0.012591
286,0.123902,0.091662,0.169299,0.111549,0.037795,0.137609,0.146536,9999.000000,0.181168,0.106379,...,0.129821,0.127393,0.144313,0.132884,0.164084,0.145046,0.129748,0.151893,0.005756,0.135961
144,0.060786,0.096304,0.039140,0.107466,0.148982,0.077910,0.090886,0.181168,9999.000000,0.085542,...,0.051348,0.131712,0.079870,0.072621,0.089225,0.091765,0.134046,0.114016,0.175972,0.099162
162,0.052702,0.058075,0.092768,0.031257,0.069676,0.034030,0.107526,0.106379,0.085542,9999.000000,...,0.042442,0.062744,0.097524,0.080594,0.064197,0.107016,0.065925,0.127734,0.102193,0.105615
95,0.141845,0.168822,0.143426,0.112269,0.184958,0.086127,0.190388,0.222752,0.105267,0.119831,...,0.124063,0.110046,0.178619,0.166300,0.058901,0.190870,0.109796,0.214178,0.219330,0.195682
16,0.098905,0.131048,0.091195,0.102975,0.165339,0.069487,0.140987,0.201779,0.052265,0.095663,...,0.082808,0.115913,0.129466,0.119217,0.060623,0.141671,0.117177,0.164595,0.197372,0.147798
382,0.081847,0.090765,0.115056,0.014731,0.087275,0.020329,0.138007,0.125028,0.097236,0.032716,...,0.067621,0.035285,0.127384,0.110692,0.039164,0.137650,0.038022,0.159152,0.121873,0.137160
171,0.077484,0.081711,0.114807,0.006534,0.074224,0.029252,0.132705,0.111991,0.101327,0.025204,...,0.065384,0.037569,0.122607,0.105699,0.052120,0.132208,0.040736,0.152903,0.108808,0.130772
21,0.108308,0.136558,0.110366,0.090832,0.159701,0.059818,0.156506,0.197190,0.073118,0.091538,...,0.090684,0.097615,0.144727,0.132398,0.040922,0.156974,0.098357,0.180295,0.193298,0.161767
393,0.141687,0.110617,0.187665,0.119387,0.049407,0.148171,0.166574,0.020236,0.197416,0.118974,...,0.146232,0.130694,0.164083,0.152227,0.172724,0.165096,0.132677,0.172130,0.025871,0.156107
425,0.118418,0.085985,0.163692,0.108656,0.034673,0.133878,0.140801,0.005756,0.175972,0.102193,...,0.124626,0.125704,0.138556,0.127150,0.160810,0.139313,0.128153,0.146308,0.100000,0.130257
365,0.134587,0.102432,0.180055,0.118919,0.046189,0.146142,0.156985,0.010770,0.191576,0.115604,...,0.140242,0.132797,0.154931,0.143619,0.171899,0.155482,0.134985,0.161831,0.016473,0.146278
55,0.130139,0.156887,0.133202,0.101580,0.173753,0.074521,0.179289,0.211532,0.095591,0.108090,...,0.112309,0.101397,0.167498,0.154904,0.048225,0.179734,0.101404,0.203074,0.208025,0.184333
266,0.060009,0.046732,0.106013,0.045275,0.042051,0.061833,0.106348,0.077857,0.107742,0.028777,...,0.058143,0.073733,0.098492,0.082188,0.090905,0.105438,0.076935,0.122860,0.073532,0.101150
269,0.057396,0.080254,0.024922,0.139088,0.149153,0.120304,0.035625,0.171244,0.063744,0.108860,...,0.067274,0.169281,0.029882,0.038379,0.141911,0.037116,0.172239,0.054571,0.165506,0.047684
38,0.089761,0.125264,0.062194,0.127199,0.175764,0.094801,0.115629,0.208978,0.028982,0.109550,...,0.079487,0.147448,0.105369,0.100159,0.097477,0.116700,0.149354,0.137755,0.203888,0.125077
28,0.054556,0.088275,0.051873,0.086251,0.133067,0.056094,0.097311,0.167093,0.021838,0.066520,...,0.039967,0.109899,0.085598,0.074439,0.068704,0.097860,0.112218,0.121083,0.162164,0.103343
397,0.087331,0.101336,0.114916,0.030255,0.103085,0.015951,0.143615,0.140857,0.092083,0.044019,...,0.071204,0.040917,0.132486,0.116282,0.023284,0.143429,0.042793,0.165716,0.137646,0.144074
132,0.101298,0.125819,0.112056,0.071385,0.142128,0.042425,0.153445,0.179846,0.078334,0.075873,...,0.083294,0.077185,0.141652,0.127748,0.020483,0.153704,0.077981,0.177041,0.176212,0.157203
395,0.024325,0.058421,0.023456,0.099178,0.120088,0.079779,0.054593,0.148163,0.041051,0.069823,...,0.027424,0.128913,0.042818,0.032191,0.102687,0.055073,0.131830,0.078381,0.142655,0.060541
374,0.132906,0.101793,0.178846,0.112986,0.041501,0.140987,0.157985,0.012367,0.188869,0.111178,...,0.137637,0.125917,0.155370,0.143428,0.166167,0.156517,0.128046,0.163910,0.017660,0.147619
265,0.053645,0.051689,0.097004,0.035004,0.058569,0.045080,0.105836,0.094990,0.093808,0.011514,...,0.047021,0.066134,0.096603,0.079714,0.074806,0.105161,0.069383,0.124731,0.090746,0.102607
152,0.140291,0.107571,0.185428,0.126087,0.053249,0.153229,0.160827,0.016623,0.197778,0.122528,...,0.146429,0.139798,0.159210,0.148369,0.179058,0.159300,0.141958,0.164756,0.021890,0.149864
350,0.079137,0.091889,0.109190,0.024217,0.094909,0.011283,0.135498,0.132703,0.089129,0.034426,...,0.063638,0.042593,0.124533,0.108128,0.031621,0.135252,0.045003,0.157302,0.129319,0.135528
117,0.018004,0.048459,0.050367,0.071892,0.098250,0.055491,0.072810,0.129821,0.051348,0.042442,...,9999.000000,0.102044,0.061449,0.045762,0.081923,0.072754,0.105028,0.095598,0.124626,0.074708
368,0.114953,0.117633,0.150253,0.031567,0.092275,0.053805,0.170267,0.127393,0.131712,0.062744,...,0.102044,9999.000000,0.160166,0.143265,0.056703,0.169760,0.003252,0.190287,0.125704,0.168142
391,0.045541,0.055965,0.043518,0.128775,0.125647,0.116892,0.011814,0.144313,0.079870,0.097524,...,0.061449,0.160166,9999.000000,0.016949,0.142860,0.012262,0.163312,0.035577,0.138556,0.019796
264,0.028991,0.042039,0.041882,0.111848,0.111469,0.100855,0.027372,0.132884,0.072621,0.080594,...,0.045762,0.143265,0.016949,9999.000000,0.127648,0.027147,0.146418,0.049840,0.127150,0.029489
0,0.099494,0.118988,0.118621,0.053396,0.126298,0.030554,0.154444,0.164084,0.089225,0.064197,...,0.081923,0.056703,0.142860,0.127648,9999.000000,0.154486,0.057518,0.177485,0.160810,0.156589
154,0.056123,0.060622,0.054548,0.138238,0.129368,0.127987,0.001648,0.145046,0.091765,0.107016,...,0.072754,0.169760,0.012262,0.027147,0.154486,9999.000000,0.172940,0.023372,0.139313,0.010955
366,0.118065,0.120884,0.153062,0.034779,0.094901,0.056147,0.173441,0.129748,0.134046,0.065925,...,0.105028,0.003252,0.163312,0.146418,0.057518,0.172940,9999.000000,0.193502,0.128153,0.171358
151,0.078473,0.076361,0.075732,0.158723,0.141550,0.150474,0.023789,0.151893,0.114016,0.127734,...,0.095598,0.190287,0.035577,0.049840,0.177485,0.023372,0.193502,9999.000000,0.146308,0.022148
157,0.118418,0.085985,0.163692,0.108656,0.034673,0.133878,0.140801,0.005756,0.175972,0.102193,...,0.124626,0.125704,0.138556,0.127150,0.160810,0.139313,0.128153,0.146308,9999.000000,0.130257
150,0.057157,0.055020,0.063314,0.136579,0.122184,0.129003,0.012591,0.135961,0.099162,0.105615,...,0.074708,0.168142,0.019796,0.029489,0.156589,0.010955,0.171358,0.022148,0.130257,9999.000000

,297,396,145,67,420,267,397,175,398,314,...,174,16,399,255,154,394,26,52,209,29
297,9999.000000,0.050637,0.187698,0.178725,0.138663,0.223895,0.137646,0.176154,0.088488,0.102930,...,0.102930,0.197372,0.169196,0.142655,0.139313,0.021674,0.178023,0.169731,0.041660,0.179175
396,0.050637,9999.000000,0.137100,0.132507,0.089527,0.267059,0.088460,0.146857,0.038090,0.058744,...,0.058744,0.147053,0.119546,0.101338,0.114769,0.066696,0.127390,0.124375,0.087322,0.128772
145,0.187698,0.137100,9999.000000,0.059925,0.061328,0.390837,0.061711,0.141631,0.100000,0.101662,...,0.101662,0.015521,0.029934,0.088676,0.143738,0.202854,0.010557,0.065635,0.222732,0.022770
67,0.178725,0.132507,0.059925,9999.000000,0.094929,0.357241,0.094567,0.083073,0.104505,0.123113,...,0.123113,0.052465,0.034801,0.042957,0.092765,0.197906,0.061770,0.010457,0.218827,0.078127
420,0.138663,0.089527,0.061328,0.094929,9999.000000,0.355334,0.001142,0.157934,0.052242,0.041552,...,0.041552,0.075907,0.062896,0.096530,0.144395,0.150352,0.050893,0.093681,0.168872,0.044289
267,0.223895,0.267059,0.390837,0.357241,0.355334,9999.000000,0.354219,0.302702,0.303121,0.324899,...,0.324899,0.395580,0.364710,0.314316,0.271478,0.222918,0.383178,0.346786,0.215249,0.389424
397,0.137646,0.088460,0.061711,0.094567,0.001142,0.354219,9999.000000,0.157138,0.051136,0.040873,...,0.040873,0.076204,0.062733,0.095730,0.143429,0.149409,0.051247,0.093202,0.167969,0.044966
175,0.176154,0.146857,0.141631,0.083073,0.157934,0.302702,0.157138,9999.000000,0.139107,0.169155,...,0.169155,0.135515,0.112936,0.061409,0.038277,0.197812,0.141248,0.076029,0.217339,0.156570
398,0.088488,0.038090,0.100000,0.104505,0.052242,0.303121,0.051136,0.139107,9999.000000,0.032747,...,0.032747,0.110925,0.085434,0.083098,0.114532,0.102859,0.090018,0.098129,0.122785,0.090715
314,0.102930,0.058744,0.101662,0.123113,0.041552,0.324899,0.040873,0.169155,0.032747,9999.000000,...,0.100000,0.115404,0.096561,0.110371,0.146662,0.111799,0.091106,0.118860,0.129237,0.085836
141,0.158329,0.111966,0.060826,0.020546,0.081320,0.341175,0.080775,0.082484,0.084695,0.105307,...,0.105307,0.058512,0.031071,0.028797,0.083339,0.177401,0.059083,0.013610,0.198318,0.074108
115,66.033773,65.988841,65.864438,65.856347,65.925507,66.138445,65.925979,65.868439,65.958019,65.966039,...,65.966039,65.850694,65.872832,65.891166,65.906489,66.053808,65.874983,65.864728,66.074732,65.882094
325,0.120538,0.079407,0.102506,0.133770,0.041743,0.343871,0.041622,0.186913,0.053948,0.021715,...,0.021715,0.117403,0.103709,0.126740,0.166465,0.126905,0.092244,0.130955,0.142715,0.083314
103,0.160364,0.110003,0.028827,0.049463,0.047145,0.362052,0.047002,0.123272,0.074064,0.081979,...,0.081979,0.037053,0.015773,0.065265,0.119763,0.176375,0.021822,0.050635,0.196607,0.034100
178,0.085985,0.054196,0.126385,0.098750,0.102455,0.264638,0.101336,0.093387,0.059611,0.092268,...,0.092268,0.131048,0.100217,0.058421,0.060622,0.107172,0.119223,0.088754,0.127633,0.127370
150,0.130257,0.108550,0.148868,0.100385,0.145084,0.261385,0.144074,0.048934,0.111680,0.144224,...,0.144224,0.147798,0.119048,0.060541,0.010955,0.151882,0.144999,0.090374,0.170683,0.157552
365,0.016473,0.064170,0.200962,0.194355,0.149590,0.220074,0.148621,0.192485,0.101090,0.111818,...,0.111818,0.211196,0.183611,0.158863,0.155482,0.006177,0.191079,0.185511,0.025201,0.191285
330,0.118418,0.077455,0.096575,0.063212,0.088307,0.297338,0.087331,0.075829,0.063364,0.093518,...,0.093518,0.098905,0.068203,0.024325,0.056123,0.138768,0.091021,0.053222,0.159612,0.102030
205,0.051007,0.072276,0.196702,0.202817,0.138716,0.256013,0.137957,0.216885,0.099792,0.097370,...,0.097370,0.209110,0.185119,0.173589,0.182256,0.036944,0.186251,0.195347,0.041040,0.182815
213,0.086563,0.043857,0.114013,0.128857,0.055978,0.308887,0.055157,0.166879,0.027830,0.016391,...,0.016391,0.126982,0.105446,0.110648,0.141335,0.095583,0.103502,0.123437,0.113346,0.099846
204,0.070537,0.049953,0.144525,0.118241,0.115489,0.246322,0.114350,0.105731,0.067611,0.098827,...,0.098827,0.149857,0.119120,0.077432,0.069642,0.092153,0.136918,0.108199,0.111997,0.144039
74,0.137866,0.090540,0.072065,0.108249,0.013326,0.357528,0.013771,0.170226,0.055389,0.036259,...,0.036259,0.087114,0.075981,0.108838,0.155212,0.147827,0.061914,0.106972,0.165481,0.052823
144,0.175972,0.129652,0.059020,0.002909,0.092463,0.355365,0.092083,0.083296,0.101598,0.120309,...,0.120309,0.052265,0.033007,0.041051,0.091765,0.195105,0.060401,0.008802,0.216024,0.076672
123,0.155738,0.105642,0.041390,0.082407,0.020309,0.368825,0.020871,0.153050,0.067578,0.061692,...,0.061692,0.056354,0.048204,0.092596,0.144440,0.168593,0.031158,0.083135,0.187577,0.024315
173,0.097144,0.052824,0.100568,0.081581,0.075872,0.290355,0.074773,0.099911,0.039858,0.071804,...,0.071804,0.106573,0.076181,0.048631,0.074862,0.116528,0.092848,0.072691,0.137462,0.100269
333,0.109294,0.062908,0.092204,0.114689,0.032421,0.329893,0.031683,0.163752,0.031645,0.009470,...,0.009470,0.105936,0.087416,0.104070,0.142944,0.119296,0.081648,0.110822,0.137226,0.076632
425,0.100000,0.050637,0.187698,0.178725,0.138663,0.223895,0.137646,0.176154,0.088488,0.102930,...,0.102930,0.197372,0.169196,0.142655,0.139313,0.021674,0.178023,0.169731,0.041660,0.179175
348,0.086189,0.099595,0.208509,0.223474,0.147729,0.282542,0.147193,0.246398,0.118994,0.106867,...,0.106867,0.222228,0.201563,0.198722,0.213262,0.071146,0.197956,0.217052,0.069226,0.191723
90,0.191218,0.141493,0.037392,0.096175,0.052813,0.405007,0.053767,0.175671,0.103540,0.093045,...,0.093045,0.050720,0.062884,0.118672,0.173047,0.203163,0.034622,0.100573,0.221581,0.019315
106,0.157690,0.107319,0.031255,0.050465,0.045394,0.359721,0.045202,0.122933,0.071378,0.079594,...,0.079594,0.039741,0.017571,0.064360,0.118612,0.173684,0.023806,0.051101,0.193915,0.035193
174,0.102930,0.058744,0.101662,0.123113,0.041552,0.324899,0.040873,0.169155,0.032747,0.100000,...,9999.000000,0.115404,0.096561,0.110371,0.146662,0.111799,0.091106,0.118860,0.129237,0.085836
16,0.197372,0.147053,0.015521,0.052465,0.075907,0.395580,0.076204,0.135515,0.110925,0.115404,...,0.115404,9999.000000,0.030873,0.087281,0.141671,0.213413,0.025203,0.060079,0.233602,0.038106
399,0.169196,0.119546,0.029934,0.034801,0.062896,0.364710,0.062733,0.112936,0.085434,0.096561,...,0.096561,0.030873,9999.000000,0.058752,0.113807,0.186237,0.028327,0.037785,0.206770,0.044100
255,0.142655,0.101338,0.088676,0.042957,0.096530,0.314316,0.095730,0.061409,0.083098,0.110371,...,0.110371,0.087281,0.058752,9999.000000,0.055073,0.163080,0.085612,0.032501,0.183912,0.099360
154,0.139313,0.114769,0.143738,0.092765,0.144395,0.271478,0.143429,0.038277,0.114532,0.146662,...,0.146662,0.141671,0.113807,0.055073,9999.000000,0.160981,0.140547,0.083056,0.180095,0.153799
394,0.021674,0.066696,0.202854,0.197906,0.150352,0.222918,0.149409,0.197812,0.102859,0.111799,...,0.111799,0.213413,0.186237,0.163080,0.160981,9999.000000,0.192865,0.189209,0.020934,0.192557
26,0.178023,0.127390,0.010557,0.061770,0.050893,0.383178,0.051247,0.141248,0.090018,0.091106,...,0.091106,0.025203,0.028327,0.085612,0.140547,0.192865,9999.000000,0.065952,0.212637,0.016483
52,0.169731,0.124375,0.065635,0.010457,0.093681,0.346786,0.093202,0.076029,0.098129,0.118860,...,0.118860,0.060079,0.037785,0.032501,0.083056,0.189209,0.065952,9999.000000,0.210143,0.081885
209,0.041660,0.087322,0.222732,0.218827,0.168872,0.215249,0.167969,0.217339,0.122785,0.129237,...,0.129237,0.233602,0.206770,0.183912,0.180095,0.020934,0.212637,0.210143,9999.000000,0.211704
29,0.179175,0.128772,0.022770,0.078127,0.044289,0.389424,0.044966,0.156570,0.090715,0.085836,...,0.085836,0.038106,0.044100,0.099360,0.153799,0.192557,0.016483,0.081885,0.211704,9999.000000

,395,240,371,372,181,259,210,72,81,31,...,365,304,128,426,48,275,256,39,355,397
395,9999.000000,0.120088,0.142655,0.146467,0.116648,0.041054,0.089083,0.044979,0.118672,0.131465,...,0.158863,0.024325,0.136939,0.148163,0.104350,0.128346,0.128346,16.573549,0.009327,0.095730
240,0.120088,9999.000000,0.034673,0.038753,0.109901,0.146038,0.094909,0.110866,0.156747,0.164631,...,0.046189,0.095997,0.175259,0.037795,0.116131,0.015765,0.015765,16.601393,0.111470,0.103085
371,0.142655,0.034673,9999.000000,0.004251,0.144459,0.161628,0.129319,0.141104,0.191218,0.199258,...,0.016473,0.118418,0.209853,0.005756,0.150766,0.019073,0.019073,16.633772,0.133481,0.137646
372,0.146467,0.038753,0.004251,9999.000000,0.148427,0.164888,0.133492,0.145311,0.195383,0.203375,...,0.013351,0.122262,0.213985,0.003986,0.154878,0.023245,0.023245,16.637113,0.137272,0.141787
181,0.116648,0.109901,0.144459,0.148427,9999.000000,0.157668,0.028426,0.073275,0.054504,0.058308,...,0.153645,0.107560,0.069344,0.146973,0.017614,0.125665,0.125665,16.495582,0.114896,0.020930
259,0.041054,0.146038,0.161628,0.164888,0.157668,9999.000000,0.129949,0.085747,0.157060,0.169884,...,0.178081,0.055831,0.174340,0.167374,0.145339,0.150796,0.150796,16.602517,0.043704,0.136761
210,0.089083,0.094909,0.129319,0.133492,0.028426,0.129949,9999.000000,0.047491,0.061910,0.070572,...,0.140740,0.079137,0.080854,0.132703,0.023274,0.110250,0.110250,16.518618,0.086818,0.009598
72,0.044979,0.110866,0.141104,0.145311,0.073275,0.085747,0.047491,9999.000000,0.076019,0.088559,...,0.155707,0.045052,0.095295,0.145833,0.059739,0.123428,0.123428,16.537095,0.045778,0.052484
81,0.118672,0.156747,0.191218,0.195383,0.054504,0.157060,0.061910,0.076019,9999.000000,0.012829,...,0.202384,0.120791,0.019989,0.194539,0.041601,0.172146,0.172146,16.462919,0.121218,0.053767
31,0.131465,0.164631,0.199258,0.203375,0.058308,0.169884,0.070572,0.088559,0.012829,9999.000000,...,0.209791,0.133161,0.011037,0.202334,0.048503,0.180204,0.180204,16.451374,0.133909,0.061729
5,0.079556,0.129578,0.162831,0.167077,0.053091,0.118964,0.039947,0.036315,0.039708,0.052301,...,0.175754,0.081196,0.059060,0.166850,0.035680,0.144057,0.144057,16.501580,0.081640,0.037489
331,0.024325,0.095997,0.118418,0.122262,0.107560,0.055831,0.079137,0.045052,0.120791,0.133161,...,0.134587,0.100000,0.140253,0.123902,0.098271,0.104026,0.104026,16.582006,0.015473,0.087331
112,0.048371,0.136348,0.165973,0.170150,0.088299,0.083793,0.066871,0.025681,0.073782,0.086541,...,0.180844,0.059887,0.090566,0.170828,0.072034,0.148598,0.148598,16.525305,0.053732,0.069078
312,0.042819,0.141688,0.156081,0.159252,0.158675,0.007631,0.130663,0.087796,0.160570,0.173398,...,0.172501,0.054352,0.178237,0.161835,0.146983,0.145821,0.145821,16.608637,0.043854,0.137847
284,0.134836,0.090767,0.123476,0.127032,0.035737,0.174538,0.049720,0.096534,0.089770,0.092035,...,0.129722,0.120039,0.102939,0.124842,0.052306,0.105972,0.105972,16.510668,0.130840,0.048475
295,0.042619,0.125060,0.137995,0.141084,0.152490,0.025423,0.124095,0.085362,0.160684,0.173411,...,0.154372,0.045080,0.179269,0.143751,0.142441,0.128355,0.128355,16.615540,0.039596,0.132065
344,0.077432,0.061105,0.070537,0.073713,0.130153,0.091199,0.104758,0.091969,0.160769,0.171808,...,0.086952,0.055030,0.180753,0.076292,0.127836,0.061595,0.061595,16.622837,0.068139,0.114350
69,0.100116,0.176552,0.209021,0.213270,0.094414,0.131097,0.087687,0.070941,0.049284,0.058106,...,0.222572,0.112003,0.055653,0.213316,0.077344,0.190546,0.190546,16.473575,0.106096,0.083714
137,0.072360,0.180803,0.208537,0.212613,0.129879,0.088864,0.111976,0.071835,0.099218,0.110209,...,0.224013,0.093461,0.109659,0.213676,0.112512,0.192051,0.192051,16.514604,0.081197,0.112629
51,0.094089,0.172260,0.204458,0.208705,0.093225,0.125162,0.084772,0.065602,0.050956,0.060693,...,0.218185,0.106176,0.059206,0.208826,0.075895,0.186084,0.186084,16.479612,0.100110,0.081370
171,0.092654,0.074224,0.108808,0.112940,0.039182,0.132004,0.021240,0.057742,0.082601,0.090467,...,0.119791,0.077484,0.101045,0.111991,0.042023,0.089746,0.089746,16.534666,0.088328,0.028867
348,0.198722,0.083909,0.086189,0.086159,0.141373,0.228630,0.143221,0.177907,0.195872,0.198855,...,0.076826,0.175745,0.209783,0.082173,0.155774,0.084862,0.084862,16.582813,0.190921,0.147193
79,0.114245,0.134833,0.169478,0.173584,0.030042,0.154619,0.041471,0.069355,0.024467,0.029850,...,0.179942,0.111454,0.040677,0.172511,0.018730,0.150436,0.150436,16.477854,0.114920,0.032256
328,0.085339,0.082473,0.116763,0.120951,0.037562,0.125486,0.012781,0.047900,0.074563,0.083352,...,0.128455,0.072328,0.093611,0.120244,0.035789,0.097706,0.097706,16.530845,0.081832,0.022024
63,0.064223,0.172662,0.200230,0.204300,0.124693,0.082620,0.105676,0.064243,0.097125,0.108603,...,0.215737,0.085115,0.108889,0.205382,0.107519,0.183805,0.183805,16.520168,0.072983,0.106835
50,0.023779,0.137166,0.162415,0.166374,0.113598,0.052793,0.088408,0.040919,0.104989,0.117766,...,0.178320,0.045085,0.121756,0.167760,0.098876,0.146952,0.146952,16.552733,0.032405,0.093053
317,0.108697,0.100192,0.134831,0.138848,0.010705,0.149567,0.019619,0.066533,0.060413,0.065879,...,0.144497,0.098303,0.076849,0.137523,0.019427,0.115935,0.115935,16.506183,0.106388,0.014830
392,0.106619,0.044628,0.079175,0.083160,0.065288,0.141786,0.052980,0.081819,0.113791,0.120881,...,0.088926,0.086097,0.131675,0.081799,0.072494,0.060393,0.060393,16.558184,0.100035,0.060104
28,0.042878,0.133067,0.162164,0.166321,0.090018,0.078861,0.067330,0.023336,0.078356,0.091156,...,0.177200,0.054556,0.095498,0.167093,0.074222,0.145004,0.145004,16.530843,0.048185,0.070279
402,0.021999,0.110394,0.136922,0.140973,0.094707,0.063051,0.067343,0.023433,0.098802,0.111473,...,0.152544,0.025351,0.117696,0.142122,0.082384,0.120796,0.120796,16.557776,0.022457,0.073780
365,0.158863,0.046189,0.016473,0.013351,0.153645,0.178081,0.140740,0.155707,0.202384,0.209791,...,9999.000000,0.134587,0.220553,0.010770,0.161348,0.032281,0.032281,16.637863,0.149725,0.148621
304,0.024325,0.095997,0.118418,0.122262,0.107560,0.055831,0.079137,0.045052,0.120791,0.133161,...,0.134587,9999.000000,0.140253,0.123902,0.098271,0.104026,0.104026,16.582006,0.015473,0.087331
128,0.136939,0.175259,0.209853,0.213985,0.069344,0.174340,0.080854,0.095295,0.019989,0.011037,...,0.220553,0.140253,9999.000000,0.212999,0.059206,0.190788,0.190788,16.442993,0.140001,0.072219
426,0.148163,0.037795,0.005756,0.003986,0.146973,0.167374,0.132703,0.145833,0.194539,0.202334,...,0.010770,0.123902,0.212999,9999.000000,0.153832,0.022798,0.022798,16.634574,0.139011,0.140857
48,0.104350,0.116131,0.150766,0.154878,0.017614,0.145339,0.023274,0.059739,0.041601,0.048503,...,0.161348,0.098271,0.059206,0.153832,9999.000000,0.131719,0.131719,16.495364,0.103704,0.013768
275,0.128346,0.015765,0.019073,0.023245,0.125665,0.150796,0.110250,0.123428,0.172146,0.180204,...,0.032281,0.104026,0.190788,0.022798,0.131719,9999.000000,0.100000,16.616633,0.119381,0.118577
256,0.128346,0.015765,0.019073,0.023245,0.125665,0.150796,0.110250,0.123428,0.172146,0.180204,...,0.032281,0.104026,0.190788,0.022798,0.131719,0.100000,9999.000000,16.616633,0.119381,0.118577
39,16.573549,16.601393,16.633772,16.637113,16.495582,16.602517,16.518618,16.537095,16.462919,16.451374,...,16.637863,16.582006,16.442993,16.634574,16.495364,16.616633,16.616633,9999.000000,16.578877,16.509040
355,0.009327,0.111470,0.133481,0.137272,0.114896,0.043704,0.086818,0.045778,0.121218,0.133909,...,0.149725,0.015473,0.140001,0.139011,0.103704,0.119381,0.119381,16.578877,9999.000000,0.094122
397,0.095730,0.103085,0.137646,0.141787,0.020930,0.136761,0.009598,0.052484,0.053767,0.061729,...,0.148621,0.087331,0.072219,0.140857,0.013768,0.118577,0.118577,16.509040,0.094122,9999.000000

,277,282,359,258,223,29,294,49,142,318,...,321,117,393,25,159,343,91,182,105,42
277,9999.000000,0.101269,0.063355,0.046190,0.026131,0.136900,0.117808,0.131862,0.161508,0.057721,...,0.105157,0.086097,0.060597,0.167300,0.097612,0.069982,0.118011,0.030910,0.131547,0.117032
282,0.101269,9999.000000,0.150427,0.060408,0.079837,0.056736,0.162512,0.057577,0.065380,0.116465,...,0.004433,0.091143,0.148632,0.072330,0.131708,0.165643,0.016742,0.112708,0.036605,0.067151
359,0.063355,0.150427,9999.000000,0.106270,0.088478,0.195214,0.168045,0.191171,0.215027,0.113596,...,0.154785,0.149080,0.002982,0.221544,0.154427,0.023427,0.166409,0.085130,0.185065,0.179080
258,0.046190,0.060408,0.106270,9999.000000,0.020870,0.090715,0.114532,0.085802,0.116200,0.059611,...,0.063612,0.056246,0.103804,0.121710,0.086205,0.115828,0.076628,0.052303,0.086580,0.073070
223,0.026131,0.079837,0.088478,0.020870,9999.000000,0.111148,0.109388,0.105912,0.137066,0.049825,...,0.083335,0.063959,0.085840,0.142577,0.084298,0.096113,0.096372,0.034296,0.107400,0.091004
29,0.136900,0.056736,0.195214,0.090715,0.111148,9999.000000,0.153799,0.008192,0.036134,0.127370,...,0.053090,0.084045,0.192969,0.037921,0.124250,0.206395,0.051160,0.136180,0.027161,0.035374
294,0.117808,0.162512,0.168045,0.114532,0.109388,0.153799,9999.000000,0.145621,0.189820,0.060622,...,0.163677,0.072754,0.165096,0.191544,0.030946,0.160003,0.174447,0.087338,0.169163,0.118455
49,0.131862,0.057577,0.191171,0.085802,0.105912,0.008192,0.145621,9999.000000,0.044322,0.120048,...,0.054340,0.076113,0.188855,0.046021,0.116127,0.201630,0.054336,0.129795,0.032429,0.027185
142,0.161508,0.065380,0.215027,0.116200,0.137066,0.036134,0.189820,0.044322,9999.000000,0.160293,...,0.060946,0.119262,0.213096,0.007425,0.160052,0.228948,0.051357,0.165698,0.030110,0.071484
318,0.057721,0.116465,0.113596,0.059611,0.049825,0.127370,0.060622,0.120048,0.160293,9999.000000,...,0.118807,0.048459,0.110617,0.164109,0.040921,0.110784,0.131221,0.028695,0.133833,0.096324
336,0.080869,0.035587,0.139121,0.034770,0.055557,0.056313,0.126925,0.052062,0.081885,0.082977,...,0.036940,0.055937,0.136821,0.087154,0.096129,0.150112,0.048629,0.084149,0.052840,0.045530
130,0.120389,0.094384,0.183744,0.082833,0.096074,0.064004,0.093080,0.055981,0.099841,0.085099,...,0.093320,0.037150,0.180977,0.100428,0.066395,0.187800,0.099703,0.105388,0.085287,0.030340
406,0.031296,0.078129,0.094079,0.017921,0.005860,0.106862,0.105438,0.101400,0.133677,0.046732,...,0.081431,0.058143,0.091414,0.139015,0.079610,0.101158,0.094462,0.034710,0.104245,0.085743
259,0.133742,0.157360,0.189831,0.119195,0.119613,0.137832,0.031905,0.129716,0.173815,0.076787,...,0.157668,0.066924,0.186849,0.174442,0.036131,0.184592,0.166869,0.105459,0.157076,0.103018
219,0.063355,0.150427,0.100000,0.106270,0.088478,0.195214,0.168045,0.191171,0.215027,0.113596,...,0.154785,0.149080,0.002982,0.221544,0.154427,0.023427,0.166409,0.085130,0.185065,0.179080
299,0.097612,0.131708,0.154427,0.086205,0.084298,0.124250,0.030946,0.116127,0.160052,0.040921,...,0.132799,0.041903,0.151446,0.162147,0.100000,0.150494,0.143506,0.069607,0.138542,0.089137
200,0.059797,0.058447,0.121523,0.016296,0.033667,0.078421,0.107016,0.072728,0.106906,0.058075,...,0.060732,0.042442,0.118974,0.111805,0.077163,0.129776,0.073203,0.058793,0.078364,0.057563
356,0.136796,0.157018,0.193587,0.120647,0.121907,0.135666,0.037116,0.127595,0.171531,0.080254,...,0.157179,0.067274,0.190605,0.171959,0.039367,0.188757,0.166081,0.108948,0.155538,0.101135
415,0.008201,0.094186,0.071105,0.038090,0.017933,0.128772,0.114769,0.123691,0.153714,0.054196,...,0.097984,0.078982,0.068394,0.159435,0.093009,0.078183,0.110912,0.029815,0.123814,0.108876
266,0.031296,0.078129,0.094079,0.017921,0.005860,0.106862,0.105438,0.101400,0.133677,0.046732,...,0.081431,0.058143,0.091414,0.139015,0.079610,0.101158,0.094462,0.034710,0.104245,0.085743
5,0.120392,0.055525,0.180687,0.074669,0.094311,0.020860,0.133504,0.013165,0.056381,0.106892,...,0.053091,0.063202,0.178293,0.058700,0.103674,0.190329,0.056215,0.117091,0.039009,0.016055
137,0.169051,0.132119,0.232378,0.131343,0.144950,0.084466,0.117721,0.078998,0.113170,0.129004,...,0.129879,0.083964,0.229584,0.110461,0.099920,0.235584,0.132527,0.152188,0.111296,0.065804
417,0.100000,0.101269,0.063355,0.046190,0.026131,0.136900,0.117808,0.131862,0.161508,0.057721,...,0.105157,0.086097,0.060597,0.167300,0.097612,0.069982,0.118011,0.030910,0.131547,0.117032
302,0.059797,0.058447,0.121523,0.016296,0.033667,0.078421,0.107016,0.072728,0.106906,0.058075,...,0.060732,0.042442,0.118974,0.111805,0.077163,0.129776,0.073203,0.058793,0.078364,0.057563
304,0.083507,0.106450,0.144620,0.063364,0.065372,0.102030,0.056123,0.094075,0.137259,0.035543,...,0.107560,0.018004,0.141687,0.139891,0.025258,0.144456,0.118367,0.060489,0.114386,0.067830
90,0.149460,0.058791,0.205238,0.103540,0.124358,0.019315,0.173047,0.027504,0.016818,0.144772,...,0.054504,0.102787,0.203162,0.019344,0.143365,0.217983,0.047975,0.151593,0.022414,0.054672
289,0.119984,0.166523,0.169109,0.117981,0.112319,0.158126,0.004329,0.149949,0.194144,0.063181,...,0.167729,0.076962,0.166172,0.195873,0.035101,0.160499,0.178561,0.089343,0.173429,0.122783
52,0.131559,0.114344,0.194527,0.098129,0.108837,0.081885,0.083056,0.074139,0.117004,0.088754,...,0.113334,0.045471,0.191671,0.116842,0.061026,0.196448,0.119692,0.112643,0.104567,0.049877
340,0.059797,0.058447,0.121523,0.016296,0.033667,0.078421,0.107016,0.072728,0.106906,0.058075,...,0.060732,0.042442,0.118974,0.111805,0.077163,0.129776,0.073203,0.058793,0.078364,0.057563
0,0.119206,0.032424,0.174820,0.073541,0.094409,0.024324,0.154486,0.025721,0.042810,0.118988,...,0.028876,0.081923,0.172724,0.048170,0.123783,0.187515,0.029073,0.122975,0.014993,0.042637
321,0.105157,0.004433,0.154785,0.063612,0.083335,0.053090,0.163677,0.054340,0.060946,0.118807,...,9999.000000,0.091851,0.152977,0.067900,0.132799,0.169884,0.013041,0.115897,0.032252,0.065413
117,0.086097,0.091143,0.149080,0.056246,0.063959,0.084045,0.072754,0.076113,0.119262,0.048459,...,0.091851,9999.000000,0.146232,0.121893,0.041903,0.151620,0.102052,0.068469,0.096737,0.050101
393,0.060597,0.148632,0.002982,0.103804,0.085840,0.192969,0.165096,0.188855,0.213096,0.110617,...,0.152977,0.146232,9999.000000,0.219575,0.151446,0.022820,0.164688,0.082158,0.183102,0.176536
25,0.167300,0.072330,0.221544,0.121710,0.142577,0.037921,0.191544,0.046021,0.007425,0.164109,...,0.067900,0.121893,0.219575,9999.000000,0.162147,0.235142,0.058624,0.170538,0.036480,0.073106
159,0.097612,0.131708,0.154427,0.086205,0.084298,0.124250,0.030946,0.116127,0.160052,0.040921,...,0.132799,0.041903,0.151446,0.162147,9999.000000,0.150494,0.143506,0.069607,0.138542,0.089137
343,0.069982,0.165643,0.023427,0.115828,0.096113,0.206395,0.160003,0.201630,0.228948,0.110784,...,0.169884,0.151620,0.022820,0.235142,0.150494,9999.000000,0.182064,0.083995,0.198838,0.186850
91,0.118011,0.016742,0.166409,0.076628,0.096372,0.051160,0.174447,0.054336,0.051357,0.131221,...,0.013041,0.102052,0.164688,0.058624,0.143506,0.182064,9999.000000,0.128897,0.025908,0.070367
182,0.030910,0.112708,0.085130,0.052303,0.034296,0.136180,0.087338,0.129795,0.165698,0.028695,...,0.115897,0.068469,0.082158,0.170538,0.069607,0.083995,0.128897,9999.000000,0.136988,0.109760
105,0.131547,0.036605,0.185065,0.086580,0.107400,0.027161,0.169163,0.032429,0.030110,0.133833,...,0.032252,0.096737,0.183102,0.036480,0.138542,0.198838,0.025908,0.136988,9999.000000,0.054955
42,0.117032,0.067151,0.179080,0.073070,0.091004,0.035374,0.118455,0.027185,0.071484,0.096324,...,0.065413,0.050101,0.176536,0.073106,0.089137,0.186850,0.070367,0.109760,0.054955,9999.000000

,234,109,210,24,208,238,39,272,371,394,...,123,216,396,199,307,314,192,120,101,315
234,9999.000000,0.137637,0.135207,0.175059,0.070615,0.130553,16.630368,0.112986,0.017660,0.006598,...,0.162025,0.181805,0.060203,0.097524,0.144925,0.105454,0.244535,0.196904,0.233940,0.193056
109,0.137637,9999.000000,0.063638,0.071740,0.173637,0.009197,16.564254,0.071892,0.124626,0.143831,...,0.071949,0.067274,0.078982,0.051104,0.079696,0.082955,0.253405,0.059308,0.114567,0.087420
210,0.135207,0.063638,9999.000000,0.041428,0.143221,0.067733,16.518618,0.024217,0.129319,0.141766,...,0.026889,0.129708,0.079682,0.043893,0.016933,0.036364,0.189969,0.096305,0.101120,0.150410
24,0.175059,0.071740,0.041428,9999.000000,0.184046,0.079672,16.493423,0.065621,0.167707,0.181653,...,0.016527,0.125720,0.117160,0.079175,0.040777,0.077348,0.202696,0.074077,0.059720,0.146772
208,0.070615,0.173637,0.143221,0.184046,9999.000000,0.169378,16.582813,0.119281,0.086189,0.071146,...,0.168038,0.231376,0.099595,0.123316,0.145075,0.106867,0.187669,0.228701,0.242879,0.246398
238,0.130553,0.009197,0.067733,0.079672,0.169378,9999.000000,16.572714,0.073018,0.117036,0.136646,...,0.078677,0.066743,0.072876,0.048653,0.084286,0.083193,0.256521,0.066979,0.123723,0.085975
39,16.630368,16.564254,16.518618,16.493423,16.582813,16.572714,9999.000000,16.532283,16.633772,16.635388,...,16.497719,16.598333,16.592771,16.562007,16.503088,16.534149,16.395993,16.533757,16.454981,16.614726
272,0.112986,0.071892,0.024217,0.065621,0.119281,0.073018,16.532283,9999.000000,0.108656,0.119473,...,0.050565,0.139088,0.061175,0.032597,0.032053,0.013026,0.185090,0.115158,0.125267,0.158865
371,0.017660,0.124626,0.129319,0.167707,0.086189,0.117036,16.633772,0.108656,9999.000000,0.021674,...,0.155738,0.165506,0.050637,0.088781,0.140667,0.102930,0.253184,0.183890,0.225605,0.176154
394,0.006598,0.143831,0.141766,0.181653,0.071146,0.136646,16.635388,0.119473,0.021674,9999.000000,...,0.168593,0.186974,0.066696,0.104099,0.151384,0.111799,0.248197,0.203122,0.240537,0.197812
273,0.026622,0.161545,0.161822,0.201567,0.079583,0.153996,16.652790,0.139579,0.036963,0.020106,...,0.188629,0.200940,0.085853,0.123631,0.171486,0.131838,0.262736,0.220827,0.260298,0.210369
175,0.193056,0.087420,0.150410,0.146772,0.246398,0.085975,16.614726,0.158865,0.176154,0.197812,...,0.153050,0.021148,0.146857,0.133368,0.165676,0.169155,0.340369,0.083492,0.163898,0.100000
204,0.087325,0.067666,0.104758,0.131335,0.144710,0.058548,16.622837,0.095608,0.070537,0.092153,...,0.125280,0.095212,0.049953,0.063238,0.121003,0.098827,0.275377,0.122981,0.181196,0.105731
87,0.136714,0.041187,0.023022,0.041096,0.155395,0.046286,16.531996,0.038745,0.128028,0.143301,...,0.034324,0.106708,0.077414,0.039315,0.038534,0.051683,0.212914,0.076422,0.097577,0.127456
339,0.097524,0.051104,0.043893,0.079175,0.123316,0.048653,16.562007,0.032597,0.088781,0.104099,...,0.068473,0.114995,0.038144,0.100000,0.058919,0.038301,0.216311,0.105715,0.136866,0.133368
41,0.204410,0.066805,0.102437,0.078058,0.235952,0.074420,16.530311,0.121825,0.191368,0.210626,...,0.090827,0.068022,0.145280,0.113072,0.111835,0.134762,0.280746,0.007510,0.078751,0.085516
426,0.012367,0.129821,0.132703,0.171541,0.082173,0.122332,16.634574,0.111549,0.005756,0.015935,...,0.159268,0.171244,0.054785,0.092871,0.143600,0.105269,0.252057,0.189113,0.229736,0.181908
357,0.158320,0.044673,0.108247,0.110111,0.206348,0.042609,16.594120,0.115574,0.142450,0.163702,...,0.113846,0.025155,0.106980,0.090229,0.124068,0.125778,0.298078,0.062910,0.139145,0.043377
342,0.029077,0.108560,0.109971,0.148578,0.084376,0.101524,16.616153,0.089336,0.019369,0.035342,...,0.136436,0.154574,0.031875,0.069902,0.121327,0.083923,0.239747,0.167827,0.206763,0.166992
137,0.221109,0.083964,0.111976,0.081729,0.249632,0.092005,16.514604,0.133120,0.208537,0.227406,...,0.096407,0.084308,0.161492,0.127802,0.119158,0.146146,0.282651,0.025517,0.068201,0.100182
58,0.181007,0.043391,0.087218,0.071928,0.214793,0.050743,16.544968,0.103963,0.167758,0.187177,...,0.081298,0.056666,0.122248,0.091493,0.099139,0.116592,0.272389,0.016424,0.090091,0.076918
3,0.227728,0.109086,0.094934,0.053523,0.236835,0.118216,16.459378,0.119094,0.219433,0.234325,...,0.068901,0.141703,0.168812,0.130683,0.091941,0.130569,0.227736,0.077211,0.006223,0.160691
185,0.120856,0.099669,0.042116,0.077645,0.109907,0.101210,16.514409,0.028293,0.120538,0.126905,...,0.061119,0.166943,0.079407,0.059275,0.036916,0.021715,0.157156,0.138379,0.134267,0.186913
373,0.073694,0.077894,0.061564,0.101515,0.095785,0.074089,16.570477,0.040400,0.068293,0.080270,...,0.088340,0.138567,0.022658,0.027892,0.072377,0.036329,0.207481,0.133594,0.160758,0.155580
184,0.088559,0.063533,0.100517,0.126920,0.144296,0.054449,16.618489,0.091759,0.072084,0.093590,...,0.120900,0.093423,0.048107,0.059296,0.116819,0.095297,0.272234,0.119319,0.176879,0.104704
198,0.181261,0.067721,0.130323,0.126712,0.231168,0.067002,16.599723,0.139482,0.164911,0.186400,...,0.132768,0.001425,0.131657,0.115148,0.145465,0.150101,0.320238,0.066307,0.146563,0.020302
141,0.171160,0.033713,0.076451,0.064422,0.203671,0.041824,16.544806,0.092714,0.158329,0.177401,...,0.072287,0.061559,0.111966,0.080421,0.088938,0.105307,0.262929,0.025809,0.090094,0.082484
89,0.167860,0.030748,0.082411,0.074184,0.203910,0.037319,16.555402,0.096599,0.154300,0.173964,...,0.080927,0.051536,0.109669,0.080756,0.095979,0.108794,0.270650,0.030461,0.100548,0.072611
71,0.211254,0.090877,0.080519,0.039568,0.223542,0.100003,16.476767,0.104713,0.202444,0.217845,...,0.055921,0.126028,0.151903,0.113873,0.079954,0.116737,0.228212,0.062710,0.023900,0.145606
367,0.021008,0.145688,0.133760,0.174785,0.049608,0.139487,16.616174,0.110226,0.037231,0.022245,...,0.160585,0.195173,0.066710,0.100774,0.141289,0.100795,0.226789,0.204303,0.234382,0.207824
123,0.162025,0.071949,0.026889,0.016527,0.168038,0.078677,16.497719,0.050565,0.155738,0.168593,...,9999.000000,0.131904,0.105642,0.068473,0.024258,0.061692,0.191169,0.086032,0.075013,0.153050
216,0.181805,0.067274,0.129708,0.125720,0.231376,0.066743,16.598333,0.139088,0.165506,0.186974,...,0.131904,9999.000000,0.131901,0.114995,0.144779,0.149778,0.319591,0.064957,0.145241,0.021148
396,0.060203,0.078982,0.079682,0.117160,0.099595,0.072876,16.592771,0.061175,0.050637,0.066696,...,0.105642,0.131901,9999.000000,0.038144,0.092435,0.058744,0.228609,0.137775,0.174990,0.146857
199,0.097524,0.051104,0.043893,0.079175,0.123316,0.048653,16.562007,0.032597,0.088781,0.104099,...,0.068473,0.114995,0.038144,9999.000000,0.058919,0.038301,0.216311,0.105715,0.136866,0.133368
307,0.144925,0.079696,0.016933,0.040777,0.145075,0.084286,16.503088,0.032053,0.140667,0.151384,...,0.024258,0.144779,0.092435,0.058919,9999.000000,0.040579,0.174917,0.106334,0.097916,0.165676
314,0.105454,0.082955,0.036364,0.077348,0.106867,0.083193,16.534149,0.013026,0.102930,0.111799,...,0.061692,0.149778,0.058744,0.038301,0.040579,9999.000000,0.178104,0.128048,0.136697,0.169155
192,0.244535,0.253405,0.189969,0.202696,0.187669,0.256521,16.395993,0.185090,0.253184,0.248197,...,0.191169,0.319591,0.228609,0.216311,0.174917,0.178104,9999.000000,0.276651,0.230769,0.340369
120,0.196904,0.059308,0.096305,0.074077,0.228701,0.066979,16.533757,0.115158,0.183890,0.203122,...,0.086032,0.064957,0.137775,0.105715,0.106334,0.128048,0.276651,9999.000000,0.080445,0.083492
101,0.233940,0.114567,0.101120,0.059720,0.242879,0.123723,16.454981,0.125267,0.225605,0.240537,...,0.075013,0.145241,0.174990,0.136866,0.097916,0.136697,0.230769,0.080445,9999.000000,0.163898
315,0.193056,0.087420,0.150410,0.146772,0.246398,0.085975,16.614726,0.158865,0.176154,0.197812,...,0.153050,0.021148,0.146857,0.133368,0.165676,0.169155,0.340369,0.083492,0.163898,9999.000000

,395,124,275,324,34,187,388,298,414,330,...,0,359,254,255,270,213,170,95,138,323
395,9999.000000,0.101856,0.128346,0.074121,0.046172,0.060541,0.039239,0.161187,0.029898,0.024325,...,0.102687,0.168944,0.163080,0.100000,0.009596,0.110648,0.047675,0.135801,0.127695,0.050131
124,0.101856,9999.000000,0.125277,0.117960,0.076385,0.151370,0.141050,0.150524,0.106839,0.094462,...,0.017868,0.157448,0.155516,0.101856,0.104060,0.060510,0.138248,0.076371,0.064783,0.100025
275,0.128346,0.125277,9999.000000,0.062071,0.150248,0.123064,0.147602,0.032874,0.102498,0.104026,...,0.141737,0.040682,0.035356,0.128346,0.120706,0.068025,0.118156,0.200268,0.188689,0.079190
324,0.074121,0.117960,0.062071,9999.000000,0.108543,0.061754,0.086362,0.093015,0.044810,0.051339,...,0.129317,0.100302,0.093590,0.074121,0.065068,0.084567,0.056087,0.181332,0.170654,0.025812
34,0.046172,0.076385,0.150248,0.108543,9999.000000,0.106711,0.079890,0.182328,0.070840,0.059237,...,0.069933,0.190156,0.185509,0.046172,0.054352,0.110346,0.093805,0.090905,0.083834,0.082755
187,0.060541,0.151370,0.123064,0.061754,0.106711,9999.000000,0.040067,0.152265,0.044531,0.057157,...,0.156589,0.159036,0.151882,0.060541,0.053005,0.137765,0.013476,0.195682,0.187047,0.058023
388,0.039239,0.141050,0.147602,0.086362,0.079890,0.040067,9999.000000,0.179272,0.047377,0.053092,...,0.141729,0.186630,0.179952,0.039239,0.038089,0.144248,0.034175,0.170756,0.163643,0.070341
298,0.161187,0.150524,0.032874,0.093015,0.182328,0.152265,0.179272,9999.000000,0.134962,0.136863,...,0.167799,0.007852,0.006032,0.161187,0.153458,0.090387,0.148656,0.226699,0.215080,0.111808
414,0.029898,0.106839,0.102498,0.044810,0.070840,0.044531,0.047377,0.134962,9999.000000,0.013238,...,0.112476,0.142570,0.136312,0.029898,0.020486,0.098445,0.031536,0.154969,0.145593,0.023504
330,0.024325,0.094462,0.104026,0.051339,0.059237,0.057157,0.053092,0.136863,0.013238,9999.000000,...,0.099494,0.144620,0.138768,0.024325,0.017362,0.091184,0.043868,0.141845,0.132401,0.026257
171,0.092654,0.035592,0.089746,0.087569,0.084430,0.130772,0.129561,0.115886,0.087601,0.077484,...,0.052120,0.123032,0.120676,0.092654,0.091524,0.028280,0.118632,0.110938,0.099321,0.074400
46,0.070769,0.116864,0.192004,0.143762,0.044854,0.123775,0.086741,0.224578,0.100570,0.092433,...,0.106447,0.232429,0.227357,0.070769,0.080346,0.155200,0.113217,0.104490,0.102078,0.118488
93,0.109715,0.033698,0.157715,0.143061,0.071701,0.166212,0.148020,0.183891,0.122840,0.109650,...,0.016092,0.190907,0.188779,0.109715,0.114604,0.094157,0.152743,0.042809,0.031191,0.121762
84,0.135941,0.090517,0.211806,0.187973,0.089869,0.196450,0.168431,0.239459,0.157893,0.145082,...,0.072664,0.246666,0.244119,0.135941,0.143664,0.150616,0.183388,0.018791,0.027775,0.163795
390,0.085390,0.079266,0.051527,0.047140,0.099830,0.101952,0.113677,0.082707,0.066375,0.062454,...,0.094024,0.090495,0.086227,0.085390,0.079776,0.037471,0.092285,0.151276,0.139844,0.044862
343,0.168499,0.170726,0.046281,0.095937,0.194831,0.150225,0.181418,0.025175,0.140301,0.144456,...,0.187515,0.023427,0.019169,0.168499,0.160003,0.111715,0.148837,0.246227,0.234627,0.118368
118,0.065265,0.049241,0.142010,0.111359,0.028001,0.123767,0.103005,0.172477,0.082362,0.069237,...,0.041954,0.180133,0.176375,0.065265,0.071075,0.091875,0.110339,0.072610,0.063384,0.086953
216,0.040627,0.142214,0.154312,0.093423,0.077844,0.047684,0.007817,0.186178,0.053072,0.057396,...,0.141911,0.193587,0.186974,0.040627,0.041277,0.148476,0.041971,0.168346,0.161655,0.076379
64,0.077025,0.097896,0.186946,0.144995,0.037050,0.135374,0.101824,0.218780,0.105044,0.094588,...,0.085540,0.226583,0.222117,0.077025,0.086341,0.142708,0.123502,0.080042,0.077550,0.119187
185,0.126740,0.042331,0.102572,0.116984,0.112819,0.164595,0.164056,0.121283,0.121955,0.112046,...,0.059055,0.127241,0.126905,0.126740,0.125987,0.035619,0.152735,0.113635,0.102535,0.107330
37,0.051691,0.050535,0.120471,0.088410,0.033869,0.105780,0.090922,0.151653,0.062445,0.049223,...,0.051421,0.159401,0.155273,0.051691,0.055036,0.076479,0.092322,0.093991,0.083964,0.064382
349,0.183912,0.173759,0.056265,0.113687,0.206289,0.170683,0.199981,0.024134,0.156906,0.159612,...,0.191190,0.016533,0.020934,0.183912,0.175906,0.113346,0.168294,0.250071,0.238458,0.134105
258,0.083098,0.058584,0.069558,0.063793,0.087723,0.111680,0.116442,0.098699,0.070989,0.063364,...,0.073541,0.106270,0.102859,0.083098,0.079607,0.027830,0.100458,0.131272,0.119769,0.053826
133,0.041500,0.113993,0.168101,0.115614,0.038166,0.092056,0.055680,0.200963,0.071251,0.065048,...,0.108094,0.208782,0.203206,0.041500,0.050764,0.140449,0.081559,0.122149,0.117048,0.091264
317,0.108697,0.014390,0.115935,0.115412,0.087910,0.154216,0.147485,0.139495,0.109924,0.098303,...,0.031644,0.146178,0.144692,0.108697,0.109746,0.049113,0.141450,0.088770,0.077315,0.100091
377,0.023233,0.124480,0.134607,0.074877,0.067266,0.041893,0.017077,0.166836,0.032439,0.036383,...,0.125861,0.174360,0.167925,0.023233,0.021020,0.127547,0.031143,0.157919,0.150199,0.055925
42,0.064013,0.049440,0.140877,0.109972,0.027430,0.122417,0.101851,0.171415,0.080960,0.067830,...,0.042637,0.179080,0.175288,0.064013,0.069756,0.091175,0.108985,0.074015,0.064762,0.085546
302,0.069823,0.051871,0.083593,0.066095,0.071429,0.105615,0.105355,0.113852,0.062436,0.052702,...,0.064197,0.121523,0.117750,0.069823,0.067587,0.041472,0.093429,0.119831,0.108545,0.049908
291,0.078381,0.172918,0.141006,0.081317,0.123942,0.022148,0.048437,0.168620,0.066237,0.078473,...,0.177485,0.174994,0.167666,0.078381,0.072083,0.159664,0.034707,0.214178,0.206016,0.080022
97,0.142317,0.079890,0.204471,0.186906,0.097524,0.202112,0.177388,0.230407,0.161192,0.148041,...,0.062777,0.237335,0.235369,0.142317,0.149133,0.140315,0.188768,0.006662,0.016290,0.164022
0,0.102687,0.017868,0.141737,0.129317,0.069933,0.156589,0.141729,0.167799,0.112476,0.099494,...,9999.000000,0.174820,0.172690,0.102687,0.106455,0.078137,0.143200,0.058901,0.047281,0.109146
359,0.168944,0.157448,0.040682,0.100302,0.190156,0.159036,0.186630,0.007852,0.142570,0.144620,...,0.174820,9999.000000,0.007479,0.168944,0.161167,0.097126,0.155739,0.233714,0.222098,0.119477
254,0.163080,0.155516,0.035356,0.093590,0.185509,0.151882,0.179952,0.006032,0.136312,0.138768,...,0.172690,0.007479,9999.000000,0.163080,0.155148,0.095583,0.148797,0.231577,0.219957,0.113376
255,0.100000,0.101856,0.128346,0.074121,0.046172,0.060541,0.039239,0.161187,0.029898,0.024325,...,0.102687,0.168944,0.163080,9999.000000,0.009596,0.110648,0.047675,0.135801,0.127695,0.050131
270,0.009596,0.104060,0.120706,0.065068,0.054352,0.053005,0.038089,0.153458,0.020486,0.017362,...,0.106455,0.161167,0.155148,0.009596,9999.000000,0.107407,0.039765,0.142689,0.134169,0.041814
213,0.110648,0.060510,0.068025,0.084567,0.110346,0.137765,0.144248,0.090387,0.098445,0.091184,...,0.078137,0.097126,0.095583,0.110648,0.107407,9999.000000,0.127130,0.136882,0.125291,0.079775
170,0.047675,0.138248,0.118156,0.056087,0.093805,0.013476,0.034175,0.148656,0.031536,0.043868,...,0.143200,0.155739,0.148797,0.047675,0.039765,0.127130,9999.000000,0.182356,0.173649,0.047563
95,0.135801,0.076371,0.200268,0.181332,0.090905,0.195682,0.170756,0.226699,0.154969,0.141845,...,0.058901,0.233714,0.231577,0.135801,0.142689,0.136882,0.182356,9999.000000,0.011620,0.158212
138,0.127695,0.064783,0.188689,0.170654,0.083834,0.187047,0.163643,0.215080,0.145593,0.132401,...,0.047281,0.222098,0.219957,0.127695,0.134169,0.125291,0.173649,0.011620,9999.000000,0.147893
323,0.050131,0.100025,0.079190,0.025812,0.082755,0.058023,0.070341,0.111808,0.023504,0.026257,...,0.109146,0.119477,0.113376,0.050131,0.041814,0.079775,0.047563,0.158212,0.147893,9999.000000

,179,41,112,33,191,158,283,166,3,297,...,253,57,403,346,295,53,46,25,186,310
179,9999.000000,0.140455,0.104932,0.030242,0.114366,0.132934,0.095094,0.008351,0.119022,0.131664,...,0.137393,0.044762,0.357404,0.156292,0.159328,0.112051,0.150894,0.087466,0.180738,0.156319
41,0.140455,9999.000000,0.035583,0.131625,0.075166,0.207958,0.082071,0.145779,0.076032,0.191368,...,0.212977,0.101321,0.368586,0.065973,0.088692,0.089870,0.017271,0.114320,0.088149,0.097266
112,0.104932,0.035583,9999.000000,0.097708,0.059887,0.180504,0.058329,0.110409,0.066385,0.165973,...,0.185609,0.067198,0.358901,0.073967,0.090877,0.075762,0.048055,0.090698,0.100183,0.095826
33,0.030242,0.131625,0.097708,9999.000000,0.122935,0.162445,0.105349,0.027234,0.095551,0.159824,...,0.167008,0.030511,0.383984,0.160213,0.167594,0.086294,0.139078,0.058332,0.186090,0.166632
191,0.114366,0.075166,0.059887,0.122935,9999.000000,0.136863,0.019658,0.122274,0.125571,0.118418,...,0.141687,0.097146,0.299072,0.045277,0.045080,0.133139,0.092433,0.139891,0.067055,0.043868
158,0.132934,0.207958,0.180504,0.162445,0.136863,9999.000000,0.125952,0.138732,0.230047,0.022390,...,0.005124,0.161865,0.232183,0.175148,0.159308,0.229394,0.224578,0.214740,0.185240,0.148656
283,0.095094,0.082071,0.058329,0.105349,0.019658,0.125952,9999.000000,0.103099,0.120147,0.109439,...,0.130951,0.081359,0.303526,0.064416,0.064254,0.125619,0.098877,0.127854,0.086713,0.061642
166,0.008351,0.145779,0.110409,0.027234,0.122274,0.138732,0.103099,9999.000000,0.120116,0.138372,...,0.143075,0.047488,0.364538,0.163794,0.167289,0.112154,0.155588,0.085531,0.188442,0.164438
3,0.119022,0.076032,0.066385,0.095551,0.125571,0.230047,0.120147,0.120116,9999.000000,0.219433,...,0.235129,0.075050,0.423526,0.136866,0.156190,0.015660,0.070938,0.049592,0.161693,0.161916
297,0.131664,0.191368,0.165973,0.159824,0.118418,0.022390,0.109439,0.138372,0.219433,9999.000000,...,0.025871,0.155081,0.226863,0.154755,0.137995,0.220180,0.208287,0.208681,0.163717,0.127131
427,0.038689,0.140672,0.106293,0.066529,0.094349,0.096493,0.074931,0.046066,0.139934,0.093372,...,0.101214,0.067028,0.318721,0.139343,0.136934,0.136619,0.154347,0.118659,0.161019,0.131617
105,0.052990,0.109033,0.077443,0.027665,0.114386,0.178273,0.099428,0.052771,0.067943,0.172554,...,0.183102,0.018879,0.392053,0.146217,0.157114,0.059384,0.114605,0.036480,0.172675,0.158028
219,0.138958,0.215809,0.188317,0.168670,0.144620,0.007852,0.133799,0.144528,0.237515,0.028784,...,0.002982,0.168863,0.229039,0.182626,0.166491,0.236684,0.232429,0.221544,0.192332,0.155739
278,0.007308,0.145388,0.109987,0.027868,0.121395,0.137710,0.102194,0.001124,0.120331,0.137288,...,0.142063,0.047430,0.363434,0.163011,0.166398,0.112496,0.155297,0.086115,0.187615,0.163502
385,0.026609,0.116642,0.081105,0.040622,0.088121,0.128662,0.069096,0.034223,0.106771,0.122969,...,0.133530,0.033527,0.344619,0.129688,0.133176,0.103058,0.128373,0.086128,0.154226,0.130636
299,0.139419,0.081241,0.076464,0.148078,0.025258,0.146962,0.044346,0.147387,0.142758,0.126552,...,0.151446,0.121758,0.287406,0.028209,0.019909,0.152015,0.097898,0.162147,0.043810,0.019849
76,0.040086,0.114615,0.081191,0.017379,0.111364,0.166462,0.095006,0.040232,0.079943,0.161514,...,0.171237,0.014770,0.382681,0.146251,0.155270,0.072084,0.121758,0.048745,0.172451,0.155231
239,0.054158,0.139939,0.107031,0.080884,0.086097,0.084460,0.067488,0.061737,0.147446,0.079175,...,0.089374,0.077407,0.303492,0.131371,0.126656,0.145594,0.154665,0.130420,0.151571,0.120421
302,0.062984,0.100915,0.068851,0.077525,0.052702,0.113852,0.033048,0.071188,0.117245,0.102193,...,0.118974,0.059492,0.314413,0.096952,0.097019,0.118569,0.115951,0.111805,0.119754,0.093429
291,0.190708,0.121109,0.126499,0.201329,0.078473,0.168620,0.096310,0.198874,0.191297,0.146308,...,0.172130,0.175437,0.257045,0.055248,0.035805,0.202056,0.135178,0.214914,0.036513,0.034707
201,0.044490,0.106174,0.072688,0.025556,0.104258,0.166216,0.088477,0.045964,0.074536,0.160145,...,0.171079,0.007129,0.379519,0.138244,0.147789,0.068010,0.113540,0.048612,0.164521,0.148085
0,0.049989,0.099092,0.065765,0.032662,0.099494,0.167799,0.084437,0.052145,0.069341,0.160810,...,0.172724,0.006047,0.378428,0.132279,0.142505,0.063943,0.106447,0.048170,0.158646,0.143200
254,0.138520,0.210626,0.183790,0.167922,0.138768,0.006032,0.128557,0.144411,0.234325,0.021674,...,0.005019,0.166781,0.226155,0.176116,0.159632,0.233950,0.227357,0.219814,0.185385,0.148797
274,0.125081,0.083386,0.071866,0.135152,0.013238,0.134962,0.030139,0.133140,0.137981,0.115308,...,0.139600,0.109972,0.287746,0.041226,0.034730,0.145948,0.100570,0.153128,0.059056,0.031536
227,0.124954,0.211797,0.182494,0.155002,0.143339,0.017090,0.130538,0.130034,0.228163,0.037231,...,0.017935,0.157491,0.246486,0.183778,0.169506,0.226355,0.228008,0.209329,0.195720,0.159309
376,0.032598,0.121825,0.086841,0.053451,0.083780,0.114491,0.064178,0.040944,0.119094,0.108656,...,0.119387,0.047418,0.330839,0.127355,0.128271,0.116268,0.134816,0.100397,0.150758,0.124574
155,0.159328,0.088692,0.090877,0.167594,0.045080,0.159308,0.064254,0.167289,0.156190,0.137995,...,0.163517,0.140757,0.281848,0.024160,0.100000,0.166566,0.104092,0.179138,0.026348,0.011720
321,0.021317,0.123346,0.088299,0.016987,0.107560,0.148282,0.089458,0.023479,0.097710,0.144459,...,0.152977,0.024020,0.367670,0.146425,0.152490,0.090868,0.132556,0.067900,0.171914,0.150999
428,0.199949,0.209409,0.196120,0.224148,0.136769,0.098142,0.139802,0.207721,0.259932,0.081428,...,0.098365,0.210776,0.163887,0.152010,0.128475,0.265113,0.226398,0.262978,0.147111,0.117151
423,0.095094,0.082071,0.058329,0.105349,0.019658,0.125952,0.100000,0.103099,0.120147,0.109439,...,0.130951,0.081359,0.303526,0.064416,0.064254,0.125619,0.098877,0.127854,0.086713,0.061642
253,0.137393,0.212977,0.185609,0.167008,0.141687,0.005124,0.130951,0.143075,0.235129,0.025871,...,9999.000000,0.166780,0.229253,0.179645,0.163517,0.234422,0.229617,0.219575,0.189366,0.152774
57,0.044762,0.101321,0.067198,0.030511,0.097146,0.161865,0.081359,0.047488,0.075050,0.155081,...,0.166780,9999.000000,0.373385,0.131488,0.140757,0.069944,0.109484,0.053687,0.157706,0.140981
403,0.357404,0.368586,0.358901,0.383984,0.299072,0.232183,0.303526,0.364538,0.423526,0.226863,...,0.229253,0.373385,9999.000000,0.305973,0.281848,0.428980,0.384973,0.426218,0.293369,0.271947
346,0.156292,0.065973,0.073967,0.160213,0.045277,0.175148,0.064416,0.163794,0.136866,0.154755,...,0.179645,0.131488,0.305973,9999.000000,0.024160,0.148364,0.080659,0.164386,0.026542,0.034913
295,0.159328,0.088692,0.090877,0.167594,0.045080,0.159308,0.064254,0.167289,0.156190,0.137995,...,0.163517,0.140757,0.281848,0.024160,9999.000000,0.166566,0.104092,0.179138,0.026348,0.011720
53,0.112051,0.089870,0.075762,0.086294,0.133139,0.229394,0.125619,0.112154,0.015660,0.220180,...,0.234422,0.069944,0.428980,0.148364,0.166566,9999.000000,0.085992,0.035237,0.173762,0.171526
46,0.150894,0.017271,0.048055,0.139078,0.092433,0.224578,0.098877,0.155588,0.070938,0.208287,...,0.229617,0.109484,0.384973,0.080659,0.104092,0.085992,9999.000000,0.114411,0.100823,0.113217
25,0.087466,0.114320,0.090698,0.058332,0.139891,0.214740,0.127854,0.085531,0.049592,0.208681,...,0.219575,0.053687,0.426218,0.164386,0.179138,0.035237,0.114411,9999.000000,0.190768,0.181993
186,0.180738,0.088149,0.100183,0.186090,0.067055,0.185240,0.086713,0.188442,0.161693,0.163717,...,0.189366,0.157706,0.293369,0.026542,0.026348,0.173762,0.100823,0.190768,9999.000000,0.036592
310,0.156319,0.097266,0.095826,0.166632,0.043868,0.148656,0.061642,0.164438,0.161916,0.127131,...,0.152774,0.140981,0.271947,0.034913,0.011720,0.171526,0.113217,0.181993,0.036592,9999.000000

,251,316,400,381,225,42,90,212,409,11,...,320,401,111,219,208,35,144,274,385,264
251,9999.000000,0.136033,0.111475,0.134698,0.154931,0.106330,0.160959,0.175743,0.029882,0.117455,...,0.059403,0.009576,0.160959,0.167057,0.209218,0.175709,0.079870,0.035257,0.133646,0.016949
316,0.136033,9999.000000,0.067251,0.032763,0.135453,0.060992,0.067872,0.150729,0.143047,0.068689,...,0.076879,0.145577,0.067872,0.137618,0.131208,0.099199,0.104156,0.101699,0.002836,0.119337
400,0.111475,0.067251,9999.000000,0.040500,0.072612,0.100747,0.131473,0.091052,0.131632,0.114203,...,0.063268,0.119505,0.131473,0.078365,0.100157,0.160979,0.124398,0.078737,0.064635,0.095745
381,0.134698,0.032763,0.040500,9999.000000,0.103501,0.085676,0.100635,0.118147,0.148242,0.096237,...,0.076876,0.143797,0.100635,0.105052,0.101658,0.131905,0.122370,0.099489,0.030953,0.117812
225,0.154931,0.135453,0.072612,0.103501,9999.000000,0.173026,0.202384,0.021038,0.181971,0.186685,...,0.126372,0.159947,0.202384,0.013631,0.076826,0.232684,0.191576,0.131715,0.133206,0.143619
42,0.106330,0.060992,0.100747,0.085676,0.173026,9999.000000,0.054672,0.191799,0.101135,0.014460,...,0.061995,0.115338,0.054672,0.179080,0.187223,0.072350,0.046795,0.080960,0.060623,0.092930
90,0.160959,0.067872,0.131473,0.100635,0.202384,0.054672,9999.000000,0.218353,0.154824,0.045598,...,0.112441,0.170003,0.100000,0.205238,0.195872,0.031688,0.094918,0.134028,0.069768,0.147196
212,0.175743,0.150729,0.091052,0.118147,0.021038,0.191799,0.218353,9999.000000,0.202948,0.205195,...,0.146983,0.180582,0.218353,0.013116,0.069959,0.249152,0.211983,0.152745,0.148669,0.164610
409,0.029882,0.143047,0.131632,0.148242,0.181971,0.101135,0.154824,0.202948,9999.000000,0.109398,...,0.071605,0.030957,0.154824,0.193587,0.231376,0.164476,0.063744,0.053072,0.141031,0.038379
11,0.117455,0.068689,0.114203,0.096237,0.186685,0.014460,0.045598,0.205195,0.109398,9999.000000,...,0.076108,0.126170,0.045598,0.192389,0.197856,0.059058,0.049819,0.094076,0.068849,0.104954
337,0.011814,0.146648,0.118396,0.143822,0.156985,0.118140,0.172762,0.177529,0.035625,0.129251,...,0.069790,0.004670,0.172762,0.169524,0.214520,0.187438,0.090886,0.045112,0.144205,0.027372
295,0.000587,0.135567,0.110894,0.134159,0.154372,0.106065,0.160684,0.175187,0.030300,0.117233,...,0.058914,0.010019,0.160684,0.166491,0.208631,0.175525,0.079843,0.034730,0.133176,0.016433
140,0.153374,0.096899,0.152105,0.128349,0.224683,0.055158,0.038787,0.242412,0.140334,0.040737,...,0.116677,0.161433,0.038787,0.229425,0.228004,0.025560,0.076626,0.133398,0.098033,0.142546
150,0.019796,0.145732,0.111958,0.140116,0.146278,0.122417,0.176662,0.166624,0.047684,0.134339,...,0.069245,0.017038,0.176662,0.159036,0.206050,0.193101,0.099162,0.044531,0.143174,0.029489
123,0.132788,0.036830,0.095798,0.068306,0.167473,0.033476,0.036241,0.184195,0.131904,0.035323,...,0.079387,0.142207,0.036241,0.171109,0.168038,0.065242,0.080266,0.102635,0.037871,0.117641
227,0.170085,0.125832,0.072012,0.093069,0.027475,0.171379,0.193703,0.028198,0.195173,0.184152,...,0.132953,0.176165,0.193703,0.017548,0.049608,0.224914,0.196153,0.142902,0.123973,0.157008
253,0.164083,0.135625,0.075796,0.103133,0.011163,0.176536,0.203162,0.015343,0.190605,0.189893,...,0.132697,0.169405,0.203162,0.002982,0.066318,0.233897,0.197416,0.139600,0.133530,0.152227
197,0.011814,0.146648,0.118396,0.143822,0.156985,0.118140,0.172762,0.177529,0.035625,0.129251,...,0.069790,0.004670,0.172762,0.169524,0.214520,0.187438,0.090886,0.045112,0.144205,0.027372
396,0.109901,0.077750,0.010538,0.050731,0.064170,0.108876,0.141493,0.083431,0.131901,0.122618,...,0.066364,0.117425,0.141493,0.071105,0.099595,0.170709,0.129652,0.078841,0.075119,0.094895
141,0.071095,0.091253,0.106842,0.106723,0.173894,0.039968,0.093273,0.194280,0.061559,0.047964,...,0.048010,0.079285,0.093273,0.182529,0.203671,0.104883,0.017712,0.055074,0.089914,0.060894
217,0.021523,0.120827,0.106506,0.123830,0.158913,0.085866,0.140531,0.179947,0.025155,0.096451,...,0.046964,0.029746,0.140531,0.170124,0.206348,0.154398,0.058634,0.028185,0.118642,0.017076
46,0.103981,0.128911,0.156087,0.150857,0.223869,0.068050,0.102926,0.244236,0.081025,0.064203,...,0.097812,0.109298,0.102926,0.232429,0.250752,0.098823,0.032318,0.100570,0.128373,0.100227
50,0.063011,0.103076,0.113720,0.116906,0.178320,0.052343,0.104989,0.198992,0.050065,0.059441,...,0.052040,0.070482,0.104989,0.187615,0.212023,0.114849,0.017406,0.053218,0.101625,0.055220
426,0.144313,0.128219,0.063759,0.096868,0.010770,0.163598,0.194539,0.031808,0.171244,0.177395,...,0.115866,0.149439,0.194539,0.023118,0.082173,0.224509,0.181168,0.120948,0.125871,0.132884
168,0.021131,0.153473,0.121528,0.148980,0.155690,0.127124,0.181669,0.175939,0.044243,0.138471,...,0.076660,0.013955,0.181669,0.168524,0.215835,0.196821,0.100576,0.051806,0.150965,0.035079
315,0.037751,0.163513,0.147675,0.167151,0.192485,0.122200,0.175671,0.213220,0.021148,0.130154,...,0.090277,0.032948,0.175671,0.204720,0.246398,0.184353,0.083296,0.069205,0.161427,0.051998
266,0.098492,0.060610,0.016682,0.041238,0.087340,0.085743,0.120580,0.106526,0.116820,0.099565,...,0.047100,0.106997,0.120580,0.094079,0.116076,0.148973,0.107742,0.064503,0.057806,0.082188
69,0.142086,0.099712,0.150039,0.129762,0.222572,0.050016,0.049284,0.240960,0.127596,0.035928,...,0.109396,0.149839,0.049284,0.228107,0.230730,0.039830,0.063888,0.124257,0.100465,0.132133
280,0.133428,0.016522,0.079275,0.048494,0.149590,0.047158,0.052813,0.165604,0.137028,0.053195,...,0.075927,0.142998,0.052813,0.152490,0.147729,0.083631,0.092463,0.100557,0.017686,0.117249
79,0.154695,0.044568,0.110360,0.077181,0.179942,0.052871,0.024467,0.195278,0.153150,0.050112,...,0.100929,0.164101,0.024467,0.182171,0.171405,0.056125,0.098783,0.124442,0.046740,0.139562
320,0.059403,0.076879,0.063268,0.076876,0.126372,0.061995,0.112441,0.146983,0.071605,0.076108,...,9999.000000,0.068881,0.112441,0.135576,0.163175,0.134105,0.065507,0.024855,0.074419,0.042557
401,0.009576,0.145577,0.119505,0.143797,0.159947,0.115338,0.170003,0.180582,0.030957,0.126170,...,0.068881,9999.000000,0.170003,0.172364,0.216370,0.184119,0.086919,0.044533,0.143180,0.026339
111,0.160959,0.067872,0.131473,0.100635,0.202384,0.054672,0.100000,0.218353,0.154824,0.045598,...,0.112441,0.170003,9999.000000,0.205238,0.195872,0.031688,0.094918,0.134028,0.069768,0.147196
219,0.167057,0.137618,0.078365,0.105052,0.013631,0.179080,0.205238,0.013116,0.193587,0.192389,...,0.135576,0.172364,0.205238,9999.000000,0.064857,0.236045,0.200241,0.142570,0.135554,0.155209
208,0.209218,0.131208,0.100157,0.101658,0.076826,0.187223,0.195872,0.069959,0.231376,0.197856,...,0.163175,0.216370,0.195872,0.064857,9999.000000,0.227497,0.220568,0.178308,0.130298,0.194474
35,0.175709,0.099199,0.160979,0.131905,0.232684,0.072350,0.031688,0.249152,0.164476,0.059058,...,0.134105,0.184119,0.031688,0.236045,0.227497,9999.000000,0.101067,0.153089,0.100959,0.163825
144,0.079870,0.104156,0.124398,0.122370,0.191576,0.046795,0.094918,0.211983,0.063744,0.049819,...,0.065507,0.086919,0.094918,0.200241,0.220568,0.101067,9999.000000,0.069997,0.103135,0.072621
274,0.035257,0.101699,0.078737,0.099489,0.131715,0.080960,0.134028,0.152745,0.053072,0.094076,...,0.024855,0.044533,0.134028,0.142570,0.178308,0.153089,0.069997,9999.000000,0.099214,0.018329
385,0.133646,0.002836,0.064635,0.030953,0.133206,0.060623,0.069768,0.148669,0.141031,0.068849,...,0.074419,0.143180,0.069768,0.135554,0.130298,0.100959,0.103135,0.099214,9999.000000,0.116916
264,0.016949,0.119337,0.095745,0.117812,0.143619,0.092930,0.147196,0.164610,0.038379,0.104954,...,0.042557,0.026339,0.147196,0.155209,0.194474,0.163825,0.072621,0.018329,0.116916,9999.000000

## Solve TSP 40 addresses with GAMS

In [ ]:

def solve_tsp(c_df, sub):
    m = Container()

    c_df.reset_index(inplace=True, drop=True)
    c_df.columns = range(c_df.shape[1])

    # Define nodes
    nodos = [str(i) for i in c_df.index]


    # Main node set
    ii = Set(m, name="ii", domain="*", records=nodos)

    # Aliases to allow i,j indexing over the same node set
    jj = Alias(m, "jj", alias_with=ii)
    i = Alias(m, "i", alias_with=ii)
    j = Alias(m, "j", alias_with=ii)

    records = c_df.stack().reset_index()
    records.columns = ['i', 'j', 'value']

    # Cost parameter c(i,j) (Distance traveled)
    c = gp.Parameter(m, "c", domain=[ii, jj], records=records)


    # Binary variable: x(i,j) = 1 if path goes from i to j
    x = Variable(m, name="x", type="binary", domain=[i, j])

    # Continuous auxiliary variable for subtour elimination (MTZ formulation)
    u = Variable(m, name="u", type = "positive", domain=ii)

    # Define equations.
    rowsum = Equation(m, name="rowsum", domain=ii)
    colsum = Equation(m, name="colsum", domain=jj)
    subtour = Equation(m, name="subtour", domain=[ii,jj])

    # Each node must leave exactly once
    rowsum[i] = Sum(j, x[i, j]) == 1
    # Each node must be entered exactly once
    colsum[j] = Sum(i, x[i, j]) == 1

    # Miller–Tucker–Zemlin (MTZ) subtour elimination constraints
    subtour = Equation(m, name="subtour", domain=[ii, jj])
    subtour[i, j].where[(Ord(i) > 1) & (Ord(j) > 1) & (Ord(i) != Ord(j))] = u[i] - u[j] + Card(i) * x[i, j] <= Card(i) - 1

    # Minimize total traveled distance
    objective = Sum([i, j], c[i, j] * x[i, j])

    assign = Model(
        m,
        name="tsp",
        equations=[rowsum, colsum, subtour],
        problem="mip",
        sense="min",
        objective=objective,
    )

    sol = assign.solve(options= Options(relative_optimality_gap=0.0001,time_limit=900, threads=6))

    # Retrieve all x(i,j) variable records
    camino = x.records
    mat = x.records

    # Filter arcs that are part of the optimal tour (x = 1)
    camino = camino[camino["level"] == 1]
    camino.reset_index(inplace=True, drop= True)


    sub_list = sub.tolist()

    # Convert node labels to integers for mapping
    mat["i"] = mat["i"].astype(int)
    mat["j"] = mat["j"].astype(int)
    camino["i"] = camino["i"].astype(int)
    camino["j"] = camino["j"].astype(int)


    # Map internal indices back to original unique address identifiers indexes.
    mat["i"] = mat["i"].map(lambda x: sub_list[x])
    mat["j"] = mat["j"].map(lambda x: sub_list[x])
    camino["i"] = camino["i"].map(lambda x: sub_list[x])
    camino["j"] = camino["j"].map(lambda x: sub_list[x])

    # Convert identifiers back to strings
    mat["i"] = mat["i"].astype(str)
    mat["j"] = mat["j"].astype(str)
    camino["i"] = camino["i"].astype(str)
    camino["j"] = camino["j"].astype(str)

    #print(camino["i"].value_counts())
    #print(camino["j"].value_counts())
    #print(camino.shape[0])

    # Print distance traveled by traveler.
    print(f"Costo: {sol["Objective"]}")

    # Reconstruct path followed to a list.
    secuencia = reconstruct_tsp_path_safe(camino)

    return mat, camino, secuencia, sol["Objective"], sol["Solver Time"]

In [ ]:
resultados_40 = {}

# Solve each 40-node instance, and store the transition matrices, tour, objective value, and solution time inside a dictionary.
for idx, matriz in enumerate(matrices_40):
    print(f"✅ Resolviendo instancia {idx+1}")
    print(matriz.columns)

    mat, camino, sec, obj, t= solve_tsp(matriz, matriz.columns)

    count(sec)

    resultados_40[idx] = {
        "mat": mat,
        "camino": camino,
        "secuencia": sec,
        "objetivo": obj,
        "time": t
    }

    print(f"✅ Finalizado con instancia {idx+1}, {camino.shape[0]}, {sec},  (Objetivo: {obj})")

✅ Resolviendo instancia 1
RangeIndex(start=0, stop=40, step=1)

/tmp/ipython-input-306832568.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].astype(int)
/tmp/ipython-input-306832568.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].astype(int)
/tmp/ipython-input-306832568.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].map(lambda x: sub_list[x])
/tmp/ipython-input-306832568.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].map(lambda x: sub_list[x])
/tmp/ipython-input-306832568.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].astype(str)
/tmp/ipython-input-306832568.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].astype(str)

Costo: 0    132.922945
Name: Objective, dtype: float64
Valor 0 se repite 2 veces
Cantidad de valores únicos: 40
✅ Finalizado con instancia 1, 40, ['0', '7', '36', '19', '32', '33', '34', '25', '28', '16', '31', '13', '10', '4', '1', '22', '18', '12', '35', '3', '5', '8', '29', '6', '26', '2', '23', '20', '30', '17', '27', '21', '14', '39', '37', '11', '38', '24', '15', '9', '0'],  (Objetivo: 0    132.922945
Name: Objective, dtype: float64)
✅ Resolviendo instancia 2
RangeIndex(start=0, stop=40, step=1)

/tmp/ipython-input-306832568.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].astype(int)
/tmp/ipython-input-306832568.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].astype(int)
/tmp/ipython-input-306832568.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].map(lambda x: sub_list[x])
/tmp/ipython-input-306832568.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].map(lambda x: sub_list[x])
/tmp/ipython-input-306832568.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].astype(str)
/tmp/ipython-input-306832568.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].astype(str)

Costo: 0    1.324939
Name: Objective, dtype: float64
Valor 0 se repite 2 veces
Cantidad de valores únicos: 40
✅ Finalizado con instancia 2, 40, ['0', '17', '32', '23', '8', '7', '27', '37', '31', '39', '15', '2', '34', '6', '12', '21', '14', '38', '22', '9', '18', '26', '33', '11', '29', '5', '16', '20', '3', '19', '35', '30', '25', '13', '36', '24', '28', '1', '4', '10', '0'],  (Objetivo: 0    1.324939
Name: Objective, dtype: float64)
✅ Resolviendo instancia 3
RangeIndex(start=0, stop=40, step=1)

/tmp/ipython-input-306832568.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].astype(int)
/tmp/ipython-input-306832568.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].astype(int)
/tmp/ipython-input-306832568.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].map(lambda x: sub_list[x])
/tmp/ipython-input-306832568.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].map(lambda x: sub_list[x])
/tmp/ipython-input-306832568.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].astype(str)
/tmp/ipython-input-306832568.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].astype(str)

Costo: 0    0.929544
Name: Objective, dtype: float64
Valor 0 se repite 2 veces
Cantidad de valores únicos: 40
✅ Finalizado con instancia 3, 40, ['0', '30', '22', '8', '21', '11', '14', '10', '18', '24', '34', '23', '5', '29', '12', '36', '31', '3', '13', '9', '27', '19', '4', '16', '7', '17', '28', '15', '26', '38', '1', '33', '32', '6', '35', '39', '37', '20', '2', '25', '0'],  (Objetivo: 0    0.929544
Name: Objective, dtype: float64)
✅ Resolviendo instancia 4
RangeIndex(start=0, stop=40, step=1)

/tmp/ipython-input-306832568.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].astype(int)
/tmp/ipython-input-306832568.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].astype(int)
/tmp/ipython-input-306832568.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].map(lambda x: sub_list[x])
/tmp/ipython-input-306832568.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].map(lambda x: sub_list[x])
/tmp/ipython-input-306832568.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].astype(str)
/tmp/ipython-input-306832568.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].astype(str)

Costo: 0    133.039967
Name: Objective, dtype: float64
Valor 0 se repite 2 veces
Cantidad de valores únicos: 40
✅ Finalizado con instancia 4, 40, ['0', '16', '26', '1', '8', '19', '9', '25', '30', '12', '21', '6', '4', '23', '28', '39', '36', '2', '31', '13', '29', '32', '10', '37', '22', '3', '11', '7', '34', '15', '33', '17', '24', '14', '20', '5', '38', '27', '18', '35', '0'],  (Objetivo: 0    133.039967
Name: Objective, dtype: float64)
✅ Resolviendo instancia 5
RangeIndex(start=0, stop=40, step=1)

/tmp/ipython-input-306832568.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].astype(int)
/tmp/ipython-input-306832568.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].astype(int)
/tmp/ipython-input-306832568.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].map(lambda x: sub_list[x])
/tmp/ipython-input-306832568.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].map(lambda x: sub_list[x])
/tmp/ipython-input-306832568.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].astype(str)
/tmp/ipython-input-306832568.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].astype(str)

Costo: 0    33.906638
Name: Objective, dtype: float64
Valor 0 se repite 2 veces
Cantidad de valores únicos: 40
✅ Finalizado con instancia 5, 40, ['0', '11', '38', '31', '29', '7', '10', '12', '28', '25', '24', '18', '19', '17', '37', '32', '9', '8', '22', '34', '4', '14', '26', '39', '6', '23', '20', '27', '21', '30', '33', '3', '2', '35', '1', '36', '16', '15', '13', '5', '0'],  (Objetivo: 0    33.906638
Name: Objective, dtype: float64)
✅ Resolviendo instancia 6
RangeIndex(start=0, stop=40, step=1)

/tmp/ipython-input-306832568.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].astype(int)
/tmp/ipython-input-306832568.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].astype(int)
/tmp/ipython-input-306832568.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].map(lambda x: sub_list[x])
/tmp/ipython-input-306832568.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].map(lambda x: sub_list[x])
/tmp/ipython-input-306832568.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].astype(str)
/tmp/ipython-input-306832568.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].astype(str)

Costo: 0    0.971227
Name: Objective, dtype: float64
Valor 0 se repite 2 veces
Cantidad de valores únicos: 40
✅ Finalizado con instancia 6, 40, ['0', '18', '22', '14', '32', '2', '35', '37', '9', '15', '17', '13', '26', '6', '34', '24', '31', '11', '27', '21', '39', '20', '7', '5', '25', '33', '8', '38', '29', '36', '30', '1', '10', '16', '12', '23', '3', '28', '19', '4', '0'],  (Objetivo: 0    0.971227
Name: Objective, dtype: float64)
✅ Resolviendo instancia 7
RangeIndex(start=0, stop=40, step=1)

/tmp/ipython-input-306832568.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].astype(int)
/tmp/ipython-input-306832568.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].astype(int)
/tmp/ipython-input-306832568.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].map(lambda x: sub_list[x])
/tmp/ipython-input-306832568.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].map(lambda x: sub_list[x])
/tmp/ipython-input-306832568.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].astype(str)
/tmp/ipython-input-306832568.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].astype(str)

Costo: 0    33.992213
Name: Objective, dtype: float64
Valor 0 se repite 2 veces
Cantidad de valores únicos: 40
✅ Finalizado con instancia 7, 40, ['0', '16', '8', '18', '32', '12', '24', '14', '23', '33', '7', '35', '22', '34', '2', '30', '3', '13', '1', '5', '17', '11', '25', '39', '31', '27', '26', '20', '37', '15', '19', '28', '21', '38', '6', '36', '4', '29', '10', '9', '0'],  (Objetivo: 0    33.992213
Name: Objective, dtype: float64)
✅ Resolviendo instancia 8
RangeIndex(start=0, stop=40, step=1)

/tmp/ipython-input-306832568.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].astype(int)
/tmp/ipython-input-306832568.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].astype(int)
/tmp/ipython-input-306832568.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].map(lambda x: sub_list[x])
/tmp/ipython-input-306832568.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].map(lambda x: sub_list[x])
/tmp/ipython-input-306832568.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].astype(str)
/tmp/ipython-input-306832568.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].astype(str)

Costo: 0    1.028014
Name: Objective, dtype: float64
Valor 0 se repite 2 veces
Cantidad de valores únicos: 40
✅ Finalizado con instancia 8, 40, ['0', '23', '11', '18', '4', '20', '26', '16', '13', '29', '37', '38', '12', '30', '1', '24', '19', '35', '10', '27', '22', '14', '2', '7', '32', '31', '21', '15', '3', '39', '9', '8', '36', '5', '28', '6', '17', '25', '33', '34', '0'],  (Objetivo: 0    1.028014
Name: Objective, dtype: float64)
✅ Resolviendo instancia 9
RangeIndex(start=0, stop=40, step=1)

[MODEL - WARNING] The solve was interrupted! Solve status: UserInterrupt. For further information, see https://gamspy.readthedocs.io/en/latest/reference/gamspy._model.html#gamspy.SolveStatus.
WARNING:MODEL:The solve was interrupted! Solve status: UserInterrupt. For further information, see https://gamspy.readthedocs.io/en/latest/reference/gamspy._model.html#gamspy.SolveStatus.
/tmp/ipython-input-306832568.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].astype(int)
/tmp/ipython-input-306832568.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].astype(int)
/tmp/ipython-input-306832568.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].map(lambda x: sub_list[x])
/tmp/ipython-input-306832568.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].map(lambda x: sub_list[x])
/tmp/ipython-input-306832568.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].astype(str)
/tmp/ipython-input-306832568.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].astype(str)

Costo: 0    1.377894
Name: Objective, dtype: float64
Valor 0 se repite 2 veces
Cantidad de valores únicos: 40
✅ Finalizado con instancia 9, 40, ['0', '13', '7', '27', '3', '16', '20', '31', '21', '11', '37', '35', '8', '36', '1', '2', '6', '18', '29', '4', '23', '33', '15', '34', '39', '26', '38', '19', '28', '32', '30', '12', '24', '5', '22', '9', '17', '10', '25', '14', '0'],  (Objetivo: 0    1.377894
Name: Objective, dtype: float64)
✅ Resolviendo instancia 10
Index([251, 316, 400, 381, 225,  42,  90, 212, 409,  11, 337, 295, 140, 150,
       123, 227, 253, 197, 396, 141, 217,  46,  50, 426, 168, 315, 266,  69,
       280,  79, 320, 401, 111, 219, 208,  35, 144, 274, 385, 264],
      dtype='int64')
Costo: 0    0.982061
Name: Objective, dtype: float64
Valor 251 se repite 2 veces
Cantidad de valores únicos: 40
✅ Finalizado con instancia 10, 40, ['251', '337', '150', '168', '197', '401', '315', '409', '217', '50', '141', '144', '46', '69', '140', '35', '90', '79', '111', '11', '42', '123', '280', '316', '385', '381', '208', '227', '253', '219', '212', '225', '426', '396', '400', '266', '320', '274', '264', '295', '251'],  (Objetivo: 0    0.982061
Name: Objective, dtype: float64)

/tmp/ipython-input-306832568.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].astype(int)
/tmp/ipython-input-306832568.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].astype(int)
/tmp/ipython-input-306832568.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].map(lambda x: sub_list[x])
/tmp/ipython-input-306832568.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].map(lambda x: sub_list[x])
/tmp/ipython-input-306832568.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["i"] = camino["i"].astype(str)
/tmp/ipython-input-306832568.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  camino["j"] = camino["j"].astype(str)

In [ ]:
import pandas as pd

# Convert dictionary to DataFrame.
df_resultados = pd.DataFrame([
    {"Instancia": i + 1,
     "Secuencia": resultados_40[i]["secuencia"],
     "Objetivo": resultados_40[i]["objetivo"],
     "Time": resultados_40[i]["time"],}
    for i in range(10)
])

display(df_resultados)

,Instancia,Secuencia,Objetivo,Time
0,1,"[0, 7, 36, 19, 32, 33, 34, 25, 28, 16, 31, 13,...","0 132.922945 Name: Objective, dtype: float64","0 45.915 Name: Solver Time, dtype: float64"
1,2,"[0, 17, 32, 23, 8, 7, 27, 37, 31, 39, 15, 2, 3...","0 1.324939 Name: Objective, dtype: float64","0 2.901 Name: Solver Time, dtype: float64"
2,3,"[0, 30, 22, 8, 21, 11, 14, 10, 18, 24, 34, 23,...","0 0.929544 Name: Objective, dtype: float64","0 76.063 Name: Solver Time, dtype: float64"
3,4,"[0, 16, 26, 1, 8, 19, 9, 25, 30, 12, 21, 6, 4,...","0 133.039967 Name: Objective, dtype: float64","0 69.246 Name: Solver Time, dtype: float64"
4,5,"[0, 11, 38, 31, 29, 7, 10, 12, 28, 25, 24, 18,...","0 33.906638 Name: Objective, dtype: float64","0 6.196 Name: Solver Time, dtype: float64"
5,6,"[0, 18, 22, 14, 32, 2, 35, 37, 9, 15, 17, 13, ...","0 0.971227 Name: Objective, dtype: float64","0 14.649 Name: Solver Time, dtype: float64"
6,7,"[0, 16, 8, 18, 32, 12, 24, 14, 23, 33, 7, 35, ...","0 33.992213 Name: Objective, dtype: float64","0 67.099 Name: Solver Time, dtype: float64"
7,8,"[0, 23, 11, 18, 4, 20, 26, 16, 13, 29, 37, 38,...","0 1.028014 Name: Objective, dtype: float64","0 38.674 Name: Solver Time, dtype: float64"
8,9,"[0, 13, 7, 27, 3, 16, 20, 31, 21, 11, 37, 35, ...","0 1.377894 Name: Objective, dtype: float64","0 133.158 Name: Solver Time, dtype: float64"
9,10,"[251, 337, 150, 168, 197, 401, 315, 409, 217, ...","0 0.982061 Name: Objective, dtype: float64","0 80.803 Name: Solver Time, dtype: float64"

In [ ]:
# Export results to an excel file.
df_resultados.to_excel("resultados_40.xlsx")

# Deine solver Function using NEOS optimization servers.

Due to the problem complexity and the limitations of the GAMSpy free license, instances with 100, 150, 200, and 250 nodes (addresses) were solved using a cloud-based solver, which removed the memory restrictions imposed by the free license. The cloud service used for this purpose was the NEOS optimization server.

In [ ]:
def solve_tsp_neos(c_df, sub, n = False):
    m = Container()

    c_df.reset_index(inplace=True, drop=True)
    c_df.columns = range(c_df.shape[1])

    # Define nodes
    nodos = [str(i) for i in c_df.index]


    # Main node set
    ii = Set(m, name="ii", domain="*", records=nodos)

    # Aliases to allow i,j indexing over the same node set
    jj = Alias(m, "jj", alias_with=ii)
    i = Alias(m, "i", alias_with=ii)
    j = Alias(m, "j", alias_with=ii)

    records = c_df.stack().reset_index()
    records.columns = ['i', 'j', 'value']

    # Cost parameter c(i,j) (Distance traveled)
    c = gp.Parameter(m, "c", domain=[ii, jj], records=records)


    # Binary variable: x(i,j) = 1 if path goes from i to j
    x = Variable(m, name="x", type="binary", domain=[i, j])

    # Continuous auxiliary variable for subtour elimination (MTZ formulation
    u = Variable(m, name="u", type = "positive", domain=ii)

    # Define equations.
    rowsum = Equation(m, name="rowsum", domain=ii)
    colsum = Equation(m, name="colsum", domain=jj)
    subtour = Equation(m, name="subtour", domain=[ii,jj])

    # Each node must leave exactly once
    rowsum[i] = Sum(j, x[i, j]) == 1
    # Each node must be entered exactly once
    colsum[j] = Sum(i, x[i, j]) == 1

    # Miller–Tucker–Zemlin (MTZ) subtour elimination constraints
    subtour = Equation(m, name="subtour", domain=[ii, jj])
    subtour[i, j].where[(Ord(i) > 1) & (Ord(j) > 1) & (Ord(i) != Ord(j))] = u[i] - u[j] + Card(i) * x[i, j] <= Card(i) - 1

    # Minimize total traveled distance
    objective = Sum([i, j], c[i, j] * x[i, j])

    assign = Model(
        m,
        name="tsp",
        equations=[rowsum, colsum, subtour],
        problem="mip",
        sense="min",
        objective=objective,
    )

    # Log into NEOS
    client= gp.NeosClient(email="A01198941@tec.mx")
    sol = assign.solve(backend="neos", client=client, options= Options(relative_optimality_gap=0.05, time_limit=600))

    # Retrieve all x(i,j) variable records
    camino = x.records
    mat = x.records

    # Filter arcs that are part of the optimal tour (x = 1)
    camino = camino[camino["level"] == 1]
    camino.reset_index(inplace=True, drop= True)

    sub_list = sub.tolist()

    # Convert node labels to integers for mapping
    mat["i"] = mat["i"].astype(int)
    mat["j"] = mat["j"].astype(int)
    camino["i"] = camino["i"].astype(int)
    camino["j"] = camino["j"].astype(int)

    # Map internal indices back to original unique address identifiers indexes.
    mat["i"] = mat["i"].map(lambda x: sub_list[x])
    mat["j"] = mat["j"].map(lambda x: sub_list[x])
    camino["i"] = camino["i"].map(lambda x: sub_list[x])
    camino["j"] = camino["j"].map(lambda x: sub_list[x])

    # Convert identifiers back to strings
    mat["i"] = mat["i"].astype(str)
    mat["j"] = mat["j"].astype(str)
    camino["i"] = camino["i"].astype(str)
    camino["j"] = camino["j"].astype(str)

    #print(camino["i"].value_counts())
    #print(camino["j"].value_counts())
    #print(camino.shape[0])

    # Print distance traveled by traveler.
    print(f"Costo: {sol["Objective"]}")

    # Reconstruct path followed to a list.
    secuencia = reconstruct_tsp_path_safe(camino)

    return mat, camino, secuencia, sol["Objective"], sol["Solver Time"]

# Solving instances of 100 addresses

## Generate distance sub matrices (matrices_100.xlsx).

In [ ]:
# Generate 10 instances of sub matrices consisting of 100 randomly chosen addresses. (matrices_100.xlsx)
matrices_100, subconjuntos = generar_submatrices_distancias(df_matriz_dist, n_subconjuntos=10, tamaño_sub=100)

✅ Subconjunto 1: 100 ubicaciones seleccionadas
✅ Subconjunto 2: 100 ubicaciones seleccionadas
✅ Subconjunto 3: 100 ubicaciones seleccionadas
✅ Subconjunto 4: 100 ubicaciones seleccionadas
✅ Subconjunto 5: 100 ubicaciones seleccionadas
✅ Subconjunto 6: 100 ubicaciones seleccionadas
✅ Subconjunto 7: 100 ubicaciones seleccionadas
✅ Subconjunto 8: 100 ubicaciones seleccionadas
✅ Subconjunto 9: 100 ubicaciones seleccionadas
✅ Subconjunto 10: 100 ubicaciones seleccionadas

In [ ]:
matrices_100[0]

,164,225,312,200,173,161,283,191,28,15,...,139,400,371,282,216,348,311,398,116,249
164,9999.000000,0.134587,0.054352,0.052702,0.025420,0.099115,0.019658,0.100000,0.054556,0.120791,...,0.109878,0.075589,0.118418,0.106450,0.057396,0.175745,0.077484,0.063364,0.055323,0.061977
225,0.134587,9999.000000,0.172501,0.115604,0.112831,0.147607,0.124996,0.134587,0.177200,0.202384,...,0.177766,0.072612,0.016473,0.149376,0.181971,0.076826,0.119791,0.101090,0.188422,0.099082
312,0.054352,0.172501,9999.000000,0.106976,0.078087,0.150625,0.073983,0.054352,0.082798,0.160570,...,0.155842,0.125819,0.156081,0.158156,0.012842,0.224754,0.131484,0.117441,0.062418,0.115866
200,0.052702,0.115604,0.106976,9999.000000,0.033122,0.052027,0.033048,0.052702,0.066520,0.092978,...,0.073066,0.043186,0.102193,0.058447,0.108860,0.135039,0.025204,0.016296,0.086423,0.017264
173,0.025420,0.112831,0.078087,0.033122,9999.000000,0.084427,0.012541,0.025420,0.066365,0.117481,...,0.101568,0.050262,0.097144,0.091171,0.082396,0.150393,0.058125,0.039858,0.075691,0.038016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,0.175745,0.076826,0.224754,0.135039,0.150393,0.139345,0.159562,0.175745,0.201240,0.195872,...,0.169517,0.100157,0.086189,0.137083,0.231376,9999.000000,0.123889,0.118994,0.220928,0.118853
311,0.077484,0.119791,0.131484,0.025204,0.058125,0.031046,0.057927,0.077484,0.080252,0.082601,...,0.058570,0.049678,0.108808,0.035996,0.132602,0.123889,9999.000000,0.024435,0.104233,0.027396
398,0.063364,0.101090,0.117441,0.016296,0.039858,0.055389,0.044261,0.063364,0.082803,0.103540,...,0.081219,0.028552,0.088488,0.060408,0.120647,0.118994,0.024435,9999.000000,0.102074,0.002963
116,0.055323,0.188422,0.062418,0.086423,0.075691,0.111401,0.063932,0.055323,0.028080,0.104237,...,0.106146,0.123201,0.172556,0.118769,0.053423,0.220928,0.104233,0.102074,9999.000000,0.102084
249,0.061977,0.099082,0.115866,0.017264,0.038016,0.058336,0.043138,0.061977,0.083475,0.106124,...,0.083994,0.026471,0.086249,0.063371,0.119343,0.118853,0.027396,0.002963,0.102084,9999.000000

In [ ]:
# Save matrices to an excel file for later use
archivo_salida = "matrices_100.xlsx"

with pd.ExcelWriter(archivo_salida, engine="xlsxwriter") as writer:
    for idx, matriz in enumerate(matrices_100):
        hoja_nombre = f"Instancia_{idx+1}"
        matriz.to_excel(writer, sheet_name=hoja_nombre, index=True)

## Read pre-generated submatrices

In [11]:
archivo = "/content/tsp-bio-inspired-algorithms/Data_for_algorithms/matrices_100.xlsx"

# Read file.
hojas_dict = pd.read_excel(archivo, sheet_name=None, index_col=0)

# Convert lists into dataframes.
matrices_100 = [hojas_dict[f"Instancia_{i+1}"] for i in range(10)]

# Validation.
print(len(matrices_100))  # print number of instances 10.
print(matrices_100[0].head())  # print first instance.
print(matrices_100[0].shape) # print first instance shape.

10
             164          225          312          200          173  \
164  9999.000000     0.134587     0.054352     0.052702     0.025420
225     0.134587  9999.000000     0.172501     0.115604     0.112831
312     0.054352     0.172501  9999.000000     0.106976     0.078087
200     0.052702     0.115604     0.106976  9999.000000     0.033122
173     0.025420     0.112831     0.078087     0.033122  9999.000000

          161       283       191       28        15   ...       139  \
164  0.099115  0.019658  0.100000  0.054556  0.120791  ...  0.109878
225  0.147607  0.124996  0.134587  0.177200  0.202384  ...  0.177766
312  0.150625  0.073983  0.054352  0.082798  0.160570  ...  0.155842
200  0.052027  0.033048  0.052702  0.066520  0.092978  ...  0.073066
173  0.084427  0.012541  0.025420  0.066365  0.117481  ...  0.101568

          400       371       282       216       348       311       398  \
164  0.075589  0.118418  0.106450  0.057396  0.175745  0.077484  0.063364
225  0.072612  0.016473  0.149376  0.181971  0.076826  0.119791  0.101090
312  0.125819  0.156081  0.158156  0.012842  0.224754  0.131484  0.117441
200  0.043186  0.102193  0.058447  0.108860  0.135039  0.025204  0.016296
173  0.050262  0.097144  0.091171  0.082396  0.150393  0.058125  0.039858

          116       249
164  0.055323  0.061977
225  0.188422  0.099082
312  0.062418  0.115866
200  0.086423  0.017264
173  0.075691  0.038016

[5 rows x 100 columns]
(100, 100)

## Solve TSP 100 addresses with NEOS

In [ ]:
resultados_100 = {}

# Solve each 100-node instance, and store the transition matrices, tour, objective value, and solution time inside a dictionary.
for idx, matriz in enumerate(matrices_100):
    print(f"✅ Resolviendo instancia {idx+1}")
    print(matriz.columns)

    mat, camino, sec, obj, t = solve_tsp_neos(matriz, matriz.columns, n = True)


    count(sec)

    resultados_100[idx] = {
        "mat": mat,
        "camino": camino,
        "secuencia": sec,
        "objetivo": obj,
        "time": t
    }

    print(f"✅ Finalizado con instancia {idx+1}, {camino.shape[0]}, {sec},  (Objetivo: {obj})")

✅ Resolviendo instancia 1
Index([164, 225, 312, 200, 173, 161, 283, 191,  28,  15, 141, 125, 234,  56,
       335,   5, 299, 174, 111, 379, 275,  52,   0,  38, 388,  92, 259, 258,
       202,  61,  43, 267, 169, 110,  47, 268,  41,  97, 214,  18,  14,  55,
       415,  35, 301,   6, 158,  75, 387, 291, 418,  27, 177,  22, 109, 428,
       339,  96, 121,  13, 108, 396, 133, 344, 228, 403, 182,  58, 181, 170,
       178,  21, 107, 157, 285, 215, 224, 199, 172, 143, 318, 404, 100, 411,
       328,  86,  89, 247, 332, 146, 139, 400, 371, 282, 216, 348, 311, 398,
       116, 249],
      dtype='int64')

[NEOS - INFO] Job Number: 17951477, Job Password: UXBsSLjo
INFO:NEOS:Job Number: 17951477, Job Password: UXBsSLjo

NeosClientException: Couldn't get output file from NEOS Server because: Output file does not exist

# Solving instances of 150 addresses

## Generate distance submatrices (matrices_150.xlsx)

In [ ]:
# Generate 10 instances of sub matrices consisting of 150 randomly chosen addresses. (matrices_100.xlsx)
matrices_150, subconjuntos = generar_submatrices_distancias(df_matriz_dist, n_subconjuntos=10, tamaño_sub=150)

✅ Subconjunto 1: 150 ubicaciones seleccionadas
✅ Subconjunto 2: 150 ubicaciones seleccionadas
✅ Subconjunto 3: 150 ubicaciones seleccionadas
✅ Subconjunto 4: 150 ubicaciones seleccionadas
✅ Subconjunto 5: 150 ubicaciones seleccionadas
✅ Subconjunto 6: 150 ubicaciones seleccionadas
✅ Subconjunto 7: 150 ubicaciones seleccionadas
✅ Subconjunto 8: 150 ubicaciones seleccionadas
✅ Subconjunto 9: 150 ubicaciones seleccionadas
✅ Subconjunto 10: 150 ubicaciones seleccionadas

In [ ]:
archivo_salida = "matrices_150.xlsx"

# Save matrices in excel file for later use
with pd.ExcelWriter(archivo_salida, engine="xlsxwriter") as writer:
    for idx, matriz in enumerate(matrices_150):
        hoja_nombre = f"Instancia_{idx+1}"
        matriz.to_excel(writer, sheet_name=hoja_nombre, index=True)

In [ ]:
matrices_150[0]

,413,37,40,332,4,360,189,206,317,107,...,184,270,382,390,381,305,60,376,211,57
413,9999.000000,0.174416,0.234961,0.262736,0.255511,0.036963,0.154548,0.190521,0.164766,0.214139,...,0.107770,0.171175,0.153624,0.105410,0.123637,0.079819,0.214141,0.139579,0.205749,0.186881
37,0.174416,9999.000000,0.080131,0.228316,0.098318,0.138504,0.035411,0.081512,0.059024,0.046395,...,0.088410,0.055036,0.047223,0.069051,0.072280,0.103877,0.064834,0.056989,0.110254,0.050095
40,0.234961,0.080131,9999.000000,0.188269,0.020574,0.202748,0.115528,0.152123,0.072167,0.088133,...,0.166329,0.131128,0.081337,0.134988,0.112424,0.176571,0.020862,0.095537,0.178805,0.048122
332,0.262736,0.228316,0.188269,9999.000000,0.193339,0.253184,0.253019,0.308658,0.170354,0.262986,...,0.272234,0.280030,0.185988,0.225103,0.183416,0.260817,0.183041,0.185090,0.337408,0.180791
4,0.255511,0.098318,0.020574,0.193339,9999.000000,0.223312,0.133464,0.165823,0.092258,0.099270,...,0.185639,0.146907,0.101890,0.155393,0.132797,0.196710,0.041372,0.116036,0.191390,0.068640
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,0.079819,0.103877,0.176571,0.260817,0.196710,0.043656,0.077554,0.111099,0.116571,0.137968,...,0.028520,0.091517,0.100454,0.043381,0.082409,9999.000000,0.156968,0.090522,0.128496,0.131467
60,0.214141,0.064834,0.020862,0.183041,0.041372,0.182125,0.099942,0.141985,0.051571,0.082992,...,0.148180,0.118516,0.060527,0.114880,0.091583,0.156968,9999.000000,0.074679,0.169744,0.027270
376,0.139579,0.056989,0.095537,0.185090,0.116036,0.108656,0.069855,0.127355,0.026538,0.103024,...,0.091759,0.097979,0.014731,0.047396,0.017902,0.090522,0.074679,9999.000000,0.155403,0.047418
211,0.205749,0.110254,0.178805,0.337408,0.191390,0.171541,0.085549,0.028808,0.167053,0.092283,...,0.100125,0.057614,0.151822,0.131363,0.163403,0.128496,0.169744,0.155403,9999.000000,0.160148
57,0.186881,0.050095,0.048122,0.180791,0.068640,0.155081,0.082184,0.131488,0.025792,0.082858,...,0.125061,0.104990,0.033298,0.088730,0.064476,0.131467,0.027270,0.047418,0.160148,9999.000000

## Read pre-generated submatrices

In [15]:

archivo = "/content/tsp-bio-inspired-algorithms/Data_for_algorithms/matrices_150.xlsx"

# Read Excel file with matrices.
hojas_dict = pd.read_excel(archivo, sheet_name=None, index_col=0)

matrices_150 = [hojas_dict[f"Instancia_{i+1}"] for i in range(10)]

# Validate
print(len(matrices_150))
print(matrices_150[0].head())
print(matrices_150[0].shape)

10
             413          37           40           332          4    \
413  9999.000000     0.174416     0.234961     0.262736     0.255511
37      0.174416  9999.000000     0.080131     0.228316     0.098318
40      0.234961     0.080131  9999.000000     0.188269     0.020574
332     0.262736     0.228316     0.188269  9999.000000     0.193339
4       0.255511     0.098318     0.020574     0.193339  9999.000000

          360       189       206       317       107  ...       184  \
413  0.036963  0.154548  0.190521  0.164766  0.214139  ...  0.107770
37   0.138504  0.035411  0.081512  0.059024  0.046395  ...  0.088410
40   0.202748  0.115528  0.152123  0.072167  0.088133  ...  0.166329
332  0.253184  0.253019  0.308658  0.170354  0.262986  ...  0.272234
4    0.223312  0.133464  0.165823  0.092258  0.099270  ...  0.185639

          270       382       390       381       305       60        376  \
413  0.171175  0.153624  0.105410  0.123637  0.079819  0.214141  0.139579
37   0.055036  0.047223  0.069051  0.072280  0.103877  0.064834  0.056989
40   0.131128  0.081337  0.134988  0.112424  0.176571  0.020862  0.095537
332  0.280030  0.185988  0.225103  0.183416  0.260817  0.183041  0.185090
4    0.146907  0.101890  0.155393  0.132797  0.196710  0.041372  0.116036

          211       57
413  0.205749  0.186881
37   0.110254  0.050095
40   0.178805  0.048122
332  0.337408  0.180791
4    0.191390  0.068640

[5 rows x 150 columns]
(150, 150)

## Solve TSP 150 addresses with NEOS

In [ ]:
resultados_150 = {}

# Solve each 150-node instance, and store the transition matrices, tour, objective value, and solution time inside a dictionary.
for idx, matriz in enumerate(matrices_150):
    print(f"✅ Resolviendo instancia {idx+1}")
    print(matriz.columns)

    mat, camino, sec, obj, t = solve_tsp_neos(matriz, matriz.columns, n = True)


    count(sec)

    resultados_150[idx] = {
        "mat": mat,
        "camino": camino,
        "secuencia": sec,
        "objetivo": obj,
        "time": t
    }

    print(f"✅ Finalizado con instancia {idx+1}, {camino.shape[0]}, {sec},  (Objetivo: {obj})")

# Solving instances of 200 addresses

## Generate distance submatrices (matrices_200.xlsx).

In [ ]:
# Generate 10 instances of sub matrices consisting of 150 randomly chosen addresses. (matrices_100.xlsx)
matrices_200, subconjuntos = generar_submatrices_distancias(df_matriz_dist, n_subconjuntos=10, tamaño_sub=200)

✅ Subconjunto 1: 200 ubicaciones seleccionadas
✅ Subconjunto 2: 200 ubicaciones seleccionadas
✅ Subconjunto 3: 200 ubicaciones seleccionadas
✅ Subconjunto 4: 200 ubicaciones seleccionadas
✅ Subconjunto 5: 200 ubicaciones seleccionadas
✅ Subconjunto 6: 200 ubicaciones seleccionadas
✅ Subconjunto 7: 200 ubicaciones seleccionadas
✅ Subconjunto 8: 200 ubicaciones seleccionadas
✅ Subconjunto 9: 200 ubicaciones seleccionadas
✅ Subconjunto 10: 200 ubicaciones seleccionadas

In [ ]:
archivo_salida = "matrices_200.xlsx"

# Save matrices in Excel file for later use.
with pd.ExcelWriter(archivo_salida, engine="xlsxwriter") as writer:
    for idx, matriz in enumerate(matrices_200):
        hoja_nombre = f"Instancia_{idx+1}"
        matriz.to_excel(writer, sheet_name=hoja_nombre, index=True)

In [ ]:
matrices_200[0]

,127,408,335,287,27,190,119,417,320,99,...,424,24,372,354,33,77,138,135,71,407
127,9999.000000,0.108063,0.161569,0.114270,0.055300,0.130711,0.111372,0.161093,0.122911,0.051919,...,0.099551,0.041212,0.206993,0.160260,0.057550,0.081072,0.006689,0.032954,0.044456,0.416465
408,0.108063,9999.000000,0.066935,0.045277,0.055073,0.049593,0.069167,0.057531,0.035141,0.056247,...,0.070922,0.069451,0.104050,0.085302,0.081694,0.040811,0.111998,0.116104,0.102653,0.308430
335,0.161569,0.066935,9999.000000,0.105861,0.116482,0.032395,0.067244,0.075888,0.038863,0.112193,...,0.136324,0.120371,0.104666,0.034223,0.147375,0.107572,0.163662,0.158194,0.139821,0.265420
287,0.114270,0.045277,0.105861,9999.000000,0.061106,0.094349,0.112835,0.056767,0.079919,0.071265,...,0.033796,0.086537,0.097225,0.129206,0.066529,0.034034,0.119989,0.133423,0.125723,0.315937
27,0.055300,0.055073,0.116482,0.061106,9999.000000,0.089637,0.085371,0.105845,0.078223,0.013785,...,0.056952,0.027012,0.151698,0.124303,0.035240,0.027073,0.060316,0.072387,0.066467,0.362752
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,0.081072,0.040811,0.107572,0.034034,0.027073,0.086452,0.093572,0.082060,0.072777,0.037840,...,0.037411,0.052914,0.126761,0.122667,0.041722,9999.000000,0.086536,0.099412,0.092391,0.341368
138,0.006689,0.111998,0.163662,0.119989,0.060316,0.132401,0.111329,0.165835,0.125219,0.055753,...,0.106006,0.043786,0.211933,0.160970,0.064190,0.086536,9999.000000,0.027287,0.040837,0.420195
135,0.032954,0.116104,0.158194,0.133423,0.072387,0.125904,0.098573,0.172828,0.121536,0.063013,...,0.125192,0.047876,0.219503,0.149948,0.086369,0.099412,0.027287,9999.000000,0.020009,0.420433
71,0.044456,0.102653,0.139821,0.125723,0.066467,0.107433,0.078781,0.160096,0.104139,0.054568,...,0.122572,0.039568,0.206695,0.130254,0.088195,0.092391,0.040837,0.020009,9999.000000,0.403406
407,0.416465,0.308430,0.265420,0.315937,0.362752,0.297338,0.332296,0.259988,0.299267,0.364567,...,0.347237,0.376831,0.220518,0.286233,0.381315,0.341368,0.420195,0.420433,0.403406,9999.000000

## Read pre-generated submatrices

In [16]:
archivo = "/content/tsp-bio-inspired-algorithms/Data_for_algorithms/matrices_200.xlsx"

hojas_dict = pd.read_excel(archivo, sheet_name=None, index_col=0)

# Read Excel file with matrices
matrices_200 = [hojas_dict[f"Instancia_{i+1}"] for i in range(10)]

# Validate
print(len(matrices_200))
print(matrices_200[0].head())
print(matrices_200[0].shape)

10
             127          408          335          287          27   \
127  9999.000000     0.108063     0.161569     0.114270     0.055300
408     0.108063  9999.000000     0.066935     0.045277     0.055073
335     0.161569     0.066935  9999.000000     0.105861     0.116482
287     0.114270     0.045277     0.105861  9999.000000     0.061106
27      0.055300     0.055073     0.116482     0.061106  9999.000000

          190       119       417       320       99   ...       424  \
127  0.130711  0.111372  0.161093  0.122911  0.051919  ...  0.099551
408  0.049593  0.069167  0.057531  0.035141  0.056247  ...  0.070922
335  0.032395  0.067244  0.075888  0.038863  0.112193  ...  0.136324
287  0.094349  0.112835  0.056767  0.079919  0.071265  ...  0.033796
27   0.089637  0.085371  0.105845  0.078223  0.013785  ...  0.056952

          24        372       354       33        77        138       135  \
127  0.041212  0.206993  0.160260  0.057550  0.081072  0.006689  0.032954
408  0.069451  0.104050  0.085302  0.081694  0.040811  0.111998  0.116104
335  0.120371  0.104666  0.034223  0.147375  0.107572  0.163662  0.158194
287  0.086537  0.097225  0.129206  0.066529  0.034034  0.119989  0.133423
27   0.027012  0.151698  0.124303  0.035240  0.027073  0.060316  0.072387

          71        407
127  0.044456  0.416465
408  0.102653  0.308430
335  0.139821  0.265420
287  0.125723  0.315937
27   0.066467  0.362752

[5 rows x 200 columns]
(200, 200)

## Solve TSP 200 addresses with NEOS

In [ ]:
# Solve each 200-node instance, and store the transition matrices, tour, objective value, and solution time inside a dictionary.
resultados_200 = {}
print(f"✅ Resolviendo instancia {idx+1}")
print(matrices_200[2].columns)

mat, camino, sec, obj, t = solve_tsp_neos(matrices_200[2], matrices_200[2].columns, n = True)


count(sec)

resultados_200[idx] = {
    "mat": mat,
    "camino": camino,
    "secuencia": sec,
    "objetivo": obj,
    "time": t
}

print(f"✅ Finalizado con instancia {idx+1}, {camino.shape[0]}, {sec},  (Objetivo: {obj})")

✅ Resolviendo instancia 9
Index([131, 204, 230, 335, 250, 165, 115, 383, 225,  93,
       ...
       276,   8, 302, 366, 382, 167, 267, 256, 129,   7],
      dtype='int64', length=200)

[NEOS - INFO] Job Number: 17951780, Job Password: CxqfFMHp
INFO:NEOS:Job Number: 17951780, Job Password: CxqfFMHp

In [ ]:
print(f"✅ Resolviendo instancia {idx+1}")
print(matrices_200[2].columns)

mat, camino, sec, obj, t = solve_tsp_neos(matrices_200[3], matrices_200[3].columns, n = True)


count(sec)

resultados_200[idx] = {
    "mat": mat,
    "camino": camino,
    "secuencia": sec,
    "objetivo": obj,
    "time": t
}

print(f"✅ Finalizado con instancia {idx+1}, {camino.shape[0]}, {sec},  (Objetivo: {obj})")